import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const WF=createRequire(import.meta.url)('../clinical-workflow.js');let n=0;const eq=(a,b,m)=>{assert.deepEqual(a,b,m);n++},ok=(a,m)=>{assert.ok(a,m);n++};
const p=WF.defaultAlertProtocol();eq(p.map,{warningLow:70,criticalLow:60,warningHigh:null,criticalHigh:null});eq(p.spo2.warningLow,95);eq(p.spo2.criticalLow,90);eq(p.etco2,{warningLow:40,criticalLow:30,warningHigh:55,criticalHigh:60});eq(p.temp,{warningLow:99,criticalLow:98,warningHigh:null,criticalHigh:null});
for(const [key,vals]of Object.entries({map:[[59,'danger'],[60,'warn'],[69,'warn'],[70,'good']],spo2:[[89,'danger'],[90,'warn'],[94,'warn'],[95,'good']],etco2:[[29,'danger'],[30,'warn'],[40,'good'],[55,'good'],[56,'warn'],[60,'warn'],[61,'danger']],temp:[[97.9,'danger'],[98,'warn'],[98.9,'warn'],[99,'good']]}))for(const [v,l]of vals)eq(WF.classifyAlert(key,v,p),l,`${key} ${v}`);
for(const k of WF.metrics)for(const v of [null,undefined,'',' ','bad',Infinity])eq(WF.classifyAlert(k,v,p),'neutral');
ok(WF.validateAlertProtocol(p).valid);for(const [key,field,value]of [['map','criticalLow',70],['spo2','criticalHigh',101],['temp','warningHigh',110],['etco2','warningHigh',20],['map','warningLow','bad']]){const x=WF.clone(p);x[key][field]=value;ok(!WF.validateAlertProtocol(x).valid,`${key}.${field} invalid`)}
ok(!WF.validateAlertProtocol({...p,temperatureUnit:'C'}).valid);ok(!WF.validateAlertProtocol({...p,schema:2}).valid);
const h=WF.clone(p);h.map.warningLow=85;h.map.criticalLow=80;eq(WF.effectiveAlertProtocol({},h),h);eq(WF.effectiveAlertProtocol({caseStartedAt:1},h),p);eq(WF.effectiveAlertProtocol({protocolSnapshot:{version:'old'}},h),p);eq(WF.effectiveAlertProtocol({protocolSnapshot:{alertProtocol:p}},h),p);eq(WF.effectiveAlertProtocol({protocolSnapshot:{alertProtocol:p},alertProtocolOverride:{protocol:h}},p),h);
eq(WF.measuredRange([{map:null},{map:''},{map:'75'},{map:60}],'map'),{min:60,max:75});eq(WF.measuredRange([{temp:null},{temp:''}],'temp'),null);
const c={weight:'4',records:[{epoch:5,map:70,temp:null},{epoch:2,map:55,temp:''}],recoveryRecords:[{epoch:8,spo2:99}],drugAdministrations:[{drug:'A',actual:1},{drug:'B',voidedAt:1}],alertEpisodes:[{id:'1'},{id:'2',resolvedAt:1}],complications:[{id:'3',status:'active'},{id:'4',status:'resolved'}],fluidActualTotal:'',events:[{category:'Emergency',name:'Emergency return to OR'}]};const out=WF.buildHandoff(c,10);eq(out.latestAnesthesia.epoch,5);eq(out.latestRecovery.epoch,8);eq(out.extrema.temp,null);eq(out.fluids.actualTotal,null);eq(out.weight,4);eq(out.administrations.length,1);eq(out.alerts.length,1);eq(out.complications.length,1);eq(out.emergencyReturns,1);out.administrations[0].actual=8;eq(c.drugAdministrations[0].actual,1,'handoff immutable copy');
console.log(`Production clinical helpers: PASS (${n} assertions)`);
