import assert from 'node:assert/strict';import {createDomApp,setupPatient} from './dom_harness.mjs';
let n=0;const eq=(a,b,m)=>{assert.deepEqual(a,b,m);n++},ok=(a,m)=>{assert.ok(a,m);n++};
const seed=await createDomApp();let legacy,settings;try{await setupPatient(seed,{weight:10});await seed.click('orStartBtn');legacy=seed.state();settings=JSON.parse(JSON.stringify(seed.api.currentSettingsObject()));for(const k of ['alertProtocolOverride','alertProtocolHistory','recoveryHandoffs'])delete legacy[k];delete legacy.protocolSnapshot.alertProtocol;settings.alertProtocol=seed.w.AnesvetWorkflow.defaultAlertProtocol();settings.alertProtocol.map={warningLow:85,criticalLow:80,warningHigh:null,criticalHigh:null};settings.criticalPopupEnabled=false}finally{seed.close()}
const a=await createDomApp({current:legacy,settings});try{
 eq(a.api.activeAlertProtocol().map.criticalLow,60);ok(a.el('orAlertProtocolStatus').textContent.includes('LEGACY'));a.set('orMap',75);await a.settle();eq(a.state().alertEpisodes.filter(x=>!x.resolvedAt).length,0);await a.click('orOpenDrugBtn');a.set('orQuickDrugSelect',1);ok(a.el('orQuickDrugCalculation').textContent.includes('4 mL'));a.el('orQuickDrugDialog').close();
 await a.click('editCaseAlertBtn');a.set('alert_map_criticalLow',65);a.set('alertProtocolActor','Dr Test');a.set('alertProtocolReason','TEST temporary override');await a.click('saveAlertProtocolBtn');eq(a.api.activeAlertProtocol().map.criticalLow,65);await a.click('editCaseAlertBtn');a.set('alertProtocolActor','Dr Test');a.set('alertProtocolReason','TEST return to baseline');await a.click('clearCaseAlertOverrideBtn');eq(a.api.activeAlertProtocol().map.criticalLow,60);eq(a.state().alertProtocolHistory.length,2);
 a.set('orMap',55);await a.settle();a.w.document.querySelector('#orProblemPanel [data-problem-action="resolve"]').click();a.set('problemActionActor','Dr Test');a.set('problemActionNote','TEST artifact verified');await a.click('saveProblemActionBtn');eq(a.state().alertEpisodes.at(-1).resolutionMethod,'manual');a.set('orHr',100);await a.settle();eq(a.state().alertEpisodes.filter(x=>!x.resolvedAt).length,0);
 const b=await createDomApp({current:a.state(),settings});try{eq(b.state().alertEpisodes.filter(x=>!x.resolvedAt).length,0,'manual resolution survives reload');b.set('orMap',55);await b.settle();eq(b.state().alertEpisodes.filter(x=>!x.resolvedAt).length,1,'new observation reopens');eq(b.errors,[])}finally{b.close()}
 // Real unit conversion function, including mixed mg / microgram concentration units.
 eq(a.api.calculateLibraryDrug({mode:'mcgkg',concUnit:'mg/mL'},10,2,1).ml,.02);eq(a.api.calculateLibraryDrug({mode:'mgkg',concUnit:'μg/mL'},10,2,1000).ml,20);
 eq(a.api.caseLowestMap({records:[{map:''},{map:null},{map:75}]}),75);eq(a.api.caseLowestSpo2({records:[{spo2:''}]}),null);eq(a.api.caseLowestTemp({records:[{temp:null}]}),null);
 const locked=JSON.parse(JSON.stringify(legacy));locked.caseLocked=true;locked.casePhase='complete';locked.timer={running:false,elapsedMs:1000,startedEpoch:null};locked.lockedAt=Date.now();locked.checksumAlgorithm='SHA-256';locked.finalChecksum=await a.api.computeCaseChecksum(locked);const bytes=JSON.stringify(locked);
 const c=await createDomApp({current:bytes,archive:[locked],settings});try{eq(c.w.localStorage.getItem('anesvet_v14_3_current'),bytes,'locked persisted payload not rewritten');eq(await c.api.computeCaseChecksum(c.api.getState()),locked.finalChecksum,'in-memory clinical checksum unchanged');for(const id of ['orOpenDrugBtn','editCaseAlertBtn'])await c.click(id);ok(!c.el('orQuickDrugDialog').open);ok(!c.el('alertProtocolDialog').open);eq(c.api.recordDrugAdministration({drug:'TEST',actual:1,route:'IV',administeredBy:'Dr Test'}),null);const verified=await c.api.verifyBackupPayloadIntegrity({current:locked,archive:[locked]});eq(verified.valid,2);const tampered=JSON.parse(bytes);tampered.weight=999;eq((await c.api.verifyBackupPayloadIntegrity({current:tampered,archive:[]})).mismatch,1);eq(c.errors,[])}finally{c.close()}
 const v=await createDomApp({current:legacy,settings,seedStorage:{anesvet_v14_3_active_session:{tabId:'another-tab',heartbeatAt:Date.now()}}});try{const before=v.w.localStorage.getItem('anesvet_v14_3_current');await v.click('orOpenDrugBtn');await v.click('editCaseAlertBtn');ok(!v.el('orQuickDrugDialog').open);ok(!v.el('alertProtocolDialog').open);eq(v.api.recordDrugAdministration({drug:'TEST',actual:1,route:'IV',administeredBy:'Dr Test'}),null);eq(v.w.localStorage.getItem('anesvet_v14_3_current'),before);eq(v.errors,[])}finally{v.close()}
 const missing=JSON.parse(JSON.stringify(legacy));delete missing.protocolSnapshot.builtInProtocol;const m=await createDomApp({current:missing,settings});try{await m.click('orOpenDrugBtn');m.set('orQuickDrugSelect',1);ok(m.el('orQuickDrugSaveBtn').disabled,'missing frozen dose must not use current hospital defaults');eq(m.errors,[])}finally{m.close()}
 eq(a.errors,[]);
}finally{a.close()}
console.log(`V14.6.4 compatibility / integrity: PASS (${n} assertions; synthetic fixtures)`);
