import assert from 'node:assert/strict';import {createDomApp,setupPatient} from './dom_harness.mjs';
let n=0;const eq=(a,b,m)=>{assert.deepEqual(a,b,m);n++},ok=(a,m)=>{assert.ok(a,m);n++};
const a=await createDomApp();try{
 await setupPatient(a);eq(Number(a.state().weight),12.5);ok(a.state().patientSaved);eq(a.errors,[]);
 await a.click('editHospitalAlertBtn');ok(a.el('alertProtocolDialog').open);await a.click('saveAlertProtocolBtn');ok(a.el('alertProtocolDialog').open,'reason required');a.set('alertProtocolActor','Dr Test');a.set('alertProtocolReason','TEST hospital review');a.set('alert_map_criticalLow',75);await a.click('saveAlertProtocolBtn');ok(a.el('alertProtocolError').textContent.length>0);a.set('alert_map_warningLow',72);a.set('alert_map_criticalLow',62);await a.click('saveAlertProtocolBtn');ok(!a.el('alertProtocolDialog').open);eq(a.api.currentSettingsObject().alertProtocol.map.criticalLow,62);const audits=JSON.parse(a.w.localStorage.getItem('anesvet_v14_3_protocol_audit'));eq(audits.at(-1).before.map.criticalLow,60);eq(audits.at(-1).after.map.criticalLow,62);
 await a.click('orStartBtn');ok(a.state().caseStartedAt);const frozen=JSON.stringify(a.state().protocolSnapshot);a.set('settingPropofolDose',2);a.set('settingPropofolConc',20);a.set('settingCriticalPopup',false);await a.click('saveSettingsBtn');eq(a.el('propofolConc').value,'10');eq(JSON.stringify(a.state().protocolSnapshot),frozen);
 await a.click('editHospitalAlertBtn');a.set('alert_map_criticalLow',64);a.set('alertProtocolActor','Dr Test');a.set('alertProtocolReason','TEST later hospital review');await a.click('saveAlertProtocolBtn');eq(a.api.activeAlertProtocol().map.criticalLow,62);
 a.set('orMap',68);await a.settle();let ep=a.state().alertEpisodes.find(x=>!x.resolvedAt);eq(ep.level,'warn');ok(!a.el('clinicalGuideDialog').open,'popup off still tracks');
 a.w.document.querySelector('#orProblemPanel [data-problem-action="ack"]').click();a.set('problemActionActor','Dr Test');await a.click('saveProblemActionBtn');ok(a.state().alertEpisodes[0].acknowledgedAt);
 a.set('orMap',55);await a.settle();ep=a.state().alertEpisodes[0];eq(ep.level,'danger');eq(ep.acknowledgedAt,null);a.w.document.querySelector('#orProblemPanel [data-problem-action="intervention"]').click();a.set('problemActionNote','TEST verify measurement and reassess');await a.click('saveProblemActionBtn');eq(a.state().alertEpisodes[0].interventions.length,1);
 a.set('orMap','');await a.settle();ok(!a.state().alertEpisodes[0].resolvedAt,'blank does not resolve');a.set('orMap',75);await a.settle();ok(a.state().alertEpisodes[0].resolvedAt);a.set('orSpo2',89);a.set('orEtco2',65);a.set('orTemp',36);await a.settle();eq(a.state().alertEpisodes.filter(x=>!x.resolvedAt).length,3);
 a.set('orHr',100);a.set('orRr',12);await a.click('orRecordNowBtn');eq(a.state().records.length,1);eq(a.state().records[0].alertProtocol.map.criticalLow,62);
 await a.click('editCaseAlertBtn');a.set('alert_map_warningLow',68);a.set('alert_map_criticalLow',58);a.set('alertProtocolActor','Dr Test');a.set('alertProtocolReason','TEST case target');await a.click('saveAlertProtocolBtn');eq(a.state().alertProtocolHistory.length,1);eq(a.api.activeAlertProtocol().map.criticalLow,58);eq(a.state().records[0].alertProtocol.map.criticalLow,62);eq(JSON.stringify(a.state().protocolSnapshot),frozen);
 await a.click('openOrLiveBtn');await a.click('orOpenDrugBtn');ok(a.el('orQuickDrugDialog').open);a.set('orQuickDrugSelect',1);eq(a.el('orQuickDrugActual').value,'');ok(a.el('orQuickDrugCalculation').textContent.includes('5 mL'));await a.click('orQuickDrugSaveBtn');eq(a.state().drugAdministrations.length,0);a.set('orQuickDrugActual',1.5);a.set('orQuickDrugRoute','IV');a.set('orQuickDrugBy','Dr Test');await a.click('orQuickDrugSaveBtn');eq(a.state().drugAdministrations.length,1);const d=a.state().drugAdministrations[0];eq(d.actual,1.5);eq(d.calculationBasis.calculatedMl,5);eq(d.calculationBasis.weightKg,12.5);eq(d.concentration,'10 mg/mL');eq(d.source,'OR Quick Drug');ok(a.state().events.some(e=>e.drugAdministrationId===d.id));ok(a.el('orlive').classList.contains('active'));
 await a.click('orOpenDrugBtn');a.set('orQuickDrugSelect',1);a.set('orQuickDrugActual',1);a.w.confirm=msg=>!msg.includes('also documented recently');await a.click('orQuickDrugSaveBtn');eq(a.state().drugAdministrations.length,1,'duplicate denied');a.el('orQuickDrugDialog').close();a.w.confirm=()=>true;
 a.set('orSpo2',98);a.set('orEtco2',45);a.set('orTemp',38);for(let i=0;i<4;i++)a.set('orHr',100+i);await a.click('orStickyRecordBtn');eq(a.state().records.length,2,'single sticky record listener');
 await a.click('orBeginRecoveryBtn');eq(a.state().casePhase,'recovery');eq(a.state().recoveryHandoffs.length,1);ok(a.el('recoveryHandoffText').textContent.includes('Propofol: 1.5 mL'));const handoff=JSON.stringify(a.state().recoveryHandoffs[0]);for(const [k,v]of Object.entries({recHR:100,recRR:12,recMAP:75,recSpO2:98,recTemp:38}))a.set(k,v);await a.click('recordRecoveryVitalsBtn');eq(a.state().recoveryRecords.length,1);eq(JSON.stringify(a.state().recoveryHandoffs[0]),handoff);
 await a.click('emergencyReturnOrBtn');eq(a.state().casePhase,'emergency');await a.click('orBeginRecoveryBtn');eq(a.state().casePhase,'recovery');eq(a.state().recoveryHandoffs.length,2);eq(a.state().recoveryHandoffs[1].emergencyReturns,1);
 const b=await createDomApp({current:a.state(),settings:a.api.currentSettingsObject()});try{eq(b.state().drugAdministrations.length,1);eq(b.state().recoveryHandoffs.length,2);ok(b.el('recovery').classList.contains('active'));await b.click('moreMenuBtn');b.w.document.querySelector('[data-more-tab="dashboard"]').click();ok(b.el('dashboard').classList.contains('active'));eq(b.errors,[])}finally{b.close()}
 eq(a.errors,[]);
}finally{a.close()}
// Actual Extubation UI route must create a timestamped handoff.
const x=await createDomApp();try{x.w.document.querySelector('.or-milestone[data-label="Extubation"]').click();await x.settle();eq(x.state()?.casePhase||'setup','setup','Extubation cannot start invalid case');await setupPatient(x);await x.click('orStartBtn');x.set('orMap',75);x.set('orSpo2',98);await x.click('orRecordNowBtn');x.w.document.querySelector('.or-milestone[data-label="Extubation"]').click();await x.settle();eq(x.state().casePhase,'recovery');ok(x.state().extubatedAt);eq(x.state().recoveryHandoffs.length,1);ok(/extubation/i.test(x.state().recoveryHandoffs[0].reason));eq(x.state().recoveryHandoffs[0].latestAnesthesia.map,75);eq(x.errors,[])}finally{x.close()}
console.log(`Full DOM workflow including Extubation: PASS (${n} assertions; jsdom, not browser E2E)`);
