import assert from 'node:assert/strict';import {createDomApp,setupPatient} from './dom_harness.mjs';let n=0;const eq=(a,b,m)=>{assert.deepEqual(a,b,m);n++},ok=(a,m)=>{assert.ok(a,m);n++};
const a=await createDomApp();try{
 await setupPatient(a,{species:'cat',weight:4});a.set('settingProtocolVersion','TEST-1');await a.click('saveSettingsBtn');await a.click('editHospitalAlertBtn');a.set('alert_map_warningLow',72);a.set('alert_map_criticalLow',62);a.set('alert_temp_warningHigh',103);a.set('alert_temp_criticalHigh',105);a.set('alertProtocolActor','Dr Test');a.set('alertProtocolReason','TEST configured upper alert');await a.click('saveAlertProtocolBtn');await a.click('toggleProtocolLockBtn');ok(a.api.currentSettingsObject().protocolLocked);await a.click('editHospitalAlertBtn');ok(!a.el('alertProtocolDialog').open,'hospital protocol lock enforced');await a.click('orStartBtn');
 a.set('orMap',61);await a.settle();ok(a.el('clinicalGuideNote').textContent.includes('Critical <62'),'guide reflects configured threshold');await a.click('clinicalGuideDismissBtn');a.set('orMap',75);a.set('orTemp',42);await a.settle();ok(a.el('clinicalGuideDialog').open);ok(a.el('clinicalGuideTitle').textContent.includes('above configured threshold'));ok(!/warming/i.test(a.el('clinicalGuideSteps').textContent),'upper temperature must not suggest warming');await a.click('clinicalGuideComplicationBtn');eq(a.el('complicationType').value,'Other');a.el('complicationDialog').close();a.set('orTemp',41);await a.settle();eq(a.state().alertEpisodes.filter(e=>e.metric==='temp').length,1);a.set('orTemp',38);await a.settle();ok(a.state().alertEpisodes.find(e=>e.metric==='temp').resolvedAt);
 await a.click('orOpenDrugBtn');const names=a.el('orQuickDrugSelect').textContent;ok(names.includes('Meloxicam'));ok(!names.includes('Carprofen'));a.set('orQuickDrugSelect',1);a.set('orQuickDrugActual',1);a.set('weight',5);await a.click('savePatientBtn');await a.click('orQuickDrugSaveBtn');eq(a.state().drugAdministrations.length,0);ok(a.el('orQuickDrugError').textContent.includes('BW/protocol changed'));eq(a.el('orQuickDrugActual').value,'');ok(a.el('orQuickDrugCalculation').textContent.includes('2 mL'));a.set('orQuickDrugActual',.5);a.set('orQuickDrugRoute','IV');a.set('orQuickDrugBy','Dr Test');await a.click('orQuickDrugSaveBtn');eq(a.state().drugAdministrations[0].calculationBasis.weightKg,5);
 a.w.document.querySelector('.drug-admin-void').click();await a.settle();ok(a.state().drugAdministrations[0].voidedAt);await a.click('orBeginRecoveryBtn');eq(a.state().recoveryHandoffs[0].administrations.length,0);await a.click('emergencyReturnOrBtn');a.set('orSpo2',85);await a.settle();if(a.el('clinicalGuideDialog').open)await a.click('clinicalGuideDismissBtn');await a.click('orBeginRecoveryBtn');for(const [id,v]of Object.entries({recHR:100,recRR:15,recMAP:75,recTemp:38}))a.set(id,v);a.w.document.querySelector('.recovery-observation-na-btn[data-key="spo2"]').click();a.set('recNaReason','Sensor unavailable');await a.click('recordRecoveryVitalsBtn');eq(a.state().recoveryRecords.at(-1).spo2,null);ok(a.state().alertEpisodes.some(x=>x.metric==='spo2'&&!x.resolvedAt),'N/A does not resolve alert');await a.click('emergencyReturnOrBtn');await a.click('addComplicationBtn');a.set('complicationType','Airway problem');a.set('complicationAssessment','TEST assessment');await a.click('complicationSaveBtn');ok(a.w.document.querySelector('#orProblemPanel [data-kind="problem"]'),'complication appears in active panel');
 for(const action of ['ack','intervention','resolve']){a.w.document.querySelector('#orProblemPanel [data-kind="problem"][data-problem-action="'+action+'"]').click();a.set('problemActionActor','Dr Test');a.set('problemActionNote','TEST '+action);await a.click('saveProblemActionBtn')}
 const problem=a.state().complications.at(-1);ok(problem.acknowledgedAt);eq(problem.responses.length,2);eq(problem.status,'resolved');eq(problem.resolvedBy,'Dr Test');ok(!a.w.document.querySelector('#orProblemPanel [data-kind="problem"]'),'resolved problem leaves active panel');eq(a.errors,[]);
}finally{a.close()}
console.log(`Protocol governance / species / BW / recovery N/A: PASS (${n} assertions)`);
