/* ANESVET V16.21.0 — Production Pilot & Real-device Reliability
   Technical acceptance instrumentation only. No clinical calculations, decisions,
   thresholds, medication semantics, or record payloads are changed by this module. */
(function(root){
'use strict';

const VERSION='16.21.0';
const ACCEPTANCE_KEY='anesvet_v16_17_pilot_acceptance';
const LIFECYCLE_KEY='anesvet_v16_17_lifecycle_log';
const LAST_READINESS_KEY='anesvet_v16_17_last_readiness';
const MAX_EVENTS=120;
const PROBE_DB='ANESVET_V16_17_PROBE';

const SCENARIOS=Object.freeze([
  {id:'normal-final',title:'Routine case → Final Lock → VERIFIED → New case',detail:'Complete a normal simulated case and confirm final archive verification before starting the next case.',required:true},
  {id:'background-5m',title:'Background / screen lock ≥ 5 min',detail:'During an active case, lock the screen or switch apps for at least 5 minutes, return, then confirm timer, case phase and latest data remain correct.',required:true},
  {id:'background-30m',title:'Background ≥ 30 min',detail:'Repeat a longer Android/iPad task-switch or screen-lock interval and verify the active case resumes without losing recent records.',required:true},
  {id:'kill-reopen',title:'Force close / browser kill → reopen',detail:'With a simulated active case saved, close the app/browser from the task switcher and reopen. Confirm the same case and recent records recover correctly.',required:true},
  {id:'offline-reconnect',title:'Offline documentation → reconnect',detail:'Disable network, continue local documentation, then reconnect. Confirm local saves continue and no clinical record disappears.',required:true},
  {id:'duplicate-tab',title:'Duplicate tab / session takeover guard',detail:'Open ANESVET twice on the same device. Confirm the second tab is view-only until explicit takeover and that writers do not silently overwrite each other.',required:true},
  {id:'update-active-case',title:'PWA update deferred during mutable case',detail:'When an update is waiting during an active mutable case, confirm Update now is blocked/deferred until the case is safely finalized or reset.',required:true},
  {id:'recovery-final',title:'Recovery → handoff → complete → Final Lock',detail:'Run serial Recovery records, medication reconciliation and transfer handoff, then complete Recovery and Final Lock.',required:true},
  {id:'backup-restore',title:'Verified backup + restore on test dataset',detail:'Create a Full Backup, validate it, restore it on a disposable/test dataset or test installation, and confirm case/patient counts and locked checksums.',required:true},
  {id:'long-case',title:'Long-case endurance ≥ 2 hours',detail:'Keep a simulated case active for at least 2 hours with repeated vital/event/drug entries and normal device sleep/task switching.',required:true},
  {id:'orientation-keyboard',title:'Portrait / landscape + soft keyboard',detail:'Test OR Fast Vital Entry and Quick Drug in portrait and landscape; keyboard must not hide Save/primary actions and docks must stay inside the viewport.',required:true},
  {id:'archive-failure',title:'Archive failure / retry path',detail:'If practical in a test environment, force or simulate archive-storage failure and verify the locked current case remains available until retry succeeds.',required:false}
]);

let adapter={};
let started=false;
let lastHiddenAt=0;
let lastReadiness=null;

const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function jsonRead(key,fallback){try{const v=JSON.parse(localStorage.getItem(key)||'null');return v??fallback}catch(_){return fallback}}
function jsonWrite(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true}catch(_){return false}}
function acceptance(){const raw=jsonRead(ACCEPTANCE_KEY,{});const out={};for(const s of SCENARIOS){const v=raw?.[s.id]||{};out[s.id]={status:['pass','fail','blocked','not-run'].includes(v.status)?v.status:'not-run',note:String(v.note||'').slice(0,500),updatedAt:Number(v.updatedAt)||0}}return out}
function saveAcceptance(data){return jsonWrite(ACCEPTANCE_KEY,data)}
function eventLog(){const rows=jsonRead(LIFECYCLE_KEY,[]);return Array.isArray(rows)?rows.slice(-MAX_EVENTS):[]}
function appState(){try{return adapter.getState?.()||root.AnesvetApp?.getState?.()||{}}catch(_){return{}}}
function caseMeta(){const s=appState();const active=!!(s?.patientSaved||s?.caseStartedAt||s?.timer?.running||(s?.records||[]).length||(s?.events||[]).length||(s?.drugAdministrations||[]).length);return{active,caseId:s?.caseId||'',phase:s?.casePhase||'preop',locked:!!s?.caseLocked,lastSavedAt:Number(s?.lastSavedAt)||0,timerRunning:!!s?.timer?.running,recordCount:(s?.records||[]).length,eventCount:(s?.events||[]).length,drugCount:(s?.drugAdministrations||[]).length}}
function deviceContext(){let standalone=false;try{standalone=root.matchMedia?.('(display-mode: standalone)')?.matches||navigator.standalone===true}catch(_){ }return{userAgent:navigator.userAgent||'',platform:navigator.userAgentData?.platform||navigator.platform||'',language:navigator.language||'',viewport:`${root.innerWidth||0}x${root.innerHeight||0}`,screen:`${root.screen?.width||0}x${root.screen?.height||0}`,pixelRatio:root.devicePixelRatio||1,touchPoints:navigator.maxTouchPoints||0,online:navigator.onLine!==false,standalone,visibility:document.visibilityState||'',timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'',orientation:root.screen?.orientation?.type||String(root.orientation||'')}}
function logEvent(type,detail={}){const rows=eventLog();const m=caseMeta();rows.push({epoch:Date.now(),type:String(type||'event'),visibility:document.visibilityState||'',online:navigator.onLine!==false,case:{active:m.active,phase:m.phase,locked:m.locked,lastSavedAgeMs:m.lastSavedAt?Math.max(0,Date.now()-m.lastSavedAt):null,recordCount:m.recordCount,eventCount:m.eventCount,drugCount:m.drugCount},detail});jsonWrite(LIFECYCLE_KEY,rows.slice(-MAX_EVENTS));renderLifecycle();return rows[rows.length-1]}
function formatWhen(epoch){if(!epoch)return '—';try{return new Date(epoch).toLocaleString()}catch(_){return String(epoch)}}
function formatDuration(ms){const sec=Math.round(Math.max(0,ms||0)/1000);if(sec<60)return `${sec}s`;const min=Math.floor(sec/60),s=sec%60;if(min<60)return `${min}m ${s}s`;return `${Math.floor(min/60)}h ${min%60}m`}

function makeCheck(level,label,detail){return{level:['pass','warn','fail','info'].includes(level)?level:'info',label,detail}}
async function indexedDbProbe(){if(!root.indexedDB)return makeCheck('fail','IndexedDB read/write','IndexedDB is not available');return new Promise(resolve=>{let settled=false;const timer=setTimeout(()=>finish(makeCheck('fail','IndexedDB read/write','Probe timed out after 4 seconds')),4000);const finish=x=>{if(settled)return;settled=true;clearTimeout(timer);try{root.indexedDB.deleteDatabase(PROBE_DB)}catch(_){ }resolve(x)};try{const req=root.indexedDB.open(PROBE_DB,1);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains('probe'))db.createObjectStore('probe')};req.onerror=()=>finish(makeCheck('fail','IndexedDB read/write',req.error?.message||'Open failed'));req.onsuccess=()=>{const db=req.result;try{const tx=db.transaction('probe','readwrite'),store=tx.objectStore('probe'),token=`probe-${Date.now()}-${Math.random()}`;store.put(token,'value');tx.oncomplete=()=>{try{const rtx=db.transaction('probe','readonly'),get=rtx.objectStore('probe').get('value');get.onsuccess=()=>{const ok=get.result===token;db.close();finish(makeCheck(ok?'pass':'fail','IndexedDB read/write',ok?'Temporary write/read verified':'Readback mismatch'))};get.onerror=()=>{db.close();finish(makeCheck('fail','IndexedDB read/write',get.error?.message||'Read failed'))}}catch(e){db.close();finish(makeCheck('fail','IndexedDB read/write',e.message||String(e)))}};tx.onerror=()=>{db.close();finish(makeCheck('fail','IndexedDB read/write',tx.error?.message||'Write failed'))}}catch(e){try{db.close()}catch(_){ }finish(makeCheck('fail','IndexedDB read/write',e.message||String(e)))}}}catch(e){finish(makeCheck('fail','IndexedDB read/write',e.message||String(e)))}})}
async function storageChecks(){const out=[];if(navigator.storage?.estimate){try{const q=await navigator.storage.estimate(),usage=Number(q.usage)||0,quota=Number(q.quota)||0,ratio=quota?usage/quota:0;out.push(makeCheck(ratio>=.85?'warn':'pass','Browser storage headroom',quota?`${(usage/1048576).toFixed(1)} MB used of ${(quota/1048576).toFixed(1)} MB (${Math.round(ratio*100)}%)`:'Quota estimate unavailable'))}catch(e){out.push(makeCheck('warn','Browser storage headroom',e.message||String(e)))}}else out.push(makeCheck('warn','Browser storage headroom','Storage estimate API not supported'));
if(navigator.storage?.persisted){try{const p=await navigator.storage.persisted();out.push(makeCheck(p?'pass':'warn','Persistent storage',p?'Browser reports persistent storage granted':'Not persistent — OS/browser may evict site data under storage pressure'))}catch(e){out.push(makeCheck('warn','Persistent storage',e.message||String(e)))}}else out.push(makeCheck('warn','Persistent storage','Persistent storage API not supported'));return out}
async function serviceWorkerCheck(){if(!('serviceWorker'in navigator))return makeCheck('warn','Installed-PWA service worker','Service worker API not supported');try{const reg=await navigator.serviceWorker.getRegistration();const controlled=!!navigator.serviceWorker.controller;if(reg&&controlled)return makeCheck('pass','Installed-PWA service worker',reg.waiting?'Controller active • update waiting':'Registration + controller active');if(reg)return makeCheck('warn','Installed-PWA service worker','Registration exists but this page is not currently controlled');return makeCheck('warn','Installed-PWA service worker','No service worker registration found for this scope')}catch(e){return makeCheck('warn','Installed-PWA service worker',e.message||String(e))}}
async function cacheCheck(){if(!root.caches?.keys)return makeCheck('warn','Offline app cache','Cache Storage API unavailable');try{const keys=await caches.keys(),match=keys.find(k=>k.includes('anesvet-v16-21-0'));return makeCheck(match?'pass':'warn','Offline app cache',match?`Active cache: ${match}`:`No V16.21.0 cache found yet • ${keys.length} cache(s) visible`)}catch(e){return makeCheck('warn','Offline app cache',e.message||String(e))}}
function localStorageProbe(){const key='__anesvet_v1617_probe__';try{const token=`${Date.now()}-${Math.random()}`;localStorage.setItem(key,token);const ok=localStorage.getItem(key)===token;localStorage.removeItem(key);return makeCheck(ok?'pass':'fail','localStorage write/read',ok?'Temporary write/read verified':'Readback mismatch')}catch(e){return makeCheck('fail','localStorage write/read',e.message||String(e))}}
function viewportCheck(){try{const overflow=Math.max(0,document.documentElement.scrollWidth-root.innerWidth);return makeCheck(overflow<=1?'pass':'fail','Viewport horizontal integrity',overflow<=1?'No page-level horizontal overflow':`${Math.round(overflow)}px horizontal overflow detected`)}catch(e){return makeCheck('warn','Viewport horizontal integrity',e.message||String(e))}}
function runtimeErrorCheck(){let rows=[];try{rows=adapter.getRuntimeErrors?.()||[]}catch(_){ }return makeCheck(rows.length?'warn':'pass','Recent runtime errors',rows.length?`${rows.length} local runtime error(s) retained for diagnostics`:'No retained runtime errors')}
function currentSaveCheck(){const m=caseMeta();if(!m.active)return makeCheck('info','Current-case save freshness','No active/current case to assess');if(!m.lastSavedAt)return makeCheck('warn','Current-case save freshness','Active case has no lastSavedAt timestamp');const age=Date.now()-m.lastSavedAt;return makeCheck(age>60000?'warn':'pass','Current-case save freshness',`Last verified local save ${formatDuration(age)} ago`)}
async function recoveryCopyCheck(){const m=caseMeta();if(!m.active||m.locked)return makeCheck('info','Active-case recovery copies',m.locked?'Current case is Final Locked':'No mutable active case');try{const r=await adapter.recoveryCopies?.();if(!r)return makeCheck('warn','Active-case recovery copies','Recovery-copy status unavailable');const names=[r.checkpoint?'checkpoint':'',r.mirror?'mirror':''].filter(Boolean);return makeCheck(names.length?'pass':'warn','Active-case recovery copies',names.length?`${names.join(' + ')} available`:'No checkpoint/mirror detected yet')}catch(e){return makeCheck('warn','Active-case recovery copies',e.message||String(e))}}
async function finalArchiveCheck(){const m=caseMeta();if(!m.locked)return makeCheck('info','Final archive assurance','Current case is not Final Locked');try{const r=await adapter.verifyFinalArchive?.();if(!r)return makeCheck('warn','Final archive assurance','Verification adapter unavailable');const ok=r.ok===true||r.status==='VERIFIED';return makeCheck(ok?'pass':'fail','Final archive assurance',ok?'Locked current record and archived copy VERIFIED':r.message||r.detail||r.status||'Verification failed')}catch(e){return makeCheck('fail','Final archive assurance',e.message||String(e))}}
async function runReadiness({announce=false}={}){const checks=[localStorageProbe(),await indexedDbProbe(),...await storageChecks(),await serviceWorkerCheck(),await cacheCheck(),viewportCheck(),runtimeErrorCheck(),currentSaveCheck(),await recoveryCopyCheck(),await finalArchiveCheck()];const levels={pass:0,warn:0,fail:0,info:0};for(const c of checks)levels[c.level]=(levels[c.level]||0)+1;lastReadiness={version:VERSION,epoch:Date.now(),device:deviceContext(),checks,levels,ok:levels.fail===0};jsonWrite(LAST_READINESS_KEY,lastReadiness);logEvent('readiness-run',{pass:levels.pass,warn:levels.warn,fail:levels.fail,info:levels.info});render();if(announce)adapter.toast?.(levels.fail?`Pilot readiness: ${levels.fail} failure(s), ${levels.warn} warning(s)`:`Pilot readiness: no hard failures • ${levels.warn} warning(s)`);return lastReadiness}
function acceptanceSummary(data=acceptance()){const required=SCENARIOS.filter(x=>x.required);const counts={pass:0,fail:0,blocked:0,'not-run':0};for(const s of SCENARIOS){const st=data[s.id]?.status||'not-run';counts[st]=(counts[st]||0)+1}const requiredPass=required.filter(s=>data[s.id]?.status==='pass').length,requiredFail=required.filter(s=>data[s.id]?.status==='fail').length,requiredBlocked=required.filter(s=>data[s.id]?.status==='blocked').length;return{total:SCENARIOS.length,required:required.length,requiredPass,requiredFail,requiredBlocked,complete:requiredPass===required.length,counts}}
function updateScenario(id,patch){if(!SCENARIOS.some(x=>x.id===id))return;const data=acceptance(),old=data[id]||{status:'not-run',note:'',updatedAt:0};data[id]={...old,...patch,updatedAt:Date.now()};saveAcceptance(data);renderAcceptance();renderSummary();logEvent('acceptance-updated',{scenario:id,status:data[id].status})}
function renderAcceptance(){const box=$('productionPilotScenarioList');if(!box)return;const data=acceptance();box.innerHTML=SCENARIOS.map(s=>{const v=data[s.id];return `<article class="pilot-scenario ${esc(v.status)}"><div class="pilot-scenario-head"><div><b>${esc(s.title)}</b><small>${s.required?'Required':'Optional'} • ${esc(s.detail)}</small></div><select data-pilot-status="${esc(s.id)}" aria-label="${esc(s.title)} status"><option value="not-run"${v.status==='not-run'?' selected':''}>Not run</option><option value="pass"${v.status==='pass'?' selected':''}>PASS</option><option value="fail"${v.status==='fail'?' selected':''}>FAIL</option><option value="blocked"${v.status==='blocked'?' selected':''}>BLOCKED</option></select></div><input data-pilot-note="${esc(s.id)}" maxlength="500" value="${esc(v.note)}" placeholder="Device / observation / bug reference"><footer>${v.updatedAt?`Updated ${esc(formatWhen(v.updatedAt))}`:'Not tested on this device yet'}</footer></article>`}).join('');box.querySelectorAll('[data-pilot-status]').forEach(el=>el.addEventListener('change',()=>updateScenario(el.dataset.pilotStatus,{status:el.value})));box.querySelectorAll('[data-pilot-note]').forEach(el=>el.addEventListener('change',()=>updateScenario(el.dataset.pilotNote,{note:el.value.trim()})))}
function renderReadiness(){const box=$('productionPilotAutomatedResults');if(!box)return;const r=lastReadiness||jsonRead(LAST_READINESS_KEY,null);lastReadiness=r;box.innerHTML=r?.checks?.length?r.checks.map(c=>`<div class="pilot-auto-check ${esc(c.level)}"><b>${c.level==='pass'?'✓':c.level==='fail'?'✕':c.level==='warn'?'⚠':'•'} ${esc(c.label)}</b><span>${esc(c.detail)}</span></div>`).join(''):'<div class="empty-state compact">Run device readiness on the actual phone / tablet / PC used in the OR.</div>'}
function renderLifecycle(){const box=$('productionPilotLifecycleLog');if(!box)return;const rows=eventLog().slice(-20).reverse();box.innerHTML=rows.length?rows.map(x=>`<div class="pilot-life-row"><time>${esc(new Date(x.epoch).toLocaleTimeString())}</time><b>${esc(x.type)}</b><span>${esc(x.case?.phase||'')} ${x.detail?.hiddenMs!=null?`• hidden ${esc(formatDuration(x.detail.hiddenMs))}`:''}</span></div>`).join(''):'<div class="empty-state compact">No lifecycle events recorded yet.</div>';const badge=$('productionPilotLifecycleBadge');if(badge){badge.textContent=`${eventLog().length} EVENTS`;badge.className='status-pill neutral'}}
function renderSummary(){const data=acceptance(),s=acceptanceSummary(data),badge=$('productionPilotBadge');if(badge){if(s.requiredFail){badge.textContent=`ISSUES ${s.requiredFail}`;badge.className='status-pill warn'}else if(s.complete){badge.textContent=`PILOT ${s.requiredPass}/${s.required} COMPLETE`;badge.className='status-pill good'}else{badge.textContent=`PILOT ${s.requiredPass}/${s.required}`;badge.className='status-pill neutral'}}const meta=$('productionPilotMeta');const r=lastReadiness||jsonRead(LAST_READINESS_KEY,null);if(meta){const auto=r?`${r.levels?.fail||0} fail • ${r.levels?.warn||0} warn • ${r.levels?.pass||0} pass`:'not run';meta.textContent=`V${VERSION} • Required real-device scenarios ${s.requiredPass}/${s.required} passed • Automated readiness ${auto}. Pilot completion is device-specific and does not replace clinical validation.`}}
function render(){renderAcceptance();renderReadiness();renderLifecycle();renderSummary()}
function snapshot(){return{format:'ANESVET_PRODUCTION_PILOT_V1',version:VERSION,generatedAt:new Date().toISOString(),device:deviceContext(),acceptance:acceptance(),acceptanceSummary:acceptanceSummary(),readiness:lastReadiness||jsonRead(LAST_READINESS_KEY,null),lifecycle:eventLog()}}
function downloadJson(name,payload){const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function exportReport(){const d=new Date(),stamp=d.toISOString().slice(0,10);downloadJson(`ANESVET_V${VERSION}_Production_Pilot_${stamp}.json`,snapshot());adapter.toast?.('Production Pilot report exported')}
function reset(){if(root.confirm&&!root.confirm('Reset Production Pilot checklist and lifecycle log on this device?\n\nClinical case data will not be changed.'))return false;try{localStorage.removeItem(ACCEPTANCE_KEY);localStorage.removeItem(LIFECYCLE_KEY);localStorage.removeItem(LAST_READINESS_KEY)}catch(_){ }lastReadiness=null;logEvent('pilot-reset',{});render();adapter.toast?.('Production Pilot results reset');return true}
function bindUi(){ $('productionPilotRunBtn')?.addEventListener('click',()=>runReadiness({announce:true}));$('productionPilotExportBtn')?.addEventListener('click',exportReport);$('productionPilotResetBtn')?.addEventListener('click',reset);$('productionPilotRefreshBtn')?.addEventListener('click',render)}
function bindLifecycle(){document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'){lastHiddenAt=Date.now();logEvent('visibility-hidden')}else{const hiddenMs=lastHiddenAt?Date.now()-lastHiddenAt:0;logEvent('visibility-visible',{hiddenMs});lastHiddenAt=0}});root.addEventListener('pagehide',e=>logEvent('pagehide',{persisted:!!e.persisted}));root.addEventListener('pageshow',e=>logEvent('pageshow',{persisted:!!e.persisted}));root.addEventListener('online',()=>logEvent('online'));root.addEventListener('offline',()=>logEvent('offline'));document.addEventListener('freeze',()=>logEvent('freeze'));document.addEventListener('resume',()=>logEvent('resume'));root.addEventListener('orientationchange',()=>setTimeout(()=>logEvent('orientationchange',{orientation:root.screen?.orientation?.type||String(root.orientation||'')}),160));document.addEventListener('anesvet:fast-vitals-saved',e=>logEvent('fast-vitals-saved',e.detail||{}));document.addEventListener('anesvet:drug-administration-changed',()=>logEvent('drug-administration-changed'))}
function init(options={}){adapter={...adapter,...options};if(started){render();return api}started=true;bindUi();bindLifecycle();lastReadiness=jsonRead(LAST_READINESS_KEY,null);logEvent('pilot-init',{version:VERSION});render();return api}
const api=Object.freeze({version:VERSION,scenarios:SCENARIOS,init,runReadiness,render,snapshot,exportReport,reset,logEvent,acceptanceSummary});
root.ANESVET_PRODUCTION_PILOT=api;
if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:this);
