'use strict';
const assert=require('assert');
const sync=require('./sync-foundation.js');
function mem(){const m=new Map();return{getItem:k=>m.has(String(k))?m.get(String(k)):null,setItem:(k,v)=>m.set(String(k),String(v)),removeItem:k=>m.delete(String(k)),clear:()=>m.clear(),_m:m}}
(async()=>{
  const tests=[];async function test(name,fn){try{await fn();tests.push({name,pass:true})}catch(e){tests.push({name,pass:false,error:e.stack||e.message});throw e}}
  await test('disabled by default',async()=>{const e=sync.createEngine({storage:mem()});assert.equal(e.snapshot().enabled,false);assert.equal(e.snapshot().counts.total,0)});
  await test('envelope carries required sync identifiers',async()=>{const e=sync.createEngine({storage:mem(),uuid:()=> 'op-1',now:()=>100});e.setEnabled(true);e.init({getContext:()=>({deviceId:'dev-1',sessionId:'sess-1',actorId:'staff-1'})});const r=e.enqueueMutation({caseId:'case-1',recordId:'r-1',recordType:'vital',payload:{hr:100}});const o=r.operation;for(const k of ['caseId','recordId','revision','operationId','deviceId','sessionId','actorId','createdAt','modifiedAt','baseRevision'])assert.ok(Object.prototype.hasOwnProperty.call(o,k),k);assert.equal(o.baseRevision,0);assert.equal(o.revision,1)});
  await test('queue survives engine recreation',async()=>{const s=mem();let e=sync.createEngine({storage:s,online:()=>false});e.setEnabled(true);e.enqueueMutation({caseId:'case-1',recordId:'v1',recordType:'vital',payload:{hr:90}});e=sync.createEngine({storage:s,online:()=>false});assert.equal(e.snapshot().counts.pending,1)});
  await test('idempotent repeated delivery returns same canonical revision',async()=>{const s=mem(),adapter=sync.createMockCanonicalAdapter({storage:s,now:()=>200});const op={caseId:'c',recordId:'v',recordType:'vital',operation:'upsert',revision:1,operationId:'same-op',deviceId:'d',sessionId:'s',actorId:'a',createdAt:1,modifiedAt:1,baseRevision:0,payload:{hr:80}};const a=await adapter.pushOperations([op]),b=await adapter.pushOperations([op]);assert.equal(a[0].canonicalRevision,1);assert.equal(b[0].canonicalRevision,1);assert.equal((await adapter.getCaseRevision('c')),1)});
  await test('out-of-order stale append-only vital merges by stable recordId',async()=>{const s=mem(),adapter=sync.createMockCanonicalAdapter({storage:s});await adapter.pushOperations([{caseId:'c',recordId:'v1',recordType:'vital',operation:'upsert',operationId:'a',baseRevision:0,payload:{hr:80}}]);const r=await adapter.pushOperations([{caseId:'c',recordId:'v2',recordType:'vital',operation:'upsert',operationId:'b',baseRevision:0,payload:{hr:90}}]);assert.equal(r[0].status,'acknowledged');assert.equal(r[0].mergedStaleAppend,true);assert.equal(await adapter.getCaseRevision('c'),2)});
  await test('stale edit to same vital conflicts and preserves both evidence',async()=>{const s=mem(),adapter=sync.createMockCanonicalAdapter({storage:s});await adapter.pushOperations([{caseId:'c',recordId:'v1',recordType:'vital',operation:'upsert',operationId:'a',baseRevision:0,payload:{hr:80}}]);const r=await adapter.pushOperations([{caseId:'c',recordId:'v1',recordType:'vital',operation:'upsert',operationId:'b',baseRevision:0,payload:{hr:120}}]);assert.equal(r[0].status,'conflict');assert.equal(r[0].conflict.localPayload.hr,120);assert.equal(r[0].conflict.remoteRecord.payload.hr,80)});
  await test('medication stale edit never auto-collapses',async()=>{const s=mem(),adapter=sync.createMockCanonicalAdapter({storage:s});await adapter.pushOperations([{caseId:'c',recordId:'m1',recordType:'medication',operation:'upsert',operationId:'a',baseRevision:0,payload:{drug:'propofol',actual:1}}]);const r=await adapter.pushOperations([{caseId:'c',recordId:'m1',recordType:'medication',operation:'upsert',operationId:'b',baseRevision:0,payload:{drug:'propofol',actual:2}}]);assert.equal(r[0].status,'conflict');assert.equal(r[0].conflict.reason,'MEDICATION_CONFLICT')});
  await test('distinct stale medication record is preserved as append',async()=>{const s=mem(),adapter=sync.createMockCanonicalAdapter({storage:s});await adapter.pushOperations([{caseId:'c',recordId:'m1',recordType:'medication',operation:'upsert',operationId:'a',baseRevision:0,payload:{drug:'propofol'}}]);const r=await adapter.pushOperations([{caseId:'c',recordId:'m2',recordType:'medication',operation:'upsert',operationId:'b',baseRevision:0,payload:{drug:'diazepam'}}]);assert.equal(r[0].status,'acknowledged');assert.equal(r[0].mergedStaleAppend,true)});
  await test('Final Lock stale revision is strict conflict',async()=>{const s=mem(),adapter=sync.createMockCanonicalAdapter({storage:s});await adapter.pushOperations([{caseId:'c',recordId:'x',recordType:'event',operation:'upsert',operationId:'a',baseRevision:0,payload:{name:'x'}}]);const r=await adapter.pushOperations([{caseId:'c',recordId:'c:final-lock',recordType:'final-lock',operation:'upsert',operationId:'b',baseRevision:0,payload:{locked:true}}]);assert.equal(r[0].status,'conflict');assert.equal(r[0].conflict.reason,'STRICT_STALE_REVISION')});
  await test('patient concurrent change requires review',async()=>{const s=mem(),adapter=sync.createMockCanonicalAdapter({storage:s});await adapter.pushOperations([{caseId:'c',recordId:'p',recordType:'patient',operation:'upsert',operationId:'a',baseRevision:0,payload:{name:'A'}}]);const r=await adapter.pushOperations([{caseId:'c',recordId:'p',recordType:'patient',operation:'upsert',operationId:'b',baseRevision:0,payload:{name:'B'}}]);assert.equal(r[0].status,'conflict');assert.equal(r[0].conflict.reason,'REVIEW_REQUIRED')});
  await test('engine records conflict and blocks dependent same-case operations',async()=>{const shared=mem(),adapter=sync.createMockCanonicalAdapter({storage:shared});await adapter.pushOperations([{caseId:'c',recordId:'remote',recordType:'event',operation:'upsert',operationId:'remote-op',baseRevision:0,payload:{}}]);const local=mem(),e=sync.createEngine({storage:local,online:()=>true});e.setEnabled(true);e.setAutoSync(false);e.setAdapter(adapter);e.enqueueMutation({caseId:'c',recordId:'c',recordType:'case-snapshot',payload:{v:1}});e.enqueueMutation({caseId:'c',recordId:'c2',recordType:'case-snapshot',payload:{v:2}});await e.syncNow();const q=e.inspect().queue;assert.equal(q[0].status,'conflict');assert.equal(q[1].status,'pending');assert.equal(e.snapshot().conflictsOpen,1)});
  await test('offline leaves pending queue intact',async()=>{const s=mem(),e=sync.createEngine({storage:s,online:()=>false});e.setEnabled(true);e.setAutoSync(false);e.enqueueMutation({caseId:'c',recordId:'v',recordType:'vital',payload:{}});await e.syncNow();assert.equal(e.snapshot().counts.pending,1);assert.equal(e.snapshot().lastResult,'offline')});
  await test('ACK loss retry remains idempotent at canonical adapter',async()=>{const shared=mem(),canonical=sync.createMockCanonicalAdapter({storage:shared});let first=true;const flaky={...canonical,pushOperations:async ops=>{const r=await canonical.pushOperations(ops);if(first){first=false;throw new Error('simulated ACK loss')}return r}};const local=mem(),e=sync.createEngine({storage:local,online:()=>true});e.setEnabled(true);e.setAutoSync(false);e.setAdapter(flaky);e.enqueueMutation({caseId:'c',recordId:'v',recordType:'vital',payload:{hr:100}});await e.syncNow();assert.equal(e.snapshot().counts.failed,1);e.retryFailed();await e.syncNow();assert.equal(e.snapshot().counts.acknowledged,1);assert.equal(await canonical.getCaseRevision('c'),1)});
  await test('enqueue during an active sync is not lost',async()=>{const shared=mem(),canonical=sync.createMockCanonicalAdapter({storage:shared});let release;const gate=new Promise(r=>release=r);let first=true;const delayed={...canonical,pushOperations:async ops=>{if(first){first=false;await gate}return canonical.pushOperations(ops)}};const local=mem(),e=sync.createEngine({storage:local,online:()=>true});e.setEnabled(true);e.setAutoSync(false);e.setAdapter(delayed);e.enqueueMutation({caseId:'c',recordId:'v1',recordType:'vital',payload:{hr:80}});const running=e.syncNow();await Promise.resolve();e.enqueueMutation({caseId:'c',recordId:'v2',recordType:'vital',payload:{hr:90}});release();await running;assert.equal(e.inspect().queue.length,2);assert.ok(e.inspect().queue.some(x=>x.recordId==='v2'));await e.syncNow();assert.equal(e.snapshot().counts.acknowledged,2)});
  await test('queue corruption is preserved as evidence instead of touching clinical data',async()=>{const s=mem();s.setItem(sync.keys.queue,'{broken-json');const e=sync.createEngine({storage:s});const snap=e.snapshot();assert.equal(snap.counts.total,0);assert.ok(s.getItem(sync.keys.queueCorrupt));assert.equal(e.inspect().status.lastResult,'queue-corrupt')});
  await test('case snapshot save is not queued when foundation disabled',async()=>{const e=sync.createEngine({storage:mem()});const r=e.captureCaseSave({caseId:'c',lastSavedAt:1});assert.equal(r.queued,false);assert.equal(r.reason,'disabled')});
  await test('locked case snapshot is typed final-lock',async()=>{const e=sync.createEngine({storage:mem(),online:()=>false});e.setEnabled(true);const r=e.captureCaseSave({caseId:'c',caseLocked:true,lastSavedAt:1},{reason:'final-lock'});assert.equal(r.operation.recordType,'final-lock')});
  const result={version:'17.1.0',suite:'sync-foundation',passed:tests.filter(x=>x.pass).length,total:tests.length,tests};process.stdout.write(JSON.stringify(result,null,2));
})().catch(e=>{process.stderr.write(`\n${e.stack||e.message}\n`);process.exit(1)});
