'use strict';
const assert=require('assert');
const sync=require('./sync-foundation.js');
const transport=require('./sync-transport.js');
function mem(){const m=new Map();return{getItem:k=>m.has(String(k))?m.get(String(k)):null,setItem:(k,v)=>m.set(String(k),String(v)),removeItem:k=>m.delete(String(k)),clear:()=>m.clear(),_m:m}}
function response(status,payload){return{ok:status>=200&&status<300,status,async text(){return payload==null?'':JSON.stringify(payload)}}}
(async()=>{
  const tests=[];async function test(name,fn){try{await fn();tests.push({name,pass:true})}catch(e){tests.push({name,pass:false,error:e.stack||e.message});throw e}}
  await test('V17.1 durable queue keys are retained for upgrade compatibility',async()=>{assert.equal(sync.keys.queue,'anesvet_v17_1_sync_queue_v1');assert.equal(sync.keys.conflicts,'anesvet_v17_1_sync_conflicts_v1')});
  await test('unattempted case snapshots coalesce instead of growing offline queue',async()=>{const e=sync.createEngine({storage:mem(),online:()=>false,now:(()=>{let n=1;return()=>n++})()});e.setEnabled(true);e.setAutoSync(false);const a=e.captureCaseSave({caseId:'c',lastSavedAt:1,x:1}),b=e.captureCaseSave({caseId:'c',lastSavedAt:2,x:2});assert.equal(a.queued,true);assert.equal(b.coalesced,true);assert.equal(e.snapshot().counts.pending,1);const op=e.inspect().queue[0];assert.equal(op.payload.case.x,2);assert.equal(op.coalescedCount,1)});
  await test('medication operations never coalesce',async()=>{const e=sync.createEngine({storage:mem(),online:()=>false});e.setEnabled(true);e.setAutoSync(false);e.enqueueMutation({caseId:'c',recordId:'m',recordType:'medication',payload:{actual:1}});e.enqueueMutation({caseId:'c',recordId:'m',recordType:'medication',payload:{actual:2}});assert.equal(e.snapshot().counts.pending,2)});
  await test('open conflict holds later same-case operations across future sync passes',async()=>{const shared=mem(),adapter=sync.createMockCanonicalAdapter({storage:shared});await adapter.pushOperations([{caseId:'c',recordId:'remote',recordType:'event',operation:'upsert',operationId:'remote',baseRevision:0,payload:{}}]);const e=sync.createEngine({storage:mem(),online:()=>true});e.setEnabled(true);e.setAutoSync(false);e.setAdapter(adapter);e.enqueueMutation({caseId:'c',recordId:'c',recordType:'case-snapshot',payload:{v:1}});await e.syncNow();assert.equal(e.snapshot().conflictsOpen,1);e.enqueueMutation({caseId:'c',recordId:'v2',recordType:'vital',payload:{hr:90}});await e.syncNow();const v=e.inspect().queue.find(x=>x.recordId==='v2');assert.equal(v.status,'pending');assert.equal(v.attempts,0);assert.equal(await adapter.getCaseRevision('c'),1);assert.equal(e.snapshot().heldCaseCount,1)});
  await test('reviewing conflict evidence does not resolve or unblock the case',async()=>{const shared=mem(),adapter=sync.createMockCanonicalAdapter({storage:shared});await adapter.pushOperations([{caseId:'c',recordId:'remote',recordType:'event',operation:'upsert',operationId:'remote',baseRevision:0,payload:{}}]);const e=sync.createEngine({storage:mem(),online:()=>true,now:(()=>{let n=100;return()=>n++})()});e.setEnabled(true);e.setAutoSync(false);e.setAdapter(adapter);e.init({getContext:()=>({actorId:'vet-1',sessionId:'s',deviceId:'d'})});e.enqueueMutation({caseId:'c',recordId:'c',recordType:'case-snapshot',payload:{v:1}});await e.syncNow();const id=e.inspect().conflicts[0].id;const r=e.reviewConflict(id,{note:'Compared both versions'});assert.equal(r.reviewStatus,'reviewed');assert.equal(r.status,'open');assert.equal(r.reviewDoesNotResolve,true);assert.equal(r.reviewedBy,'vet-1');assert.equal(e.snapshot().heldCaseCount,1)});
  await test('conflict evidence export contains both conflict and queued operation',async()=>{const shared=mem(),adapter=sync.createMockCanonicalAdapter({storage:shared});await adapter.pushOperations([{caseId:'c',recordId:'m',recordType:'medication',operation:'upsert',operationId:'remote',baseRevision:0,payload:{dose:1}}]);const e=sync.createEngine({storage:mem(),online:()=>true});e.setEnabled(true);e.setAutoSync(false);e.setAdapter(adapter);e.enqueueMutation({caseId:'c',recordId:'m',recordType:'medication',payload:{dose:2}});await e.syncNow();const id=e.inspect().conflicts[0].id,ev=e.exportConflictEvidence(id);assert.equal(ev.format,'ANESVET_SYNC_CONFLICT_EVIDENCE');assert.equal(ev.conflict.localPayload.dose,2);assert.equal(ev.conflict.remoteRecord.payload.dose,1);assert.equal(ev.operation.recordId,'m');assert.match(ev.safety,/does not resolve/i)});
  await test('remote pull is preview-only and does not mutate queue or local revision ledger',async()=>{const shared=mem(),adapter=sync.createMockCanonicalAdapter({storage:shared});await adapter.pushOperations([{caseId:'c',recordId:'v1',recordType:'vital',operation:'upsert',operationId:'r1',baseRevision:0,payload:{hr:80}}]);const e=sync.createEngine({storage:mem(),online:()=>true});e.setAdapter(adapter);const before=e.inspect();const p=await e.previewRemoteChanges('c');const after=e.inspect();assert.equal(p.changeCount,1);assert.equal(p.applied,false);assert.equal(after.queue.length,before.queue.length);assert.deepEqual(after.revisions,before.revisions);assert.equal(after.pullPreviews.length,1)});
  await test('mock adapter capability probe identifies canonical protocol',async()=>{const e=sync.createEngine({storage:mem()});const cap=await e.probeAdapter();assert.equal(cap.protocol,'anesvet-sync');assert.equal(cap.protocolVersion,1);assert.equal(cap.canonical,true)});
  await test('public plain HTTP endpoint is rejected',async()=>{assert.throws(()=>transport.createHttpCanonicalAdapter({baseUrl:'http://example.com',fetchImpl:async()=>response(200,{})}),/Plain HTTP/)});
  await test('private LAN HTTP and public HTTPS endpoints are accepted',async()=>{const f=async()=>response(200,{protocol:'anesvet-sync',protocolVersion:1,canonical:true});const a=transport.createHttpCanonicalAdapter({baseUrl:'http://192.168.1.20:8080/',fetchImpl:f}),b=transport.createHttpCanonicalAdapter({baseUrl:'https://sync.example.com/',fetchImpl:f});assert.equal(a.baseUrl,'http://192.168.1.20:8080');assert.equal(b.baseUrl,'https://sync.example.com')});
  await test('HTTP capability handshake validates ANESVET protocol',async()=>{let url='';const f=async(u)=>{url=u;return response(200,{protocol:'anesvet-sync',protocolVersion:1,canonical:true,serverTime:123})};const a=transport.createHttpCanonicalAdapter({baseUrl:'https://sync.example.com',fetchImpl:f});const cap=await a.probe();assert.equal(cap.canonical,true);assert.match(url,/\/api\/anesvet-sync\/v1\/capabilities$/)});
  await test('invalid capability handshake is rejected',async()=>{const a=transport.createHttpCanonicalAdapter({baseUrl:'https://sync.example.com',fetchImpl:async()=>response(200,{protocol:'other',protocolVersion:1,canonical:true})});await assert.rejects(()=>a.probe(),/Unsupported sync protocol/)});
  await test('HTTP push sends operation IDs and requires results array',async()=>{let seen=null;const f=async(u,opt)=>{seen={u,opt};return response(200,{results:[{ok:true,status:'acknowledged',operationId:'op1',canonicalRevision:1}]})};const a=transport.createHttpCanonicalAdapter({baseUrl:'https://sync.example.com',fetchImpl:f});const r=await a.pushOperations([{operationId:'op1'}]);assert.equal(r[0].canonicalRevision,1);assert.equal(seen.opt.headers['X-ANESVET-Operation-Ids'],'op1');assert.equal(JSON.parse(seen.opt.body).protocolVersion,1)});
  await test('HTTP pull validates change-list response',async()=>{const a=transport.createHttpCanonicalAdapter({baseUrl:'https://sync.example.com',fetchImpl:async()=>response(200,{caseId:'c',revision:2,changes:[{recordId:'v'}]})});const r=await a.pullChanges({caseId:'c',sinceRevision:1});assert.equal(r.revision,2);assert.equal(r.changes.length,1)});
  await test('fault adapter can inject pre-commit transport failure',async()=>{const base=sync.createMockCanonicalAdapter({storage:mem()}),f=transport.createFaultInjectionAdapter(base);f.controls.failNext(1);await assert.rejects(()=>f.pushOperations([{caseId:'c',recordId:'v',recordType:'vital',operationId:'x',baseRevision:0,payload:{}}]),/Injected transport failure/);assert.equal(await base.getCaseRevision('c'),0)});
  await test('fault adapter can inject ACK loss after canonical commit',async()=>{const base=sync.createMockCanonicalAdapter({storage:mem()}),f=transport.createFaultInjectionAdapter(base);f.controls.dropAckNext(1);await assert.rejects(()=>f.pushOperations([{caseId:'c',recordId:'v',recordType:'vital',operationId:'x',baseRevision:0,payload:{}}]),/ACK loss/);assert.equal(await base.getCaseRevision('c'),1);const r=await f.pushOperations([{caseId:'c',recordId:'v',recordType:'vital',operationId:'x',baseRevision:0,payload:{}}]);assert.equal(r[0].canonicalRevision,1)});
  await test('invalid adapter interface is rejected',async()=>{const e=sync.createEngine({storage:mem()});assert.throws(()=>e.setAdapter({pushOperations(){}}),/Invalid canonical adapter/)});
  await test('acknowledged queue compaction never removes pending/conflict evidence',async()=>{const e=sync.createEngine({storage:mem(),online:()=>true});e.setEnabled(true);e.setAutoSync(false);e.enqueueMutation({caseId:'a',recordId:'v1',recordType:'vital',payload:{}});await e.syncNow();e.enqueueMutation({caseId:'b',recordId:'v2',recordType:'vital',payload:{}});await e.syncNow();e.enqueueMutation({caseId:'c',recordId:'v3',recordType:'vital',payload:{}});const n=e.compactAcknowledged({keep:1});assert.equal(n,1);assert.equal(e.inspect().queue.filter(x=>x.status==='acknowledged').length,1);assert.equal(e.inspect().queue.filter(x=>x.status==='pending').length,1)});
  await test('final-lock operations are never coalesced',async()=>{const e=sync.createEngine({storage:mem(),online:()=>false});e.setEnabled(true);e.setAutoSync(false);e.captureCaseSave({caseId:'c',caseLocked:true,lastSavedAt:1});e.captureCaseSave({caseId:'c',caseLocked:true,lastSavedAt:2});assert.equal(e.inspect().queue.filter(x=>x.recordType==='final-lock').length,2)});
  const result={version:'17.2.0',suite:'sync-safety-backend-readiness',passed:tests.filter(x=>x.pass).length,total:tests.length,tests};process.stdout.write(JSON.stringify(result,null,2));
})().catch(e=>{process.stderr.write(`\n${e.stack||e.message}\n`);process.exit(1)});
