'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');
const {chromium}=require('playwright');
const ROOT=__dirname,OUT=path.resolve(ROOT,'../../output/startup-v17-5-3');fs.mkdirSync(OUT,{recursive:true});
const tests=[],errors=[];let delayApp=false;
const server=http.createServer((req,res)=>{let f=path.join(ROOT,new URL(req.url,'http://localhost').pathname);if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');if(!fs.existsSync(f)){res.writeHead(404);res.end();return}res.setHeader('Content-Type',{'.js':'text/javascript','.css':'text/css','.html':'text/html','.svg':'image/svg+xml','.webmanifest':'application/manifest+json','.png':'image/png'}[path.extname(f)]||'application/octet-stream');const send=()=>res.end(fs.readFileSync(f));if(delayApp&&path.basename(f)==='app.js')setTimeout(send,1600);else send();});
async function test(name,fn){try{await fn();tests.push({name,pass:true});console.log('PASS',name)}catch(e){tests.push({name,pass:false,error:e.message});console.log('FAIL',name,e.message)}}
const ready=p=>p.waitForFunction(()=>window.ANESVET_BOOT_DIAGNOSTIC?.snapshot().ready&&!document.body.classList.contains('av-booting'));
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({executablePath:process.env.ANESVET_CHROMIUM_EXECUTABLE||'/tmp/anesvet-browser/chrome-headless-shell-linux64/chrome-headless-shell',args:['--no-sandbox','--disable-gpu','--disable-software-rasterizer','--disable-dev-shm-usage']});
try{
 const ctx=await browser.newContext({viewport:{width:393,height:852},isMobile:true,hasTouch:true}),p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));delayApp=true;
 await test('Figma splash is visible while runtime loads; every local asset decodes and fits',async()=>{await p.goto(origin,{waitUntil:'commit'});await p.locator('.av-boot-logo').waitFor();await p.waitForTimeout(400);assert(await p.locator('#avBoot').isVisible());assert.equal(await p.locator('#avBootTitle').innerText(),'ANESVET');const assets=await p.locator('#avBoot img').evaluateAll(es=>es.map(e=>({src:e.getAttribute('src'),okay:e.complete&&e.naturalWidth>0,w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height})));assert.equal(assets.length,6);assert(assets.every(x=>x.okay));assert.equal(assets.find(x=>x.src.endsWith('logo.png')).w,220);assert.equal(assets.find(x=>x.src.endsWith('ring.svg')).w,176);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:path.join(OUT,'splash-393.png')});});
 delayApp=false;await ready(p);
 await test('Empty Figma home has a full-width archive action and no hard-coded patient',async()=>{assert.equal(await p.evaluate(()=>document.querySelector('.tabpage.active')?.id),'start');assert(await p.locator('#avHomeEmpty').isVisible());assert(!await p.locator('#avHomeCase').isVisible());assert.equal(await p.locator('#weight').inputValue(),'');await p.screenshot({path:path.join(OUT,'home-empty-393.png')});});
 const seed=await p.evaluate(()=>{const s=JSON.parse(JSON.stringify(AnesvetApp.getState()));Object.assign(s,{patientName:'QA Milo',species:'dog',weight:'9.6',asa:'II',patientSaved:true,procedure:'Dental',patientProcedure:'Dental',visitId:'QA-26001',anesthetist:'QA Vet',surgeon:'QA Vet',casePhase:'intraop',caseStartedAt:Date.now()-60000,timer:{running:false,elapsedMs:60000,startedEpoch:null},caseIdentitySnapshot:{patientName:'QA Milo',species:'dog',weight:9.6,capturedAt:Date.now()},protocolSnapshot:JSON.parse(JSON.stringify(AnesvetApp.settings()))});s.events=[{id:'qa-event',name:'Induction',category:'Workflow',epoch:s.caseStartedAt,elapsedMs:0,clock:'10:00:00'}];s.records=[{id:'qa-record',epoch:s.caseStartedAt,elapsedMs:0,clock:'10:00:00',hr:100,rr:16,map:75,spo2:98,etco2:45,temp:100.04,note:''}];return s;});await ctx.close();
 const real=await browser.newContext({viewport:{width:393,height:852},isMobile:true,hasTouch:true});await real.addInitScript(s=>{if(!localStorage.getItem('qa-seeded')){localStorage.setItem('anesvet_v14_3_current',JSON.stringify(s));localStorage.setItem('qa-seeded','1');}},seed);const q=await real.newPage();q.on('pageerror',e=>errors.push(e.message));
 await test('Cold launch from old installed start URL shows actual current case without changing records',async()=>{await q.goto(origin+'/?v=17.5.1');await ready(q);assert.equal(await q.evaluate(()=>document.querySelector('.tabpage.active')?.id),'start');assert.equal(await q.locator('#avHomePatient').innerText(),'QA Milo');assert.equal(await q.evaluate(()=>AnesvetApp.getState().records[0].id),'qa-record');assert.equal(await q.evaluate(()=>AnesvetApp.getState().casePhase),'intraop');await q.screenshot({path:path.join(OUT,'home-case-393.png')});await q.setViewportSize({width:360,height:780});await q.screenshot({path:path.join(OUT,'home-case-360.png')});});
 await test('Continue and reload resume the existing native OR instead of forcing home',async()=>{await q.locator('#avHomePrimary').click();await q.waitForFunction(()=>document.querySelector('.tabpage.active')?.id==='orlive');await q.reload();await ready(q);assert.equal(await q.evaluate(()=>document.querySelector('.tabpage.active')?.id),'orlive');assert.equal(await q.evaluate(()=>AnesvetApp.getState().records[0].id),'qa-record');});
 await test('Successful save flash settles without observer recursion or new records',async()=>{await q.evaluate(()=>{window.qaSaveMutations=0;new MutationObserver(ms=>qaSaveMutations+=ms.length).observe(document.getElementById('saveState'),{attributes:true,childList:true,subtree:true});AnesvetApp.save();});await q.waitForTimeout(1400);const first=await q.evaluate(()=>qaSaveMutations);await q.waitForTimeout(800);assert.equal(await q.evaluate(()=>qaSaveMutations),first);assert(first<15,'Unexpected repeated save-state mutations: '+first);assert.equal(await q.evaluate(()=>AnesvetApp.getState().records.length),1);});
 await test('Fast input still updates critical thresholds immediately; historical record stays unchanged',async()=>{await q.locator('#orHr').fill('101');await q.locator('#orMap').fill('55');assert(await q.locator('.or-vital-card[data-vital="map"].danger #orMapHint').isVisible());assert.equal(await q.evaluate(()=>AnesvetApp.getState().records[0].map),75);await q.evaluate(()=>AnesvetApp.setTab('record'));assert((await q.locator('#recordPreview').textContent()).includes('101'),JSON.stringify(await q.evaluate(()=>({page:document.querySelector('.tabpage.active')?.id,hr:document.getElementById('hr').value,orHr:document.getElementById('orHr').value,preview:document.getElementById('recordPreview').textContent}))));await q.evaluate(()=>AnesvetApp.setTab('dashboard'));assert((await q.locator('#interpretationCards').innerText()).includes('Hypotension'));await q.evaluate(()=>AnesvetApp.resumeActiveCase());await q.locator('#orMap').fill('75');});
 await test('Offline cold launch provides Figma home and existing case from precached assets',async()=>{await q.evaluate(()=>navigator.serviceWorker.ready);await q.waitForFunction(()=>!!navigator.serviceWorker.controller);await q.close();await real.setOffline(true);const offline=await real.newPage();offline.on('pageerror',e=>errors.push(e.message));await offline.goto(origin+'/?v=17.5.1');await ready(offline);assert.equal(await offline.evaluate(()=>document.querySelector('.tabpage.active')?.id),'start');assert.equal(await offline.locator('#avHomePatient').innerText(),'QA Milo');assert(await offline.locator('#start img').evaluate(e=>e.complete&&e.naturalWidth>0));assert.equal(await offline.evaluate(()=>AnesvetApp.getState().records[0].id),'qa-record');await offline.close();await real.setOffline(false);});await real.close();
 const broken=await browser.newContext({viewport:{width:360,height:780},isMobile:true});await broken.addInitScript(s=>localStorage.setItem('anesvet_v14_3_current',JSON.stringify(s)),seed);await broken.route('**/mobile-design.js?*',r=>r.abort());const fail=await broken.newPage();
 await test('Failed UI script shows retry and preserves clinical bytes instead of exposing old screen',async()=>{await fail.goto(origin);await fail.waitForFunction(()=>document.body.classList.contains('av-boot-error'));assert(await fail.locator('#avBootRetry').isVisible());assert(await fail.locator('#avBootReview').isDisabled());assert.equal(await fail.evaluate(()=>JSON.parse(localStorage.getItem('anesvet_v14_3_current')).records[0].id),'qa-record');assert(!await fail.locator('#patient').isVisible());await fail.screenshot({path:path.join(OUT,'startup-ui-error.png')});});await broken.close();
 await test('No uncaught runtime errors in startup/input/offline flows',async()=>assert.deepEqual(errors,[]));
}finally{await browser.close();await new Promise(r=>server.close(r));}
const report={version:'17.5.3',passed:tests.filter(x=>x.pass).length,total:tests.length,tests,errors,limits:['Chromium mobile emulation; not a physical installed iOS/Android test.']};fs.writeFileSync(path.join(ROOT,'QA_V17_5_3_STARTUP_RESULTS.json'),JSON.stringify(report,null,2));if(report.passed!==report.total)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1;server.close()});
