'use strict';
// Controlled viewport models exercise our code; they are not native IME tests.
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');
const {chromium}=require('playwright');
const ROOT=__dirname,OUT=path.resolve(ROOT,'../../output/editing-v17-5-3');fs.mkdirSync(OUT,{recursive:true});
const tests=[],errors=[];let diagnosticPage=null;
const server=http.createServer((req,res)=>{let f=path.resolve(ROOT,'.'+new URL(req.url,'http://localhost').pathname);if(!f.startsWith(ROOT+path.sep)&&f!==ROOT){res.writeHead(403);res.end();return}if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');if(!fs.existsSync(f)){res.writeHead(404);res.end();return}res.setHeader('Content-Type',{'.js':'text/javascript','.css':'text/css','.html':'text/html','.svg':'image/svg+xml','.webmanifest':'application/manifest+json','.png':'image/png','.ttf':'font/ttf','.woff2':'font/woff2'}[path.extname(f)]||'application/octet-stream');res.end(fs.readFileSync(f));});
async function test(name,fn){try{await fn();tests.push({name,pass:true});console.log('PASS',name)}catch(e){tests.push({name,pass:false,error:e.message});console.log('FAIL',name,e.message.split('Call log:')[0]);if(diagnosticPage)console.log('DIAG',JSON.stringify(await diagnosticPage.evaluate(()=>['avContextWorkflow','avMedicationDetails','orFastEntryRail'].map(id=>{const e=document.getElementById(id),r=e.getBoundingClientRect(),c=getComputedStyle(e);return {id,box:{x:r.x,y:r.y,w:r.width,h:r.height},pointer:c.pointerEvents,position:c.position,transform:c.transform,overflow:c.overflow,clip:c.clipPath,hit:document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)?.outerHTML.slice(0,200),parent:e.parentElement.id,body:document.body.className,view:{w:innerWidth,h:innerHeight,docw:document.documentElement.clientWidth,scrollw:document.documentElement.scrollWidth,vv:{w:visualViewport.width,h:visualViewport.height,top:visualViewport.offsetTop,scale:visualViewport.scale}},csswidth:c.width,padding:c.padding}}))))}}
const ready=p=>p.waitForFunction(()=>window.ANESVET_BOOT_DIAGNOSTIC?.snapshot().ready&&!document.body.classList.contains('av-booting'));
function installViewportModel(){
 const native=window.visualViewport,vv=new EventTarget();window.qaViewportOverride=null;
 for(const k of ['height','width','offsetTop','offsetLeft','scale'])Object.defineProperty(vv,k,{get:()=>window.qaViewportOverride?.[k]??native?.[k]??({height:innerHeight,width:innerWidth,offsetTop:0,offsetLeft:0,scale:1})[k]});
 Object.defineProperty(window,'visualViewport',{value:vv,configurable:true});
 native?.addEventListener('resize',()=>vv.dispatchEvent(new Event('resize')));native?.addEventListener('scroll',()=>vv.dispatchEvent(new Event('scroll')));
 window.qaViewportSet=value=>{window.qaViewportOverride=value;vv.dispatchEvent(new Event('resize'))};
 window.qaScrollCalls=[];const scrollBy=window.scrollBy.bind(window);window.scrollBy=(...args)=>{qaScrollCalls.push(args);return scrollBy(...args)};
 const into=Element.prototype.scrollIntoView;Element.prototype.scrollIntoView=function(...args){qaScrollCalls.push({id:this.id,into:args});return into.apply(this,args)};
}
function contrast(css){
 const luminance=s=>{const c=s.match(/[\d.]+/g).slice(0,3).map(Number).map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return .2126*c[0]+.7152*c[1]+.0722*c[2]};
 const a=luminance(css.color),b=luminance(css.background);return(Math.max(a,b)+.05)/(Math.min(a,b)+.05);
}
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;
 const browser=await chromium.launch({executablePath:process.env.ANESVET_CHROMIUM_EXECUTABLE||'/tmp/anesvet-browser/chrome-headless-shell-linux64/chrome-headless-shell',args:['--no-sandbox','--disable-gpu','--disable-software-rasterizer','--disable-dev-shm-usage']});
 try{
  const initial=await browser.newContext({viewport:{width:393,height:852},isMobile:true,hasTouch:true}),p=await initial.newPage();await p.goto(origin);await ready(p);
  const seed=await p.evaluate(()=>{const s=JSON.parse(JSON.stringify(AnesvetApp.getState()));Object.assign(s,{patientName:'QA Mochi',species:'dog',weight:'6.8',asa:'II',patientSaved:true,patientProcedure:'QA surgery',procedure:'QA surgery',anesthetist:'QA Vet',surgeon:'QA Surgeon',casePhase:'intraop',caseStartedAt:Date.now()-60000,timer:{running:false,elapsedMs:60000,startedEpoch:null},hr:'100',rr:'16',map:'75',spo2:'98',etco2:'38',temp:'100.0',caseIdentitySnapshot:{patientName:'QA Mochi',species:'dog',weight:6.8,capturedAt:Date.now()},protocolSnapshot:JSON.parse(JSON.stringify(AnesvetApp.settings()))});s.protocolSnapshot.caseDrugPlan=[{id:'qa-plan',name:'Propofol',phase:'induction',role:'induction',dose:4,route:'IV',conc:10,concUnit:'mg/ml',plannedMl:2.7}];s.events=[{id:'qa-induction',name:'Induction',category:'Workflow',epoch:s.caseStartedAt,elapsedMs:0,clock:'10:00:00'},{id:'qa-start',name:'Surgery start',category:'Workflow',epoch:s.caseStartedAt+1000,elapsedMs:1000,clock:'10:00:01'}];return s;});await initial.close();
  async function launch(s=seed){const ctx=await browser.newContext({viewport:{width:360,height:780},isMobile:true,hasTouch:true});await ctx.addInitScript(installViewportModel);await ctx.addInitScript(s=>{if(!localStorage.getItem('qa-seeded')){localStorage.setItem('anesvet_v14_3_current',JSON.stringify(s));localStorage.setItem('qa-seeded','1');}},s);const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));diagnosticPage=page;page.setDefaultTimeout(2500);await page.goto(origin);await ready(page);if(s.caseLocked)await page.evaluate(()=>AnesvetApp.setTab('orlive',{force:true}));else await page.locator('#avHomePrimary').click();await page.waitForFunction(()=>document.querySelector('.tabpage.active')?.id==='orlive');return {ctx,page};}
  const{ctx,page:q}=await launch();
  await test('360px phone keeps viewport scale 1 and does not expand its layout width',async()=>{const v=await q.evaluate(()=>({inner:innerWidth,client:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth,scale:visualViewport.scale}));assert(v.inner<=361&&v.scroll<=v.client+1&&v.scale>=.99,JSON.stringify(v));});
  await test('End Surgery is visible in the main footer with readable native and shell buttons',async()=>{assert(await q.locator('#avContextWorkflow').isVisible());assert.equal(await q.locator('#avContextWorkflow').innerText(),'จบผ่าตัด');for(const id of ['avContextPrimary','avContextWorkflow','orPrimaryActionBtn']){const css=await q.locator('#'+id).evaluate(e=>{const c=getComputedStyle(e);return {color:c.color,background:c.backgroundColor}});assert(contrast(css)>=4.5,id+' contrast '+contrast(css));const box=await q.locator('#'+id).boundingBox();assert(box.height>=44,id+' touch height');}await q.waitForTimeout(2800);await q.screenshot({path:path.join(OUT,'or-main-360.png')});});
  await test('Transient feedback does not obscure the End Surgery or Vitals actions',async()=>{await q.evaluate(()=>AnesvetApp.toast('QA feedback'));await q.waitForTimeout(100);const toast=await q.locator('.toast').boundingBox(),action=await q.locator('#avContextWorkflow').boundingBox();assert(toast.y+toast.height<=action.y||toast.y>=action.y+action.height,JSON.stringify({toast,action}));});
  await test('Medication queue collapses to its real review count and expands without marking any drug administered',async()=>{const before=await q.evaluate(()=>JSON.stringify(AnesvetApp.getState().drugAdministrations));assert(await q.locator('#orMedicationQueue').isVisible());assert(!(await q.locator('#avMedicationDetails').getAttribute('open')));assert((await q.locator('#avMedicationDetails summary').innerText()).includes('1 NEED REVIEW'));assert(!await q.locator('#orMedicationQueueList').isVisible());await q.locator('#avMedicationDetails summary').evaluate(e=>e.scrollIntoView({block:'center',behavior:'instant'}));await q.locator('#avMedicationDetails summary').click();assert(await q.locator('#orMedicationQueueList').isVisible());assert((await q.locator('#orMedicationQueueList').innerText()).includes('Propofol'));await q.locator('#avMedicationDetails summary').evaluate(e=>e.scrollIntoView({block:'center',behavior:'instant'}));await q.locator('#avMedicationDetails summary').click();assert.equal(await q.evaluate(()=>JSON.stringify(AnesvetApp.getState().drugAdministrations)),before);});
  await test('Scrolled OR retains one header; high-specificity legacy sticky patient bar stays hidden',async()=>{await q.evaluate(()=>{document.body.classList.add('ux-or-context-compact');window.scrollTo(0,500)});await q.waitForTimeout(250);assert(!await q.locator('#orStickyMini').isVisible());assert(await q.locator('#avContextWorkflow').isVisible());});
  await test('Overlay keyboard hides normal dock, keeps page padding, and anchors rail to visible viewport',async()=>{const padding=await q.locator('body>main').evaluate(e=>getComputedStyle(e).paddingBottom);await q.locator('#orEtco2').focus();await q.evaluate(()=>qaViewportSet({height:410,offsetTop:0}));await q.waitForTimeout(400);assert(await q.locator('body').evaluate(e=>e.classList.contains('av-editing')));assert(!await q.locator('#avBottom').isVisible());assert.equal(await q.locator('body>main').evaluate(e=>getComputedStyle(e).paddingBottom),padding);assert.equal(await q.locator('.av-workspace-header').evaluate(e=>getComputedStyle(e).position),'static');const rail=await q.locator('#orFastEntryRail').boundingBox(),input=await q.locator('#orEtco2').boundingBox();assert(rail.y>=0&&rail.y+rail.height<=410);assert(input.y>=0&&input.y+input.height<=rail.y-4);});
  await test('Long warning card and repeated visual viewport scroll events do not trigger a scroll loop',async()=>{await q.locator('#orEtco2').fill('58');await q.waitForTimeout(250);await q.evaluate(()=>{document.getElementById('orEtco2Hint').append(document.createTextNode(' '.repeat(2)+'Long threshold explanation '.repeat(35)));qaScrollCalls=[];for(let i=0;i<20;i++)visualViewport.dispatchEvent(new Event('scroll'));});await q.waitForTimeout(600);assert.equal(await q.evaluate(()=>qaScrollCalls.length),0);assert.equal(await q.evaluate(()=>document.activeElement.id),'orEtco2');assert.equal(await q.evaluate(()=>AnesvetApp.getState().records.length),0);await q.locator('#orEtco2').fill('38');});
  await test('Rapid viewport resize settles with at most one minimal input scroll; no animated card centering',async()=>{await q.evaluate(()=>{qaScrollCalls=[];for(const height of [390,380,375,365,360])qaViewportSet({height,offsetTop:25});});await q.waitForTimeout(500);const calls=await q.evaluate(()=>qaScrollCalls);assert(calls.length<=1,JSON.stringify(calls));assert(!calls.some(x=>x.into));const rail=await q.locator('#orFastEntryRail').boundingBox();assert(rail.y>=25&&rail.y+rail.height<=385);});
  await test('Resize-content Android model does not double-subtract keyboard height',async()=>{await q.evaluate(()=>qaViewportSet(null));await q.setViewportSize({width:360,height:430});await q.waitForTimeout(500);const rail=await q.locator('#orFastEntryRail').boundingBox(),input=await q.locator('#orEtco2').boundingBox();assert(rail.y>300&&rail.y+rail.height<=430,JSON.stringify(rail));assert(input.y>=0&&input.y+input.height<rail.y);await q.screenshot({path:path.join(OUT,'editing-viewport-360.png')});});
  await test('Prev/Next preserve the editor; finishing the last field never automatically creates a record',async()=>{await q.locator('#orFastEntryNextBtn').click();assert.equal(await q.evaluate(()=>document.activeElement.id),'orRr');await q.locator('#orFastEntryPrevBtn').click();assert.equal(await q.evaluate(()=>document.activeElement.id),'orEtco2');await q.locator('#orEtco2').press('Enter');assert.equal(await q.evaluate(()=>document.activeElement.id),'orRr');await q.locator('#orRr').press('Enter');assert.equal(await q.evaluate(()=>document.activeElement.id),'orTemp');await q.locator('#orTemp').press('Enter');await q.waitForTimeout(250);assert.equal(await q.evaluate(()=>AnesvetApp.getState().records.length),0);assert(!await q.locator('#orFastEntryRail').isVisible());assert(await q.locator('#avBottom').isVisible());});
  await q.setViewportSize({width:360,height:780});
  await test('Explicit rail Save records through native handler once and restores the normal actions',async()=>{await q.locator('#orHr').fill('101');await q.locator('#orFastEntrySaveBtn').click();await q.waitForFunction(()=>AnesvetApp.getState().records.length===1);await q.waitForTimeout(250);assert.equal(await q.evaluate(()=>Number(AnesvetApp.getState().records[0].hr)),101);assert(await q.locator('#avBottom').isVisible());assert(!await q.locator('#orFastEntryRail').isVisible());await q.locator('#avContextPrimary').click();assert.equal(await q.evaluate(()=>AnesvetApp.getState().records.length),1);});
  await test('Fill blanks remains available in native OR tools; the duplicate inline Save stays out of the main screen',async()=>{assert(!await q.locator('#orVitalsFocusSaveBtn').isVisible());await q.locator('#avHeaderTools').click();assert(await q.locator('#orCopyLastVitalsBtn').isVisible());await q.locator('#orMoreCloseBtn').click();});
  await test('End Surgery cancel changes no evidence; confirm records one timestamp and advances to Emergence',async()=>{const before=await q.evaluate(()=>JSON.stringify({events:AnesvetApp.getState().events,phase:AnesvetApp.getState().casePhase,ended:AnesvetApp.getState().surgeryEndedAt}));await q.locator('#avContextWorkflow').click();assert(await q.locator('#orStepConfirmDialog').isVisible());assert.equal(await q.locator('#orStepConfirmTitle').innerText(),'End surgery?');await q.locator('#orStepConfirmCancelBtn').click();assert.equal(await q.evaluate(()=>JSON.stringify({events:AnesvetApp.getState().events,phase:AnesvetApp.getState().casePhase,ended:AnesvetApp.getState().surgeryEndedAt})),before);await q.locator('#avContextWorkflow').click();await q.locator('#orStepConfirmGoBtn').click();await q.waitForFunction(()=>AnesvetApp.getState().casePhase==='emergence');assert(await q.evaluate(()=>AnesvetApp.getState().surgeryEndedAt>0));assert.equal(await q.evaluate(()=>AnesvetApp.getState().events.filter(e=>e.name==='Surgery end').length),1);assert.equal(await q.locator('#avContextWorkflow').innerText(),'เริ่มฟื้นตัว');});
  await ctx.close();
  const special=JSON.parse(JSON.stringify(seed));special.caseWorkflowProfile='csection';special.procedureTemplateSnapshot={workflowProfile:'csection',label:'QA C-section'};
  const{ctx:cx,page:c}=await launch(special);
  await test('C-section End Surgery remains accessible without losing the native neonatal milestone action',async()=>{assert.equal(await c.locator('#orPrimaryActionBtn').getAttribute('data-action'),'first-neonate');assert.equal(await c.locator('#avContextWorkflow').innerText(),'จบผ่าตัด');assert.equal(await c.locator('#avContextWorkflow').getAttribute('data-native-target'),'orSecondaryPhaseBtn');await c.locator('#avContextWorkflow').click();assert.equal(await c.locator('#orStepConfirmTitle').innerText(),'End surgery?');await c.locator('#orStepConfirmCancelBtn').click();assert.equal(await c.locator('#orPrimaryActionBtn').getAttribute('data-action'),'first-neonate');});
  await cx.close();
  const locked=JSON.parse(JSON.stringify(seed));locked.caseLocked=true;const{ctx:lx,page:l}=await launch(locked);
  await test('Final locked case cannot expose an enabled phase transition',async()=>{assert(!await l.locator('#avContextWorkflow').isVisible());assert.equal(await l.evaluate(()=>AnesvetApp.getState().surgeryEndedAt||null),null);});await lx.close();
  await test('No uncaught runtime errors in focused input and phase transitions',async()=>assert.deepEqual(errors,[]));
 }finally{await browser.close();await new Promise(r=>server.close(r));}
 const report={version:'17.5.3',passed:tests.filter(x=>x.pass).length,total:tests.length,tests,errors,limits:['Controlled Chromium mobile visualViewport overlay/resize models, not physical Android/iOS IME validation.']};fs.writeFileSync(path.join(ROOT,'QA_V17_5_3_EDITING_RESULTS.json'),JSON.stringify(report,null,2));if(report.passed!==report.total)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1;server.close()});
