'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');
const {chromium}=require('playwright');
const ROOT=__dirname,OUT=path.resolve(ROOT,'../../output/runtime-v17-5-1');fs.mkdirSync(OUT,{recursive:true});
const results=[],errors=[];let workerRevision=1;
async function test(name,fn){try{await fn();results.push({name,pass:true});console.log('PASS',name)}catch(e){results.push({name,pass:false,error:e.message});console.log('FAIL',name,e.message)}}
const server=http.createServer((req,res)=>{let f=path.resolve(ROOT,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!f.startsWith(ROOT+path.sep)&&f!==ROOT){res.writeHead(403);res.end();return;}if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');if(!fs.existsSync(f)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',{'.js':'text/javascript','.css':'text/css','.html':'text/html','.webmanifest':'application/manifest+json','.svg':'image/svg+xml','.png':'image/png','.woff2':'font/woff2','.ttf':'font/ttf'}[path.extname(f)]||'application/octet-stream');let body=fs.readFileSync(f);if(path.basename(f)==='service-worker.js'&&workerRevision>1)body=Buffer.from(body.toString().replace('anesvet-v17-5-1-mobile-design','anesvet-v17-5-1-mobile-design-qa-'+workerRevision));res.end(body);});
const active=p=>p.evaluate(()=>document.querySelector('.tabpage.active')?.id);
const noOverflow=async p=>assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Horizontal page overflow');
const ready=async p=>{await p.waitForFunction(()=>window.ANESVET_BOOT_DIAGNOSTIC?.snapshot().ready);await p.waitForFunction(()=>!document.body.classList.contains('av-booting'));await p.waitForTimeout(200);};
const click=async(p,id)=>{await p.locator('#'+id).click();await p.waitForTimeout(150);};
const route=async(p,id)=>{await p.evaluate(id=>AnesvetApp.setTab(id),id);await p.waitForTimeout(100);};
async function fixture(p){const s=await p.evaluate(()=>JSON.parse(JSON.stringify(AnesvetApp.getState())));s.patientName='QA Patient';s.species='dog';s.weight='10';s.asa='II';s.patientSaved=true;s.procedure='QA procedure';s.patientProcedure='QA procedure';s.anesthetist='QA Vet';s.surgeon='QA Surgeon';s.caseStartedAt=Date.now()-60000;s.casePhase='intraop';s.timer={running:false,elapsedMs:60000,startedEpoch:null};s.caseIdentitySnapshot={patientName:s.patientName,species:s.species,weight:10,capturedAt:s.caseStartedAt};s.events=[{id:'qa-induction',name:'Induction',category:'Workflow',epoch:s.caseStartedAt,elapsedMs:0,clock:'10:00:00'}];s.protocolSnapshot=await p.evaluate(()=>JSON.parse(JSON.stringify(AnesvetApp.settings())));return s;}
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;const browser=await chromium.launch({executablePath:process.env.ANESVET_CHROMIUM_EXECUTABLE||'/tmp/anesvet-browser/chrome-headless-shell-linux64/chrome-headless-shell',headless:true,args:['--no-sandbox','--disable-gpu','--disable-software-rasterizer','--disable-dev-shm-usage']});
try{
 const ctx=await browser.newContext({viewport:{width:393,height:852},isMobile:true,hasTouch:true}),p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));
 await test('Empty startup uses live storage, blank BW, no onboarding obstruction',async()=>{await p.goto(origin);await ready(p);assert.equal(await active(p),'start');assert(await p.locator('#avHomeEmpty').isVisible());assert(!await p.locator('#avHomeCase').isVisible());assert.equal(await p.locator('#weight').inputValue(),'');await p.waitForTimeout(1200);assert.equal(await p.locator('dialog[open]').count(),0);await noOverflow(p);await p.screenshot({path:path.join(OUT,'home-empty.png')});});
 await test('Primary action reaches original patient fields',async()=>{await click(p,'avHomePrimary');assert.equal(await active(p),'patient');assert.equal(await p.locator('#weight').inputValue(),'');assert(await p.locator('#savePatientBtn').count());});
 await test('OR and Recovery tabs retain readiness gates',async()=>{await p.locator('[data-av-nav="orlive"]').click();await p.locator('#preOrReadinessDialog').waitFor({state:'visible'});assert.notEqual(await active(p),'orlive');await click(p,'preOrReadinessCloseBtn');await p.locator('[data-av-nav="recovery"]').click();assert.notEqual(await active(p),'recovery');});
 await test('Real patient setup save confirms measured BW and survives reload',async()=>{await p.locator('#patientName').fill('QA Patient');await p.locator('#species').selectOption('dog');await p.locator('#weight').fill('10');await p.locator('[data-asa="II"]').click();await p.locator('#patientProcedure').fill('QA procedure');await p.locator('#anesthetist').fill('QA Vet');await p.locator('#surgeon').fill('QA Surgeon');await click(p,'savePatientBtn');await p.waitForFunction(()=>AnesvetApp.getState().patientSaved);assert.equal(await active(p),'preop');assert.equal(await p.evaluate(()=>AnesvetApp.getState().weight),'10');await p.reload();await ready(p);assert.equal(await p.evaluate(()=>AnesvetApp.getState().patientName),'QA Patient');assert(await p.locator('#avHomeCase').isVisible());await p.screenshot({path:path.join(OUT,'home-active.png')});});
 await test('Case hub and every More route remain reachable without mutating clinical state',async()=>{const before=await p.evaluate(()=>{const s=AnesvetApp.getState();return JSON.stringify({name:s.patientName,weight:s.weight,records:s.records,events:s.events,meds:s.drugAdministrations,recovery:s.recoveryRecords,checks:s.preopChecks});});await p.locator('#avHomeCase [data-av-route="casehub"]').click();assert.equal(await active(p),'casehub');for(const id of ['patient','preop','drugs','plan','casesummary','more','cases','record','events','trends','timeline','settings','dashboard','start']){await route(p,id);assert.equal(await active(p),id);await noOverflow(p);}assert.equal(await p.evaluate(()=>{const s=AnesvetApp.getState();return JSON.stringify({name:s.patientName,weight:s.weight,records:s.records,events:s.events,meds:s.drugAdministrations,recovery:s.recoveryRecords,checks:s.preopChecks});}),before);});
 await test('Knowledge and BOAS/cardiac/pancreatitis/liver/kidney/ECG stay read only',async()=>{const before=await p.evaluate(()=>JSON.stringify(AnesvetApp.getState()));await p.locator('#start [data-av-knowledge]').click();for(const id of ['brachycephalic','cardiac-disease','pancreatitis','hepatic-disease','renal-disease']){await p.evaluate(id=>ANESVET_CLINICAL_KNOWLEDGE.openGuide(id),id);assert(await p.locator('.ck-phase').count()>=8);await noOverflow(p);}await p.evaluate(()=>ANESVET_CLINICAL_KNOWLEDGE.open('ecg'));assert.equal(await p.locator('[data-ecg-example]').count(),18);await click(p,'ckClose');assert.equal(await p.evaluate(()=>JSON.stringify(AnesvetApp.getState())),before);});
 const seed=await fixture(p);await ctx.close();
 const c2=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await c2.addInitScript(seed=>{if(!localStorage.getItem('qa-seeded')){localStorage.setItem('anesvet_v14_3_current',JSON.stringify(seed));localStorage.setItem('qa-seeded','1');}},seed);const q=await c2.newPage();q.on('pageerror',e=>errors.push(e.message));
 await test('Progressed case resumes directly into OR with six real inputs',async()=>{await q.goto(origin);await ready(q);assert.equal(await active(q),'orlive');for(const id of ['orHr','orMap','orSpo2','orEtco2','orTemp','orRr'])assert(await q.locator('#'+id).isVisible(),id);await noOverflow(q);});
 await test('Vitals save records actual fields and survives reload',async()=>{for(const [id,value] of Object.entries({orHr:'100',orMap:'75',orSpo2:'98',orEtco2:'38',orRr:'16',orTemp:'37.8'}))await q.locator('#'+id).fill(value);await click(q,'avContextPrimary');await q.waitForFunction(()=>AnesvetApp.getState().records.length===1);await click(q,'avContextPrimary');assert.equal(await q.evaluate(()=>AnesvetApp.getState().records.length),1,'Duplicate footer tap must use native duplicate guard');const row=await q.evaluate(()=>AnesvetApp.getState().records[0]);assert.equal(Number(row.hr),100);assert.equal(Number(row.map),75);assert.equal(Number(row.etco2),38);await q.reload();await ready(q);assert.equal(await active(q),'orlive');assert.equal(await q.evaluate(()=>AnesvetApp.getState().records.length),1);await q.screenshot({path:path.join(OUT,'or-live.png')});});
 await test('Six measured inputs fit above footer at 360x780; threshold details preserve native text',async()=>{await q.setViewportSize({width:360,height:780});await q.locator('#orEtco2').fill('45');await q.waitForTimeout(200);for(const id of ['orHr','orMap','orSpo2','orEtco2','orTemp','orRr']){const box=await q.locator('#'+id).boundingBox(),footer=await q.locator('#avBottom').boundingBox();assert(box.y>=0&&box.y+box.height<=footer.y,id+' must remain above footer');assert(box.height>=44,id+' touch height');}await click(q,'avHeaderTools');await q.locator('#avVitalThresholds summary').click();for(const id of ['orHrHint','orMapHint','orSpo2Hint','orEtco2Hint','orTempHint','orRrHint'])assert.equal(await q.locator('#avThreshold'+id).innerText(),await q.locator('#'+id).textContent());await click(q,'orMoreCloseBtn');await q.locator('#orEtco2').fill('38');await q.setViewportSize({width:390,height:844});});
 await test('Draft change is distinguished from saved record; critical hints remain visible',async()=>{await q.locator('#orHr').fill('101');await q.waitForTimeout(200);assert((await q.locator('#avMeasurementStatus').innerText()).includes('ยังไม่ลง record'));assert.equal(Number(await q.evaluate(()=>AnesvetApp.getState().records[0].hr)),100);assert.equal(await q.evaluate(()=>AnesvetApp.getState().records.length),1);await q.locator('#orHr').fill('100');await q.locator('#orMap').fill('55');await q.waitForTimeout(200);assert(await q.locator('.or-vital-card[data-vital="map"].danger #orMapHint').isVisible());const hint=await q.locator('#orMapHint').evaluate(el=>({visible:el.clientHeight,content:el.scrollHeight}));assert(hint.content<=hint.visible+1,'Critical hint must not be clipped');await q.locator('#orMap').fill('75');await q.waitForTimeout(200);assert((await q.locator('#avMeasurementStatus').innerText()).includes('ตรงกับ record'));await q.screenshot({path:path.join(OUT,'or-live.png')});});
 await test('Downloaded worker waits for explicit update and restores actual case after promotion',async()=>{await q.evaluate(()=>navigator.serviceWorker.ready);await q.waitForFunction(()=>!!navigator.serviceWorker.controller);const before=await q.evaluate(()=>{const s=AnesvetApp.getState();return JSON.stringify({caseId:s.caseId,records:s.records,timer:s.timer});});workerRevision=2;await q.evaluate(async()=>{const reg=await navigator.serviceWorker.getRegistration();await reg.update();});await q.waitForFunction(async()=>!!(await navigator.serviceWorker.getRegistration())?.waiting);await q.locator('#updateBanner').waitFor({state:'visible'});await q.waitForTimeout(300);assert.equal(await q.evaluate(()=>{const s=AnesvetApp.getState();return JSON.stringify({caseId:s.caseId,records:s.records,timer:s.timer});}),before);await Promise.all([q.waitForNavigation(),q.locator('#updateNowBtn').click()]);await ready(q);assert.equal(await active(q),'orlive');assert.equal(await q.evaluate(()=>{const s=AnesvetApp.getState();return JSON.stringify({caseId:s.caseId,records:s.records,timer:s.timer});}),before);});
 await test('Footer Meds opens actual medication editor, no automatic administration',async()=>{const n=await q.evaluate(()=>AnesvetApp.getState().drugAdministrations.length);await q.locator('#avBottom [data-av-action="meds"]').click();await q.locator('#orQuickDrugDialog').waitFor({state:'visible'});assert.equal(await q.evaluate(()=>AnesvetApp.getState().drugAdministrations.length),n);await noOverflow(q);await q.screenshot({path:path.join(OUT,'medication.png')});await click(q,'orQuickDrugCloseTop');});
 await test('Actual medication validates fields, respects cancel, saves once and persists',async()=>{await route(q,'orlive');await q.locator('#avBottom [data-av-action="meds"]').click();await q.locator('#orQuickDrugSelect').selectOption('0');await click(q,'orQuickDrugSaveBtn');assert.equal(await q.evaluate(()=>AnesvetApp.getState().drugAdministrations.length),0);assert((await q.locator('#orQuickDrugError').innerText()).length>0);await q.locator('#orQuickDrugActual').fill('1');await q.locator('#orQuickDrugRoute').fill('IV');await q.locator('#orQuickDrugBy').fill('QA Vet');await q.locator('#orQuickDrugConcentration').fill('QA preparation');q.once('dialog',d=>d.dismiss());await click(q,'orQuickDrugSaveBtn');assert.equal(await q.evaluate(()=>AnesvetApp.getState().drugAdministrations.length),0);q.once('dialog',d=>d.accept());await click(q,'orQuickDrugSaveBtn');assert.equal(await q.evaluate(()=>AnesvetApp.getState().drugAdministrations.length),1);const row=await q.evaluate(()=>AnesvetApp.getState().drugAdministrations[0]);assert.equal(Number(row.actual),1);assert.equal(row.route,'IV');await click(q,'orQuickDrugCloseTop');await q.reload();await ready(q);assert.equal(await q.evaluate(()=>AnesvetApp.getState().drugAdministrations.length),1);});
 await test('OR tools retain native timer/wake/fullscreen and close correctly',async()=>{await click(q,'avHeaderTools');await q.locator('#orMoreDialog').waitFor({state:'visible'});assert.equal(await q.locator('#orMoreDialog #orStartBtn').count(),1);await noOverflow(q);await click(q,'orMoreCloseBtn');assert(!await q.locator('#orMoreDialog').isVisible());await q.locator('[data-av-nav="casehub"]').click();assert.equal(await active(q),'casehub');});
 await test('Layout works at 360, 393, 768 and 1280 without page overflow',async()=>{for(const width of [360,393,768,1280]){await q.setViewportSize({width,height:width<768?852:900});for(const id of ['start','casehub','more','patient','preop','drugs','settings','cases']){await route(q,id);await noOverflow(q);}await q.screenshot({path:path.join(OUT,'screen-'+width+'.png')});}await q.setViewportSize({width:390,height:844});});
 await test('PWA reload is offline-ready with all new assets and local fonts',async()=>{await q.evaluate(()=>navigator.serviceWorker.ready);await q.waitForFunction(()=>!!navigator.serviceWorker.controller);assert((await q.evaluate(()=>caches.keys())).includes('anesvet-v17-5-1-mobile-design-qa-2'));await c2.setOffline(true);await q.reload();await ready(q);await noOverflow(q);assert.equal(await active(q),'orlive');await q.evaluate(async()=>{await document.fonts.load('600 28px Inter');await document.fonts.load('16px "ANESVET Thai"','วางยาสลบ');});assert(await q.evaluate(()=>document.fonts.check('600 28px Inter')));await c2.setOffline(false);});
 await c2.close();
 const recovery={...seed,casePhase:'recovery',recoveryStartedAt:Date.now(),extubatedAt:Date.now()};const c3=await browser.newContext({viewport:{width:360,height:780},isMobile:true,hasTouch:true});await c3.addInitScript(s=>localStorage.setItem('anesvet_v14_3_current',JSON.stringify(s)),recovery);const r=await c3.newPage();r.on('pageerror',e=>errors.push(e.message));
 await test('Recovery resumes, records real observations, OR remains locked',async()=>{await r.goto(origin);await ready(r);assert.equal(await active(r),'recovery');await noOverflow(r);await r.locator('[data-av-nav="orlive"]').click();assert.equal(await active(r),'recovery');await r.screenshot({path:path.join(OUT,'recovery.png')});for(const [id,v] of Object.entries({recHR:'100',recRR:'18',recMAP:'75',recSpO2:'98',recTemp:'37.8'})){await r.evaluate(id=>{const el=document.getElementById(id);for(let n=el?.parentElement;n;n=n.parentElement){if(n.tagName==='DETAILS')n.open=true;}window.ANESVETProgressiveDisclosure?.openForElement?.(el);window.ANESVETFocusedWorkspace?.openForElement?.(el);},id);await r.locator('#'+id).fill(v);}await click(r,'recordRecoveryVitalsBtn');await r.waitForFunction(()=>AnesvetApp.getState().recoveryRecords.length===1);assert.equal(Number(await r.evaluate(()=>AnesvetApp.getState().recoveryRecords[0].hr)),100);});await c3.close();
 const corrupt=await browser.newContext({viewport:{width:393,height:852}});await corrupt.addInitScript(()=>localStorage.setItem('anesvet_v14_3_current','{invalid'));const z=await corrupt.newPage();z.on('pageerror',e=>errors.push(e.message));
 await test('Unreadable storage fails closed with retry and review, original bytes preserved',async()=>{await z.goto(origin);await z.waitForTimeout(1000);await z.waitForFunction(()=>document.body.classList.contains('av-boot-error'));assert.equal(await z.evaluate(()=>localStorage.getItem('anesvet_v14_3_current')),'{invalid');assert(await z.locator('#avBootRetry').isVisible());assert(!await z.locator('#avBottom').isVisible());await noOverflow(z);await z.screenshot({path:path.join(OUT,'startup-error.png')});});await corrupt.close();
 await test('No uncaught runtime errors',async()=>assert.deepEqual(errors,[]));
}finally{await browser.close();await new Promise(r=>server.close(r));}
const report={version:'17.5.1',passed:results.filter(r=>r.pass).length,total:results.length,errors,tests:results,limits:['Chromium mobile emulation; physical iOS/Android not tested.','Clinical knowledge and dose rules are inherited, not independently clinically approved by this UI test.']};fs.writeFileSync(path.join(OUT,'QA_V17_5_1_MOBILE_RESULTS.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));if(report.passed!==report.total)process.exitCode=1;
})().catch(e=>{console.error(e);process.exit(1)});
