'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');
const {chromium}=require('playwright');
const ROOT=__dirname,BASE=process.env.ANESVET_BASELINE_DIR||path.resolve(ROOT,'../../baseline/v17-5-3'),OUT=path.resolve(ROOT,'../../output/splash-v17-5-4');fs.mkdirSync(OUT,{recursive:true});
const tests=[],errors=[];let remoteManifest=null,manifestStatus=200;
const server=http.createServer((req,res)=>{
 const url=new URL(req.url,'http://localhost'),baseline=url.pathname.startsWith('/baseline/');let rel=url.pathname.replace(/^\/(baseline\/)?/,'');if(!rel)rel='index.html';let f=path.join(baseline?BASE:ROOT,rel);if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');if(!fs.existsSync(f)){res.writeHead(404);res.end();return}
 res.setHeader('Content-Type',{'.js':'text/javascript','.css':'text/css','.html':'text/html','.svg':'image/svg+xml','.webmanifest':'application/manifest+json','.png':'image/png'}[path.extname(f)]||'application/octet-stream');res.setHeader('Cache-Control','no-store');
 if(!baseline&&rel==='manifest.webmanifest'&&remoteManifest){res.writeHead(manifestStatus);res.end(JSON.stringify(remoteManifest));return}res.end(fs.readFileSync(f));
});
async function test(name,fn){try{await fn();tests.push({name,pass:true});console.log('PASS',name)}catch(e){tests.push({name,pass:false,error:e.message});console.log('FAIL',name,e.message)}}
const ready=p=>p.waitForFunction(()=>window.ANESVET_BOOT_DIAGNOSTIC?.snapshot().ready&&!document.body.classList.contains('av-booting')&&!document.body.classList.contains('av-boot-error'),null,{timeout:30000});
async function shot(p,name){const cdp=await p.context().newCDPSession(p);const s=await cdp.send('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(OUT,name),Buffer.from(s.data,'base64'));await cdp.detach();}
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({executablePath:process.env.ANESVET_CHROMIUM_EXECUTABLE||'/tmp/anesvet-browser/chrome-headless-shell-linux64/chrome-headless-shell',args:['--no-sandbox','--disable-gpu','--disable-software-rasterizer','--disable-dev-shm-usage']});
try{
 let baselineMetrics;
 await test('Baseline reproduction: held external CSS prevents the Figma first paint',async()=>{
  const ctx=await browser.newContext({viewport:{width:393,height:852},isMobile:true,hasTouch:true,serviceWorkers:'block'});let release;const latch=new Promise(r=>release=r);await ctx.route('**/*.css?*',async r=>{await latch;await r.continue().catch(()=>{})});const p=await ctx.newPage();
  try{await p.goto(origin+'/baseline/',{waitUntil:'commit'});await p.waitForFunction(()=>!!document.getElementById('avBoot'));await p.waitForTimeout(450);
   baselineMetrics=await p.evaluate(()=>({paint:performance.getEntriesByType('paint').map(x=>x.name),bg:getComputedStyle(document.documentElement).backgroundColor,logoWidth:document.querySelector('.av-boot-logo').getBoundingClientRect().width}));
   assert(!baselineMetrics.paint.includes('first-contentful-paint'));// Baseline has no paint while CSS is held; skip screenshot.
  }finally{release();await ctx.close()}
 });
 const ctx=await browser.newContext({viewport:{width:393,height:852},isMobile:true,hasTouch:true,serviceWorkers:'block'});let release;const latch=new Promise(r=>release=r);await ctx.route('**/*.css?*',async r=>{await latch;await r.continue().catch(()=>{})});const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));let early;
 await test('Figma splash paints while all 38 external styles are still pending',async()=>{
  await p.goto(origin,{waitUntil:'commit'});await p.waitForFunction(()=>document.querySelector('.av-boot-logo')?.complete&&document.querySelector('.av-boot-logo')?.naturalWidth>0);await p.waitForTimeout(450);
  early=await p.evaluate(()=>({paint:performance.getEntriesByType('paint').map(x=>({name:x.name,time:x.startTime})),bg:getComputedStyle(document.documentElement).backgroundColor,bootHidden:document.getElementById('avBoot').hidden,pending:Array.from(document.querySelectorAll('link[data-av-style]')).filter(x=>x.dataset.avStyle==='pending').length,assets:Array.from(document.querySelectorAll('#avBoot img')).map(x=>({src:x.getAttribute('src'),loaded:x.complete&&x.naturalWidth>0,w:x.getBoundingClientRect().width,h:x.getBoundingClientRect().height})),width:document.documentElement.scrollWidth,client:document.documentElement.clientWidth,viewport:innerWidth}));
  assert(early.paint.some(x=>x.name==='first-contentful-paint'));assert.equal(early.bg,'rgb(11, 45, 49)');assert.equal(early.pending,38);assert(!early.bootHidden);assert.equal(early.assets.length,6);assert(early.assets.every(x=>x.loaded));assert.equal(early.assets.find(x=>x.src.endsWith('logo.png')).w,220);assert.equal(early.assets.find(x=>x.src.endsWith('ring.svg')).w,176);assert(early.width<=early.client+1);assert(early.viewport<=394);assert(await p.evaluate(()=>document.fonts.check('12px "ANESVET Thai"','กำลังเตรียมหน้าจอ')));await shot(p,'figma-first-paint-393.png');
 });
 await test('Ready clinical runtime cannot dismiss startup while styles are incomplete',async()=>{await p.waitForFunction(()=>window.ANESVET_BOOT_DIAGNOSTIC?.snapshot().ready);assert(await p.locator('#avBoot').isVisible());assert(await p.evaluate(()=>document.body.classList.contains('av-booting')));assert(!await p.locator('#weight').isVisible());assert(!await p.locator('#avBottom').isVisible());assert.equal(await p.evaluate(()=>AnesvetApp.getState().records.length),0);});
 await test('The exact first-paint assets fit a 360 pixel viewport without overflow',async()=>{await p.setViewportSize({width:360,height:780});const v=await p.evaluate(()=>({width:document.documentElement.scrollWidth,client:document.documentElement.clientWidth,logo:document.querySelector('.av-boot-logo').getBoundingClientRect().width,ring:document.querySelector('.av-boot-ring').getBoundingClientRect().width,rail:document.querySelector('.av-boot-trace').getBoundingClientRect().width,innerWidth,offenders:Array.from(document.body.children).map(e=>({id:e.id,tag:e.tagName,w:e.getBoundingClientRect().width,sw:e.scrollWidth})).filter(e=>e.sw>360)}));await shot(p,'figma-first-paint-360.png');assert(v.width<=v.client,JSON.stringify(v));assert.equal(v.logo,220);assert.equal(v.ring,176);assert.equal(v.rail,310.5);await shot(p,'figma-first-paint-360.png');});
 await test('Only after all styles load does the app open its native current-case home',async()=>{release();await ready(p);assert.equal(await p.evaluate(()=>document.querySelector('.tabpage.active')?.id),'start');assert.equal(await p.evaluate(()=>Array.from(document.querySelectorAll('link[data-av-style]')).filter(x=>x.dataset.avStyle!=='ready'||x.media!=='all').length),0);assert(await p.locator('#avHomeEmpty').isVisible());assert.equal(await p.locator('#weight').inputValue(),'');});
 const seed=await p.evaluate(()=>{let s=JSON.parse(JSON.stringify(AnesvetApp.getState()));Object.assign(s,{patientName:'QA Splash',species:'dog',weight:'8',patientSaved:true,casePhase:'intraop',caseStartedAt:Date.now()-60000,timer:{running:false,elapsedMs:60000,startedEpoch:null},caseIdentitySnapshot:{patientName:'QA Splash',species:'dog',weight:8,capturedAt:Date.now()},protocolSnapshot:JSON.parse(JSON.stringify(AnesvetApp.settings()))});s.records=[{id:'qa-splash-record',epoch:s.caseStartedAt,elapsedMs:0,clock:'10:00:00',hr:100,map:75,spo2:98,etco2:40,rr:16,temp:100,note:''}];s.events=[{id:'qa-splash-event',name:'Induction',category:'Workflow',epoch:s.caseStartedAt,elapsedMs:0,clock:'10:00:00'}];return s;});await ctx.close();
 await test('Failed stylesheet is fail-closed with Retry; seeded clinical records are preserved',async()=>{const c=await browser.newContext({viewport:{width:360,height:780},isMobile:true,serviceWorkers:'block'});await c.addInitScript(s=>localStorage.setItem('anesvet_v14_3_current',JSON.stringify(s)),seed);await c.route('**/mobile-design.css?*',r=>r.abort());const q=await c.newPage();q.on('pageerror',e=>errors.push(e.message));await q.goto(origin);await q.waitForFunction(()=>document.body.classList.contains('av-boot-error'));assert(await q.locator('#avBootRetry').isVisible());assert(await q.locator('#avBootReview').isDisabled());assert(!await q.locator('#weight').isVisible());assert.equal(await q.evaluate(()=>JSON.parse(localStorage.getItem('anesvet_v14_3_current')).records[0].id),'qa-splash-record');assert((await q.locator('#avBootStatus').innerText()).includes('โหลดรูปแบบ'));await shot(q,'stylesheet-error-360.png');await c.close();});
 await test('Stylesheet timeout never exposes unfinished clinical controls',async()=>{const c=await browser.newContext({viewport:{width:360,height:780},isMobile:true,serviceWorkers:'block'});let release;const wait=new Promise(r=>release=r);await c.route('**/ui-refinement.css?*',async r=>{await wait;await r.continue().catch(()=>{})});const q=await c.newPage();try{await q.goto(origin,{waitUntil:'domcontentloaded'});await q.waitForFunction(()=>document.body.classList.contains('av-boot-error'),null,{timeout:16000});assert(await q.locator('#avBootReview').isDisabled());assert(!await q.locator('#weight').isVisible());assert((await q.locator('#avBootStatus').innerText()).includes('ยังโหลดหน้าจอไม่ครบ'));}finally{release();await c.close()}});
 await test('Retry after a stylesheet failure restores normal startup',async()=>{const c=await browser.newContext({viewport:{width:360,height:780},serviceWorkers:'block'});let fail=true;await c.route('**/mobile-design.css?*',r=>fail?r.abort():r.continue());const q=await c.newPage();await q.goto(origin);await q.waitForFunction(()=>document.body.classList.contains('av-boot-error'));fail=false;await q.locator('#avBootRetry').click();await ready(q);assert(await q.locator('#avHomeEmpty').isVisible());await c.close();});
 const live=await browser.newContext({viewport:{width:360,height:780},isMobile:true});const q=await live.newPage();q.on('pageerror',e=>errors.push(e.message));await q.goto(origin);await ready(q);await q.evaluate(()=>navigator.serviceWorker.ready);await q.waitForFunction(()=>!!navigator.serviceWorker.controller);
 await test('Installed manifest keeps the exact previous app identity and uses the dark splash color',async()=>{const old=JSON.parse(fs.readFileSync(path.join(BASE,'manifest.webmanifest'))),m=await q.evaluate(()=>fetch('./manifest.webmanifest').then(r=>r.json()));assert.equal(m.start_url,old.start_url);assert.equal(m.scope,old.scope);assert.equal(m.id,old.id);assert.equal(await q.locator('link[rel=manifest]').getAttribute('href'),'./manifest.webmanifest');assert.equal(m.background_color,'#0b2d31');assert.equal(m.theme_color,'#0b2d31');assert(m.icons.some(x=>x.sizes==='512x512'&&x.type==='image/png'));assert(m.icons.every(x=>x.src.endsWith('?v=17.5.4')));});
 await test('An online manifest refresh replaces an old cached white splash',async()=>{
  const old={name:'Old installed manifest',background_color:'#ffffff',theme_color:'#ffffff',icons:[]};await q.evaluate(async old=>{const names=await caches.keys(),key=names.find(x=>x==='anesvet-v17-5-4-startup'),c=await caches.open(key);await c.put('./manifest.webmanifest',new Response(JSON.stringify(old),{headers:{'Content-Type':'application/manifest+json'}}));},old);
  remoteManifest={...JSON.parse(fs.readFileSync(path.join(ROOT,'manifest.webmanifest'))),name:'QA fresh manifest'};const m=await q.evaluate(()=>fetch('./manifest.webmanifest').then(r=>r.json()));assert.equal(m.name,'QA fresh manifest');assert.equal(m.background_color,'#0b2d31');await q.waitForFunction(async()=>{const x=await caches.match('./manifest.webmanifest');return x&&(await x.json()).name==='QA fresh manifest'});
 });
 await test('Offline manifest requests use the last successfully updated dark copy',async()=>{await live.setOffline(true);const m=await q.evaluate(()=>fetch('./manifest.webmanifest').then(r=>r.json()));assert.equal(m.name,'QA fresh manifest');assert.equal(m.background_color,'#0b2d31');await live.setOffline(false);});
 await test('HTTP failure cannot replace the cached manifest with an error response',async()=>{manifestStatus=503;remoteManifest={name:'HTTP failure'};const m=await q.evaluate(()=>fetch('./manifest.webmanifest').then(r=>r.json()));assert.equal(m.name,'QA fresh manifest');assert.equal(await q.evaluate(async()=>JSON.parse(await (await caches.match('./manifest.webmanifest')).text()).name),'QA fresh manifest');manifestStatus=200;remoteManifest=null;});
 await test('Versioned Android icon URLs are available offline without changing logo bytes',async()=>{await live.setOffline(true);const xs=await q.evaluate(async()=>{const m=await fetch('./manifest.webmanifest').then(r=>r.json());return Promise.all(m.icons.map(async i=>{const r=await fetch(i.src);return{status:r.status,type:r.headers.get('Content-Type'),bytes:(await r.arrayBuffer()).byteLength}}))});assert.equal(xs.length,3);assert(xs.every(x=>x.status===200&&x.type==='image/png'&&x.bytes>0));await live.setOffline(false);});
 await live.close();
 await test('No uncaught runtime errors in first-paint, failure, retry or manifest flows',async()=>assert.deepEqual(errors,[]));
 const report={version:'17.5.4',passed:tests.filter(x=>x.pass).length,total:tests.length,tests,errors,baselineMetrics,early,limits:['Chromium mobile emulation; native Android launcher/WebAPK splash not exercised.','A new service worker must first activate through the existing checkpointed update flow.','Chrome controls installed manifest update timing; this code cannot instantly redraw an existing native splash.']};fs.writeFileSync(path.join(ROOT,'QA_V17_5_4_SPLASH_RESULTS.json'),JSON.stringify(report,null,2));if(report.passed!==report.total)process.exitCode=1;
}finally{await browser.close();await new Promise(r=>server.close(r))}
})().catch(e=>{console.error(e);process.exitCode=1;server.close()});
