/* ANESVET V17.14.6 — Production Validation Center
   Non-clinical real-device qualification evidence only.
   Does not alter clinical calculations, thresholds, medication semantics, or patient records. */
(function(root){
'use strict';

const FALLBACK_VERSION='17.14.6';
const runtimeVersion=()=>root.AnesvetApp?.version||FALLBACK_VERSION;
const RUNS_KEY='anesvet_v16_19_1_validation_runs';
const ACTIVE_KEY='anesvet_v16_19_1_active_validation_run';
const DEVICE_LABEL_KEY='anesvet_v16_19_1_validation_device_label';
const MAX_RUNS=30;
const EVIDENCE_TARGET=20;

const STEPS=Object.freeze([
  {id:'readiness',title:'1. Device readiness baseline',detail:'Run storage / IndexedDB / PWA / viewport / recovery-copy readiness before the workflow test.',required:true,auto:'readiness'},
  {id:'case-resume',title:'2. Active case save → leave → resume',detail:'Create a disposable test case, save it, leave the screen/app, return, and confirm phase + recent documentation remain correct.',required:true},
  {id:'or-live',title:'3. OR LIVE repeated documentation',detail:'Record repeated Fast Vitals plus at least one event/milestone; confirm timestamps/order and recent activity remain correct.',required:true},
  {id:'medication',title:'4. Medication documentation',detail:'Document at least one planned/actual medication and confirm it is not marked GIVEN until explicitly confirmed.',required:true},
  {id:'background',title:'5. Screen lock / background ≥ 5 min',detail:'Background or lock the device for at least 5 minutes during the test case, then resume and verify timer/state/data.',required:true},
  {id:'force-reopen',title:'6. Force-close → reopen',detail:'Force-close the installed app/browser during a saved mutable test case, reopen, and verify recent data recovers.',required:true},
  {id:'offline',title:'7. Offline documentation → reconnect',detail:'Disable network, continue local documentation, reconnect, and confirm no clinical entry disappears.',required:true},
  {id:'recovery',title:'8. Recovery → handoff → complete',detail:'Enter Recovery, add serial records/medication review/handoff, and complete the Recovery workflow.',required:true},
  {id:'final-archive',title:'9. Final Lock → Archive VERIFIED',detail:'Complete reconciliation/sign-off, Final Lock the test record, and confirm Final Archive Assurance reports VERIFIED.',required:true},
  {id:'backup',title:'10. Schema-3 backup → verify file',detail:'Create a Full Backup and verify that exact downloaded JSON with Data Safety 2.0. Record off-device copy when actually copied.',required:true},
  {id:'restore',title:'11. Restore drill in disposable profile',detail:'Restore the verified backup in a disposable/test profile and confirm post-restore verification plus reopen.',required:true},
  {id:'ui-endurance',title:'12. Orientation / keyboard / endurance',detail:'Test portrait + landscape + soft keyboard and keep a simulated case active long enough to exercise normal sleep/task switching.',required:true}
]);

let adapter={};
let started=false;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function readJson(key,fallback){try{const v=JSON.parse(localStorage.getItem(key)||'null');return v??fallback}catch(_){return fallback}}
function writeJson(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true}catch(_){return false}}
function now(){return Date.now()}
function uid(){return `VR-${new Date().toISOString().replace(/[-:TZ.]/g,'').slice(0,14)}-${Math.random().toString(36).slice(2,7).toUpperCase()}`}
function fmt(epoch){if(!epoch)return '—';try{return new Date(epoch).toLocaleString()}catch(_){return String(epoch)}}
function runs(){const r=readJson(RUNS_KEY,[]);return Array.isArray(r)?r.slice(0,MAX_RUNS):[]}
function saveRuns(rows){return writeJson(RUNS_KEY,(rows||[]).slice(0,MAX_RUNS))}
function activeRun(){const r=readJson(ACTIVE_KEY,null);return r&&r.version===runtimeVersion()?r:null}
function saveActive(r){if(r)return writeJson(ACTIVE_KEY,r);try{localStorage.removeItem(ACTIVE_KEY);return true}catch(_){return false}}
function deviceLabel(){try{return String(localStorage.getItem(DEVICE_LABEL_KEY)||'').slice(0,80)}catch(_){return''}}
function setDeviceLabel(v){try{localStorage.setItem(DEVICE_LABEL_KEY,String(v||'').trim().slice(0,80))}catch(_){}}
function device(){let standalone=false;try{standalone=root.matchMedia?.('(display-mode: standalone)')?.matches||navigator.standalone===true}catch(_){ }
  return{platform:navigator.userAgentData?.platform||navigator.platform||'',userAgent:navigator.userAgent||'',screen:`${root.screen?.width||0}x${root.screen?.height||0}`,viewport:`${root.innerWidth||0}x${root.innerHeight||0}`,touchPoints:navigator.maxTouchPoints||0,standalone,language:navigator.language||'',timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||''};
}
function deviceSignature(d=device()){return [d.platform,d.screen,d.touchPoints,d.standalone?'PWA':'BROWSER'].join('|')}
function runtimeErrors(){try{return adapter.getRuntimeErrors?.()||[]}catch(_){return[]}}
function stateMeta(){let s={};try{s=adapter.getState?.()||root.AnesvetApp?.getState?.()||{}}catch(_){ }
  const active=!!(s?.patientSaved||s?.caseStartedAt||s?.timer?.running||(s?.records||[]).length||(s?.events||[]).length||(s?.drugAdministrations||[]).length);
  return{active,patientSaved:!!s?.patientSaved,phase:s?.casePhase||'preop',locked:!!s?.caseLocked,timerRunning:!!s?.timer?.running,recordCount:(s?.records||[]).length,eventCount:(s?.events||[]).length,drugCount:(s?.drugAdministrations||[]).length,lastSavedAgeMs:s?.lastSavedAt?Math.max(0,now()-Number(s.lastSavedAt)):null};
}
async function evidence(){
  const meta=stateMeta();let finalArchive=null,dataSafety=null,pilot=null,protocolGovernance=null,security=null;
  try{if(meta.locked)finalArchive=await adapter.verifyFinalArchive?.()}catch(e){finalArchive={ok:false,status:'ERROR',message:e?.message||String(e)}}
  try{dataSafety=adapter.dataSafety?.()||root.AnesvetDataBridge?.dataSafetySnapshot?.()||null}catch(_){ }
  try{pilot=root.ANESVET_PRODUCTION_PILOT?.snapshot?.()||null}catch(_){ }
  try{const g=root.ANESVET_HOSPITAL_PROTOCOL_GOVERNANCE?.summary?.()||null;if(g)protocolGovernance={managed:!!g.managed,activePublishedVersion:g.activePublished?.version||'',workingStatus:g.working?.status||'',workingVersion:g.working?.version||''}}catch(_){ }
  try{const q=root.ANESVET_SECURITY_BASELINE?.snapshot?.()||null;if(q)security={enabled:!!q.enabled,locked:!!q.locked,staffCount:q.staffCount||0,activeRole:q.activeIdentity?.role||''}}catch(_){ }
  return{capturedAt:now(),online:navigator.onLine!==false,visibility:document.visibilityState||'',viewport:`${root.innerWidth||0}x${root.innerHeight||0}`,case:meta,runtimeErrorCount:runtimeErrors().length,finalArchive:finalArchive?{ok:finalArchive.ok===true||finalArchive.status==='VERIFIED',status:finalArchive.status||'',message:finalArchive.message||''}:null,dataSafety:dataSafety?{historyCount:(dataSafety.history||[]).length,hasFullyVerifiedFile:!!dataSafety.verified,hasOffDeviceReceipt:!!dataSafety.external,lastRestoreOk:!!dataSafety.lastRestore?.verification?.ok,lastRestoreLevel:dataSafety.lastRestore?.verification?.level||''}:null,pilot:pilot?{requiredPass:pilot.acceptanceSummary?.requiredPass||0,required:pilot.acceptanceSummary?.required||0,readinessFail:pilot.readiness?.levels?.fail||0,readinessWarn:pilot.readiness?.levels?.warn||0}:null,protocolGovernance,security};
}
function emptySteps(){const o={};for(const s of STEPS)o[s.id]={status:'not-run',note:'',updatedAt:0,evidence:null};return o}
function runResult(r){const required=STEPS.filter(s=>s.required),rows=required.map(s=>r.steps?.[s.id]?.status||'not-run');if(rows.includes('fail'))return'FAIL';if(rows.includes('blocked'))return'BLOCKED';if(rows.every(x=>x==='pass'))return'PASS';return'INCOMPLETE'}
function historySummary(){const rows=runs(),sig=deviceSignature(),label=deviceLabel();const same=rows.filter(r=>r.version===runtimeVersion()&&r.deviceSignature===sig&&(!label||r.deviceLabel===label));let consecutive=0;for(const r of same){if(r.result==='PASS')consecutive++;else break}return{total:rows.length,sameDevice:same.length,pass:same.filter(r=>r.result==='PASS').length,consecutivePass:consecutive,target:EVIDENCE_TARGET,targetMet:consecutive>=EVIDENCE_TARGET,latest:same[0]||null}}
async function startRun(){if(activeRun()){adapter.toast?.('A validation run is already active');return activeRun()}const label=$('validationDeviceLabel')?.value.trim()||deviceLabel()||'';setDeviceLabel(label);let readiness=null;try{readiness=await root.ANESVET_PRODUCTION_PILOT?.runReadiness?.({announce:false})||null}catch(_){ }
  const r={format:'ANESVET_VALIDATION_RUN_V1',version:runtimeVersion(),runId:uid(),deviceLabel:label,deviceSignature:deviceSignature(),device:device(),startedAt:now(),completedAt:0,result:'INCOMPLETE',runtimeErrorsAtStart:runtimeErrors().length,readinessAtStart:readiness,steps:emptySteps(),events:[]};
  if(readiness){r.steps.readiness={status:(readiness.levels?.fail||0)===0?'pass':'fail',note:(readiness.levels?.fail||0)===0?`Automated readiness: ${readiness.levels?.pass||0} pass / ${readiness.levels?.warn||0} warn`:`Automated readiness: ${readiness.levels?.fail||0} hard failure(s)`,updatedAt:now(),evidence:await evidence()}}
  r.events.push({epoch:now(),type:'run-started'});saveActive(r);render();adapter.toast?.(`Validation run started • ${r.runId}`);return r}
async function updateStep(id,status,note){const r=activeRun();if(!r||!STEPS.some(s=>s.id===id))return;const allowed=['not-run','pass','fail','blocked'];if(!allowed.includes(status))return;r.steps[id]={status,note:String(note ?? r.steps[id]?.note ?? '').slice(0,500),updatedAt:now(),evidence:status==='not-run'?null:await evidence()};r.events=(r.events||[]).concat({epoch:now(),type:'step-updated',step:id,status}).slice(-100);r.result=runResult(r);saveActive(r);render()}
async function captureStep(id){const r=activeRun();if(!r)return;const row=r.steps[id]||{status:'not-run',note:'',updatedAt:0};row.evidence=await evidence();row.updatedAt=now();r.steps[id]=row;r.events=(r.events||[]).concat({epoch:now(),type:'evidence-captured',step:id}).slice(-100);saveActive(r);render();adapter.toast?.('Technical evidence captured')}
async function completeRun(){const r=activeRun();if(!r){adapter.toast?.('No active validation run');return null}r.completedAt=now();r.runtimeErrorsAtEnd=runtimeErrors().length;r.result=runResult(r);r.completionEvidence=await evidence();r.events=(r.events||[]).concat({epoch:now(),type:'run-completed',result:r.result}).slice(-100);const rows=runs();rows.unshift(r);saveRuns(rows);saveActive(null);render();adapter.toast?.(`Validation run ${r.result}`);return r}
function abortRun(){const r=activeRun();if(!r)return;if(root.confirm&&!root.confirm('Abort this validation run? Clinical data will not be changed.'))return;r.completedAt=now();r.result='ABORTED';r.events=(r.events||[]).concat({epoch:now(),type:'run-aborted'}).slice(-100);const rows=runs();rows.unshift(r);saveRuns(rows);saveActive(null);render();adapter.toast?.('Validation run aborted')}
function safeReport(){const r=activeRun(),h=historySummary();return{format:'ANESVET_PRODUCTION_VALIDATION_V1',version:runtimeVersion(),generatedAt:new Date().toISOString(),deviceLabel:deviceLabel(),deviceSignature:deviceSignature(),device:device(),activeRun:r,historySummary:h,recentRuns:runs().slice(0,20).map(x=>({runId:x.runId,version:x.version,deviceLabel:x.deviceLabel,deviceSignature:x.deviceSignature,startedAt:x.startedAt,completedAt:x.completedAt,result:x.result,runtimeErrorsAtStart:x.runtimeErrorsAtStart,runtimeErrorsAtEnd:x.runtimeErrorsAtEnd,steps:x.steps})),productionPilot:root.ANESVET_PRODUCTION_PILOT?.snapshot?.()||null};}
function download(name,payload){const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function exportReport(){download(`ANESVET_V${runtimeVersion()}_Production_Validation_${new Date().toISOString().slice(0,10)}.json`,safeReport());adapter.toast?.('Production validation report exported')}
function resetHistory(){if(root.confirm&&!root.confirm('Reset validation run history on this device?\n\nClinical case data will not be changed.'))return;try{localStorage.removeItem(RUNS_KEY);localStorage.removeItem(ACTIVE_KEY)}catch(_){ }render();adapter.toast?.('Validation history reset')}
function badgeClass(result){return result==='PASS'?'good':result==='FAIL'?'critical':result==='BLOCKED'?'warn':'neutral'}
function renderSteps(){const box=$('validationStepList'),r=activeRun();if(!box)return;if(!r){box.innerHTML='<div class="empty-state compact">Start a validation run. The run persists through app/browser reopen so force-close testing can continue.</div>';return}box.innerHTML=STEPS.map(s=>{const v=r.steps[s.id]||{};const evidenceText=v.evidence?`Evidence ${fmt(v.evidence.capturedAt)} • ${v.evidence.case?.phase||'—'} • ${v.evidence.case?.recordCount||0} vitals • ${v.evidence.runtimeErrorCount||0} runtime errors`:'No evidence captured yet';return `<article class="validation-step ${esc(v.status||'not-run')}"><div class="validation-step-main"><b>${esc(s.title)}</b><small>${esc(s.detail)}</small><span>${esc(evidenceText)}</span></div><div class="validation-step-actions"><select data-validation-status="${esc(s.id)}"><option value="not-run"${v.status==='not-run'?' selected':''}>Not run</option><option value="pass"${v.status==='pass'?' selected':''}>PASS</option><option value="fail"${v.status==='fail'?' selected':''}>FAIL</option><option value="blocked"${v.status==='blocked'?' selected':''}>BLOCKED</option></select><button class="btn light" type="button" data-validation-evidence="${esc(s.id)}">Capture evidence</button></div><input data-validation-note="${esc(s.id)}" maxlength="500" value="${esc(v.note||'')}" placeholder="Observation / bug reference / device note"></article>`}).join('');box.querySelectorAll('[data-validation-status]').forEach(el=>el.addEventListener('change',()=>{const note=[...box.querySelectorAll('[data-validation-note]')].find(x=>x.dataset.validationNote===el.dataset.validationStatus)?.value||'';updateStep(el.dataset.validationStatus,el.value,note)}));box.querySelectorAll('[data-validation-note]').forEach(el=>el.addEventListener('change',()=>updateStep(el.dataset.validationNote,r.steps[el.dataset.validationNote]?.status||'not-run',el.value.trim())));box.querySelectorAll('[data-validation-evidence]').forEach(el=>el.addEventListener('click',()=>captureStep(el.dataset.validationEvidence)))}
function renderHistory(){const box=$('validationHistoryList');if(!box)return;const rows=runs().slice(0,10);box.innerHTML=rows.length?rows.map(r=>`<div class="validation-history-row"><div><b>${esc(r.runId)}</b><small>${esc(fmt(r.completedAt||r.startedAt))} • ${esc(r.deviceLabel||'Unnamed device')}</small></div><span class="status-pill ${badgeClass(r.result)}">${esc(r.result)}</span></div>`).join(''):'<div class="empty-state compact">No completed validation runs on this device.</div>'}
function renderSummary(){const r=activeRun(),h=historySummary(),badge=$('validationCenterBadge'),target=$('validationEvidenceTarget');if(badge){badge.textContent=r?`RUN ${r.result}`:(h.latest?`LAST ${h.latest.result}`:'NOT RUN');badge.className=`status-pill ${badgeClass(r?.result||h.latest?.result||'')}`}if(target){target.textContent=`${Math.min(h.consecutivePass,h.target)}/${h.target} consecutive PASS`;target.className=`status-pill ${h.targetMet?'good':'neutral'}`}if($('validationDeviceLabel')&&!$('validationDeviceLabel').matches(':focus'))$('validationDeviceLabel').value=deviceLabel();if($('validationRunMeta'))$('validationRunMeta').textContent=r?`${r.runId} • started ${fmt(r.startedAt)} • ${STEPS.filter(s=>r.steps[s.id]?.status==='pass').length}/${STEPS.filter(s=>s.required).length} required steps passed • current result ${runResult(r)}`:`V${runtimeVersion()} • ${h.sameDevice} completed run(s) on this build/device signature • ${h.consecutivePass} consecutive PASS • target ${h.target} evidence runs.`;if($('validationStartRunBtn'))$('validationStartRunBtn').disabled=!!r;if($('validationCompleteRunBtn'))$('validationCompleteRunBtn').disabled=!r;if($('validationAbortRunBtn'))$('validationAbortRunBtn').disabled=!r}
function render(){renderSummary();renderSteps();renderHistory()}
function bind(){if(started)return;started=true;$('validationDeviceLabel')?.addEventListener('change',e=>{setDeviceLabel(e.target.value);render()});$('validationStartRunBtn')?.addEventListener('click',startRun);$('validationCompleteRunBtn')?.addEventListener('click',completeRun);$('validationAbortRunBtn')?.addEventListener('click',abortRun);$('validationExportBtn')?.addEventListener('click',exportReport);$('validationResetBtn')?.addEventListener('click',resetHistory);root.addEventListener('online',render);root.addEventListener('offline',render);document.addEventListener('visibilitychange',()=>{if(!document.hidden)render()});render()}
function init(options={}){adapter={...adapter,...options};bind();return api}
const api=Object.freeze({get version(){return runtimeVersion()},steps:STEPS,evidenceTarget:EVIDENCE_TARGET,init,render,startRun,completeRun,abortRun,updateStep,captureStep,activeRun,runs,historySummary,snapshot:safeReport,exportReport});
root.ANESVET_VALIDATION_CENTER=api;
if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:this);
