/** Real Chromium + HTTP origin + native storage. This runner must execute on a host with Chromium installed. */
import {chromium} from 'playwright';import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';
const root=path.resolve(path.dirname(new URL(import.meta.url).pathname),'..');
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.webmanifest':'application/manifest+json','.png':'image/png'};
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost'),name=url.pathname==='/'?'/index.html':decodeURIComponent(url.pathname),file=path.resolve(root,'.'+name);if(!file.startsWith(root+path.sep)){res.writeHead(403);res.end();return}try{res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file))}catch{res.writeHead(404);res.end('Not found')}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`,results=[];let browser;
try{
 browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_BIN?{executablePath:process.env.CHROMIUM_BIN}:{})});
 for(const viewport of [{width:1440,height:1000},{width:390,height:844}]){
  const context=await browser.newContext({viewport}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept(d.type()==='prompt'?'TEST reason':undefined));
  const click=s=>page.locator(s).click(),fill=(id,v)=>page.locator('#'+id).fill(String(v)),state=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('anesvet_v14_3_current'))),waitState=fn=>page.waitForFunction(fn),blur=()=>page.locator('body').click({position:{x:2,y:2}});
  const more=async tab=>{await click('#moreMenuBtn');await click(`[data-more-tab="${tab}"]`)};
  const edit=async scope=>{await click(scope==='hospital'?'#editHospitalAlertBtn':'#editCaseAlertBtn');await fill('alertProtocolActor','Dr E2E');await fill('alertProtocolReason','TEST audited protocol change')};
  await page.goto(base);await page.locator('#patient.active').waitFor();await fill('patientName','E2E V14.7');await page.selectOption('#species','dog');await fill('weight',12.5);await page.selectOption('#bcs','5');await click('.asa-card[data-asa="II"]');await fill('anesthetist','Dr E2E');await fill('surgeon','Dr Surgeon');await click('#savePatientBtn');await waitState(()=>JSON.parse(localStorage.getItem('anesvet_v14_3_current')).patientSaved);
  await more('settings');await page.locator('#settingCriticalPopup').uncheck();await click('#saveSettingsBtn');await edit('hospital');await fill('alert_map_warningLow',72);await fill('alert_map_criticalLow',62);await click('#saveAlertProtocolBtn');await click('[data-tab="orlive"]');await click('#orStartBtn');await waitState(()=>!!JSON.parse(localStorage.getItem('anesvet_v14_3_current')).caseStartedAt);assert.equal((await state()).protocolSnapshot.alertProtocol.map.criticalLow,62);
  await fill('orMap',68);await blur();await waitState(()=>JSON.parse(localStorage.getItem('anesvet_v14_3_current')).alertEpisodes.some(e=>!e.resolvedAt&&e.level==='warn'));await click('#orProblemPanel [data-problem-action="ack"]');await click('#saveProblemActionBtn');assert.ok((await state()).alertEpisodes[0].acknowledgedAt);await fill('orMap',55);await blur();await waitState(()=>JSON.parse(localStorage.getItem('anesvet_v14_3_current')).alertEpisodes[0].level==='danger');assert.equal((await state()).alertEpisodes[0].acknowledgedAt,null);await click('#orProblemPanel [data-problem-action="intervention"]');await fill('problemActionNote','TEST reassessment documented');await click('#saveProblemActionBtn');
  await fill('orMap','');await blur();assert.ok(!(await state()).alertEpisodes[0].resolvedAt);await fill('orMap',75);await fill('orSpo2',98);await fill('orEtco2',45);await fill('orTemp',38);await fill('orHr',100);await fill('orRr',12);await blur();await click('#orRecordNowBtn');assert.equal((await state()).records.length,1);
  await edit('case');await fill('alert_map_warningLow',68);await fill('alert_map_criticalLow',58);await click('#saveAlertProtocolBtn');assert.equal((await state()).alertProtocolHistory.length,1);assert.equal((await state()).records[0].alertProtocol.map.criticalLow,62);
  await more('settings');await fill('settingPropofolDose',2);await fill('settingPropofolConc',20);await click('#saveSettingsBtn');await click('[data-tab="orlive"]');await click('#orOpenDrugBtn');await page.selectOption('#orQuickDrugSelect','1');assert.equal(await page.inputValue('#orQuickDrugActual'),'');assert.match(await page.textContent('#orQuickDrugCalculation'),/5 mL/);await click('#orQuickDrugSaveBtn');assert.equal((await state()).drugAdministrations.length,0);await fill('orQuickDrugActual',1.5);await fill('orQuickDrugRoute','IV');await fill('orQuickDrugBy','Dr E2E');await click('#orQuickDrugSaveBtn');await page.locator('#orQuickDrugDialog').waitFor({state:'hidden'});assert.equal((await state()).drugAdministrations[0].calculationBasis.calculatedMl,5);assert.equal(await page.locator('#orlive.active').count(),1);
  fs.mkdirSync(path.join(root,'tests/artifacts'),{recursive:true});await page.screenshot({path:path.join(root,`tests/artifacts/or-live-${viewport.width}.png`),fullPage:true});await click('.or-milestone[data-label="Extubation"]');await page.locator('#recovery.active').waitFor();let s=await state();assert.equal(s.recoveryHandoffs.length,1);assert.ok(s.extubatedAt);assert.equal(s.recoveryHandoffs[0].administrations[0].actual,1.5);await page.reload();await page.locator('#recovery.active').waitFor();assert.equal((await state()).recoveryHandoffs.length,1);
  await fill('recHR',100);await fill('recRR',12);await fill('recMAP',75);await fill('recSpO2',98);await fill('recTemp',38);await click('#recordRecoveryVitalsBtn');assert.equal((await state()).recoveryRecords.length,1);await click('#emergencyReturnOrBtn');await page.locator('#orlive.active').waitFor();await click('#orBeginRecoveryBtn');assert.equal((await state()).recoveryHandoffs.length,2);
  await click('#moreMenuBtn');await click('.advanced-menu summary');await click('[data-more-tab="dashboard"]');await page.locator('#dashboard.active').waitFor();
  // Native service worker/cache smoke; this is not an upgrade-from-V14.6.4 proof.
  await page.evaluate(()=>navigator.serviceWorker.ready);assert.ok((await page.evaluate(()=>caches.keys())).some(k=>k==='anesvet-v14-7-or-live-clinical-workflow'));await context.setOffline(true);await page.reload();await page.locator('#recovery.active').waitFor();assert.equal((await state()).drugAdministrations.length,1);await context.setOffline(false);assert.deepEqual(errors,[]);results.push({viewport,status:'PASS'});await context.close();
 }
 console.log('Real Chromium browser E2E: PASS',JSON.stringify(results));
}catch(e){console.error('Browser E2E did not pass:',e.message);process.exitCode=1}finally{await browser?.close();await new Promise(r=>server.close(r))}
