import assert from 'node:assert/strict';import {createDomApp,setupPatient} from './dom_harness.mjs';let n=0;const eq=(a,b,m)=>{assert.deepEqual(a,b,m);n++},ok=(a,m)=>{assert.ok(a,m);n++};
const a=await createDomApp();try{
 await setupPatient(a);a.set('settingCriticalPopup',false);await a.click('saveSettingsBtn');await a.click('orStartBtn');a.set('orMap',55);await a.settle();await a.click('orRecordNowBtn');await a.click('orBeginRecoveryBtn');await a.click('signAnesthetistBtn');await a.click('signSurgeonBtn');for(const id of ['endConfirmRecovery','endConfirmRecord','endConfirmDrugs','endConfirmPdf'])a.set(id,true);await a.click('endSaveArchiveBtn');ok(!a.state().caseLocked,'unresolved episode prevents final lock');
 a.w.document.querySelector('#recoveryProblemPanel [data-problem-action="resolve"]').click();a.set('problemActionActor','Dr Test');a.set('problemActionNote','TEST verified outcome');await a.click('saveProblemActionBtn');
 // Hold only the post-archive reset so the sealed current payload can be inspected.
 const nativeTimeout=a.w.setTimeout;a.w.setTimeout=(fn,delay,...args)=>delay===350?0:nativeTimeout(fn,delay,...args);await a.click('endSaveArchiveBtn');await a.settle();const sealed=a.state();ok(sealed.caseLocked,'lock must persist before reset');ok(sealed.finalChecksum);eq(await a.api.computeCaseChecksum(sealed),sealed.finalChecksum);const archived=a.api.getArchive().find(c=>c.caseId===sealed.caseId);ok(archived?.caseLocked);eq(await a.api.computeCaseChecksum(archived),sealed.finalChecksum);eq((await a.api.verifyBackupPayloadIntegrity({current:sealed,archive:[archived]})).valid,2);
 a.api.buildPdfReport();ok(a.el('reportRecoveryHandoff').textContent.includes('Recovery Handoff Summary'));const bytes=a.w.localStorage.getItem('anesvet_v14_3_current');a.el('weight').value='999';a.api.save();eq(a.w.localStorage.getItem('anesvet_v14_3_current'),bytes,'ordinary autosave cannot alter sealed payload');eq(a.errors,[]);
}finally{a.close()}
console.log(`Final lock / archive / report integrity: PASS (${n} assertions)`);
