import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=path.resolve(path.dirname(new URL(import.meta.url).pathname),'..');
const app=fs.readFileSync(path.join(root,'app.js'),'utf8');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const css=fs.readFileSync(path.join(root,'style.css'),'utf8');
const manifest=JSON.parse(fs.readFileSync(path.join(root,'manifest.webmanifest'),'utf8'));
const ids=[...html.matchAll(/\sid="([^"]+)"/g)].map(m=>m[1]);
const must=(c,m)=>assert.ok(c,m);
for(const id of ['orStickyPatient','orMobileDock','orMobileNextBtn','orMobileRecordBtn','orMobileDrugBtn','orMobileFluidBtn','orMobileEventBtn','connectivityState'])must(ids.includes(id),`missing V14.9 mobile control ${id}`);
must(html.includes('viewport-fit=cover'),'safe-area viewport support missing');
must(html.includes('apple-mobile-web-app-capable'),'iOS standalone support missing');
must(css.includes('env(safe-area-inset-bottom)')&&css.includes('.or-mobile-dock'),'mobile OR dock must honor device safe area');
must(css.includes('body.or-mobile-active')&&app.includes("classList.toggle('or-mobile-active',id==='orlive')"),'bottom safe-area spacing must only apply in OR LIVE');
must(css.includes('.or-sticky-mini>div:nth-child(3){display:block}'),'mobile sticky bar must preserve case time after V14.7 responsive rules');
must(css.includes('@media(orientation:landscape) and (min-width:768px) and (max-width:1180px)'),'iPad landscape optimization missing');
must(app.includes("const AUTOSAVE_DELAY_MS=450")&&app.includes('function scheduleAutosave()'),'debounced autosave missing');
must(app.includes("let saveUiMode='saved'")&&app.includes('mode=mode||saveUiMode'),'timer rerenders must not falsely overwrite dirty/save-failed state');
must(app.includes('ACTIVE_CHECKPOINT_MS=15000')&&app.includes('startActiveCheckpoint()'),'active-case checkpoint missing');
must(app.includes('Local save verification failed'),'local save read-after-write verification missing');
must(app.includes("window.addEventListener('online',renderConnectivityState)")&&app.includes("window.addEventListener('offline',renderConnectivityState)"),'offline/local-first status missing');
must(app.includes("requestScreenWakeLock(true)")&&app.includes('autoWakeEnabled()'),'OR wake-lock behavior missing');
must(app.includes("$('orMobileRecordBtn')?.addEventListener")&&app.includes("$('orMobileDrugBtn')?.addEventListener"),'mobile dock actions not bound');
must(manifest.start_url.includes('15.0.0'),'manifest release version mismatch');
console.log('ANESVET V14.9 mobile/iPad OR reliability compatibility contracts on V15.0.0: PASS');
