/* ANESVET V17.13.3 — canonical workspace disclosure/focus coordinator.
 * Consolidates global workflow status, mobile continue, and Settings disclosure.
 * Presentation only; never marks clinical items complete. */
(function(root){
'use strict';
const VERSION='17.13.3',$=id=>document.getElementById(id),q=(sel,scope=document)=>scope?.querySelector?.(sel)||null,qa=(sel,scope=document)=>[...(scope?.querySelectorAll?.(sel)||[])],MAIN_FLOW=['patient','preop','drugs','orlive','recovery','endcase'];
let mobilePending=false;
const isGood=el=>!!el&&el.classList.contains('good');

/* Settings-only progressive disclosure. Patient/Pre-op/Drug/Recovery are owned elsewhere. */
const SETTINGS_STORE='anesvet_pd_state_v1',settingsState=(()=>{try{return JSON.parse(localStorage.getItem(SETTINGS_STORE)||'{}')||{}}catch(_){return{}}})(),settingsEnhanced=new Map();
const saveSettingsState=()=>{try{localStorage.setItem(SETTINGS_STORE,JSON.stringify(settingsState))}catch(_){}};
const slug=text=>String(text||'section').trim().toLowerCase().replace(/[^a-z0-9\u0E00-\u0E7F]+/g,'-').replace(/^-+|-+$/g,'').slice(0,70)||'section';
function directHeading(panel){return Array.from(panel?.children||[]).find(el=>el.classList?.contains('section-heading'))||null}
function panelTitle(panel){return panel?.querySelector?.(':scope > .section-heading h2, :scope > .section-heading h3, :scope > h2, :scope > h3')?.textContent?.trim()||'Section'}
function settingsSetOpen(panel,open,persist=true){const meta=settingsEnhanced.get(panel);if(!meta)return;panel.classList.toggle('pd-open',!!open);panel.classList.toggle('pd-collapsed',!open);meta.toggle.setAttribute('aria-expanded',String(!!open));meta.toggle.setAttribute('aria-label',`${open?'พับ':'เปิด'} ${meta.title}`);const label=meta.toggle.querySelector('.pd-toggle-label');if(label)label.textContent=open?'พับ':'เปิด';if(persist){settingsState[meta.key]=!!open;saveSettingsState()}}
function enhanceSettingsPanel(panel,index){if(!panel||panel.classList.contains('pd-enhanced'))return;const heading=directHeading(panel);if(!heading)return;const title=panelTitle(panel),key=`settings:${slug(title)}:${index}`,summary=document.createElement('div');summary.className='pd-summary';summary.textContent='แตะเพื่อเปิดรายละเอียดเมื่อจำเป็น';const toggle=document.createElement('button');toggle.type='button';toggle.className='pd-toggle session-safe';toggle.innerHTML='<span class="pd-toggle-label">เปิด</span><span class="pd-toggle-icon" aria-hidden="true">⌄</span>';heading.appendChild(toggle);heading.insertAdjacentElement('afterend',summary);panel.classList.add('pd-panel','pd-enhanced');panel.dataset.pdKey=key;settingsEnhanced.set(panel,{key,title,toggle});settingsSetOpen(panel,Object.prototype.hasOwnProperty.call(settingsState,key)?!!settingsState[key]:false,false);toggle.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();settingsSetOpen(panel,panel.classList.contains('pd-collapsed'))});heading.addEventListener('click',e=>{if(e.target.closest('button,input,select,textarea,a,label,summary'))return;settingsSetOpen(panel,panel.classList.contains('pd-collapsed'))})}
function setupSettingsDisclosure(){const settings=$('settings');if(!settings)return;qa(':scope > section.panel',settings).forEach(enhanceSettingsPanel);if(settings.querySelector('.pd-settings-toolbar'))return;const bar=document.createElement('div');bar.className='pd-settings-toolbar';bar.innerHTML='<div class="pd-settings-toolbar-copy"><b>Settings แบบย่อ</b><small>เปิดเฉพาะหัวข้อที่ต้องการแก้ เพื่อลดการเลื่อนบนมือถือ</small></div><div class="pd-settings-tools"><input id="pdSettingsSearch" class="pd-settings-search" type="search" placeholder="ค้นหา เช่น logo, Drug Library, alert" autocomplete="off"><button id="pdSettingsCollapseAll" class="btn" type="button">พับทั้งหมด</button><button id="pdSettingsExpandAll" class="btn" type="button">เปิดทั้งหมด</button><span id="pdSettingsCount" class="pd-settings-count"></span></div>';settings.insertBefore(bar,settings.firstChild);const panels=()=>qa(':scope > section.panel.pd-enhanced',settings),search=$('pdSettingsSearch'),count=$('pdSettingsCount'),updateCount=()=>{if(count)count.textContent=`${panels().filter(p=>!p.hidden).length}/${panels().length} หมวด`};$('pdSettingsCollapseAll')?.addEventListener('click',()=>panels().filter(p=>!p.hidden).forEach(p=>settingsSetOpen(p,false)));$('pdSettingsExpandAll')?.addEventListener('click',()=>panels().filter(p=>!p.hidden).forEach(p=>settingsSetOpen(p,true)));search?.addEventListener('input',()=>{const term=search.value.trim().toLowerCase();panels().forEach(panel=>{const match=!term||`${panelTitle(panel)} ${panel.textContent}`.toLowerCase().includes(term);panel.hidden=!match;if(term&&match)settingsSetOpen(panel,true,false);panel.dataset.pdHighlight=term&&match?'true':'false'});updateCount()});updateCount()}
function revealSettingsAncestor(target,persist=false){if(!target?.closest||target.closest('.section-heading'))return false;const panel=target.closest('#settings .pd-panel.pd-collapsed');if(panel){settingsSetOpen(panel,true,persist);return true}return false}

function openForElement(el,{persist=true,scroll=false}={}){if(!el)return false;try{if(el.closest?.('.patient-secondary-field'))root.ANESVET_PATIENT_PREOP_SIMPLIFICATION?.setDetails?.(true,persist)}catch(_){}try{root.ANESVET_RECOVERY_END_REFINEMENT?.openForElement?.(el,persist)}catch(_){}revealSettingsAncestor(el,persist);const summaryDetails=el.closest?.('summary')?.parentElement;let node=el.parentElement;while(node){if(node.tagName==='DETAILS'&&node!==summaryDetails&&!node.open)node.open=true;node=node.parentElement}if(scroll)requestAnimationFrame(()=>{if(root.ANESVET_MOBILE_OR_OWNER?.editing?.())return;el.scrollIntoView?.({behavior:'smooth',block:'nearest'})});return true}
function openWorkflowStatus(){const tracker=q('#orlive .or-phase-tracker-panel');if(!tracker)return false;tracker.classList.add('ux-phase-requested');if('open' in tracker)tracker.open=true;openForElement(tracker,{scroll:true});return true}

function syncWorkflow(){const body=document.body,wide=window.matchMedia('(min-width:1180px)').matches,tablet=window.matchMedia('(min-width:760px) and (max-width:1179px)').matches;document.documentElement.classList.toggle('ux-phone',window.matchMedia('(max-width:720px)').matches);body.classList.toggle('ux-wide-workspace',wide);body.classList.toggle('ux-tablet-workspace',tablet);body.dataset.uxViewport=wide?'wide':tablet?'tablet':'mobile';const workflow=q('.workflow-tabs'),tabs=qa('.tab[data-tab]',workflow),main=tabs.filter(x=>MAIN_FLOW.includes(x.dataset.tab)),active=tabs.find(x=>x.classList.contains('active')),activeMain=main.findIndex(x=>x.classList.contains('active'));tabs.forEach(x=>x.toggleAttribute('aria-current',x===active));main.forEach((btn,i)=>{const state=activeMain<0?'future':i<activeMain?'past':i===activeMain?'current':'future';btn.dataset.stepState=state;btn.setAttribute('aria-label',`${btn.textContent.trim()} • step ${i+1} of ${main.length}`)});if(active){active.setAttribute('aria-current','step');body.dataset.uxActiveTab=active.dataset.tab||''}if(active&&workflow&&window.matchMedia('(max-width:1180px), (pointer:coarse)').matches&&!body.classList.contains('or-mobile-active')&&!body.classList.contains('recovery-mobile-active')&&workflow.scrollWidth>workflow.clientWidth+1){const max=Math.max(0,workflow.scrollWidth-workflow.clientWidth),left=Math.max(0,Math.min(max,active.offsetLeft-(workflow.clientWidth-active.offsetWidth)/2));requestAnimationFrame(()=>{try{workflow.scrollTo({left,behavior:'auto'})}catch(_){workflow.scrollLeft=left}})}scheduleMobileRefresh()}
function syncViewport(){syncWorkflow()}

function activePageId(){return q('.tabpage.active')?.id||''}
function setTab(id){if(root.AnesvetApp?.setTab){root.AnesvetApp.setTab(id);return true}const btn=q(`.workflow-tabs .tab[data-tab="${id}"]`);if(btn){btn.click();return true}return false}
function mobileContinueSpec(){const current=activePageId();if(current==='patient'){if(!isGood($('patientSaveStatus')))return{label:'บันทึก & ต่อ',icon:'✓',run:()=>$('savePatientBtn')?.click()};return{label:'Pre-check',icon:'→',run:()=>setTab('preop')}}if(current==='preop'){if(!isGood($('preopProgress')))return{label:'รายการถัดไป',icon:'↓',run:()=>root.ANESVET_PATIENT_PREOP_SIMPLIFICATION?.preopNext?.()};return{label:'Medications',icon:'→',run:()=>setTab('drugs')}}if(current==='drugs'){const spec=root.ANESVET_DRUG_START_SIMPLIFICATION?.spec?.();if(spec)return{label:spec.label||'OR LIVE',icon:/review/i.test(spec.label||'')?'✓':/สร้าง/.test(spec.label||'')?'↻':'→',run:()=>spec.run?.()}}if(current==='endcase'){const next=$('endCaseNextTaskBtn');if(next)return{label:next.dataset.action==='finalize'?'Lock & Archive':'รายการถัดไป',icon:next.dataset.action==='finalize'?'✓':'→',run:()=>next.click()}}return null}
function mobileStatusData(id){if(id==='patient'){const el=$('patientSaveStatus');return{text:isGood(el)?'✓ SAVED':'ต้องบันทึก',tone:isGood(el)?'good':'warn'}}if(id==='preop'){const el=$('preopProgress'),text=el?.textContent?.trim()||'—';return{text:text.replace(' REVIEWED',''),tone:isGood(el)?'good':'warn'}}if(id==='drugs'){const p=root.ANESVET_DRUG_START_SIMPLIFICATION?.planState?.();return{text:p?.reviewed?'✓ Plan reviewed':'Plan ยังไม่ review',tone:p?.reviewed?'good':'muted'}}if(id==='orlive'||id==='recovery'){const src=q(`.workflow-tabs .tab[data-tab="${id}"]`),locked=src?.classList.contains('locked-step');if(id==='recovery'){const rs=root.ANESVET_RECOVERY_END_REFINEMENT?.recoveryUiState?.();if(rs?.complete)return{text:'✓ Complete',tone:'good'};if(rs?.active)return{text:`${rs.records} rec • ${rs.reviewed}/${rs.total}`,tone:rs.ready?'good':'warn'}}return{text:locked?'ยังล็อก':'พร้อมเปิด',tone:locked?'muted':'good'}}if(id==='endcase')return{text:'Final record',tone:'muted'};return{text:'',tone:'muted'}}
function refreshMobile(){mobilePending=false;const btn=$('mobileQuickContinueBtn'),bar=$('mobileQuickBar'),spec=mobileContinueSpec();if(btn&&bar){btn.hidden=!spec;bar.classList.toggle('has-continue',!!spec);if(spec){const icon=btn.querySelector('span'),label=btn.querySelector('b');if(icon)icon.textContent=spec.icon||'→';if(label)label.textContent=spec.label||'ต่อไป';btn.title=spec.label||'ต่อไป';btn.setAttribute('aria-label',spec.label||'ต่อไป')}}qa('[data-mobile-tab]').forEach(b=>{const id=b.dataset.mobileTab;if(!MAIN_FLOW.includes(id))return;let badge=b.querySelector('.mobile-step-status');if(!badge){badge=document.createElement('small');badge.className='mobile-step-status';b.appendChild(badge)}const st=mobileStatusData(id);badge.textContent=st.text;badge.dataset.tone=st.tone})}
function scheduleMobileRefresh(){if(mobilePending)return;mobilePending=true;requestAnimationFrame(refreshMobile)}

function setupMobileIdentityBridge(){const chip=$('securityIdentityChip'),workflow=$('mobileWorkflowDialog'),secondary=q('.mobile-workflow-secondary',workflow);if(!chip||!secondary||$('mobileIdentityBtn'))return;const btn=document.createElement('button');btn.id='mobileIdentityBtn';btn.type='button';btn.className='session-safe';btn.innerHTML='<span class="r27-identity-icon" aria-hidden="true">👤</span><span class="r27-identity-info"><b>ผู้ใช้งาน / Identity</b><small id="mobileIdentityStatus">กำลังโหลดสถานะ</small></span>';secondary.append(btn);btn.addEventListener('click',()=>{if(workflow?.open){try{workflow.close()}catch(_){workflow.removeAttribute('open')}}chip.click()});const sync=()=>{const raw=(chip.textContent||'').trim(),state=/locked/i.test(raw)?'locked':/off|unmanaged/i.test(raw)?'off':'active',label=state==='off'?'Identity ยังไม่เปิดใช้งาน':state==='locked'?'Identity ถูกล็อก':raw.replace(/^[^\p{L}\p{N}]*/u,'').trim()||'Identity';chip.dataset.securityState=state;chip.setAttribute('aria-label',`ผู้ใช้งาน / Identity: ${label}`);chip.setAttribute('title',`ผู้ใช้งาน / Identity: ${label}`);if($('mobileIdentityStatus'))$('mobileIdentityStatus').textContent=label;const icon=q('.r27-identity-icon',btn);if(icon)icon.textContent=state==='locked'?'🔒':state==='off'?'🔓':'👤'};new MutationObserver(sync).observe(chip,{childList:true,characterData:true,subtree:true});sync()}

function bind(){if(bind.done)return;bind.done=true;setupSettingsDisclosure();setupMobileIdentityBridge();document.addEventListener('focusin',e=>openForElement(e.target,{persist:false}),true);document.addEventListener('invalid',e=>openForElement(e.target,{persist:false}),true);document.addEventListener('anesvet:viewportchange',syncWorkflow);root.ANESVET_LIFECYCLE_COORDINATOR?.subscribe('pageshow',syncWorkflow);const workflow=q('.workflow-tabs');if(workflow)new MutationObserver(syncWorkflow).observe(workflow,{subtree:true,attributes:true,attributeFilter:['class']});$('mobileQuickContinueBtn')?.addEventListener('click',()=>mobileContinueSpec()?.run?.());$('mobileWorkflowMenuBtn')?.addEventListener('click',()=>setTimeout(refreshMobile,0));document.addEventListener('change',e=>{if(e.target.closest?.('#patient,#preop,#drugs,#recovery,#endcase'))scheduleMobileRefresh()},true);document.addEventListener('input',e=>{if(e.target.closest?.('#patient,#preop,#drugs,#recovery'))scheduleMobileRefresh()},true);document.addEventListener('click',e=>{if(e.target.closest?.('.workflow-tabs,#mobileWorkflowDialog,#mobileQuickBar,#patient,#preop,#drugs,#recovery,#endcase'))scheduleMobileRefresh()},true);const obs=new MutationObserver(scheduleMobileRefresh);['patientSaveStatus','preopProgress','caseDrugPlanStatus','caseDrugPlanList','recoveryPhaseBadge','recoveryReadiness','recoveryScoreCount','recoveryRecordCount','endCaseReadiness'].forEach(id=>{const el=$(id);if(el)obs.observe(el,{attributes:true,childList:true,characterData:true,subtree:true})});window.addEventListener('hashchange',()=>{const id=decodeURIComponent(location.hash.slice(1));if(id)openForElement($(id),{persist:false})});syncWorkflow();refreshMobile()}
const api=Object.freeze({version:VERSION,bind,openForElement,openWorkflowStatus,syncViewport,syncWorkflow,refreshMobile,setupSettingsDisclosure,setupMobileIdentityBridge,settingsSetOpen});root.ANESVET_WORKSPACE_OWNER=api;
/* Compatibility API for remaining legacy callers. */
root.ANESVETProgressiveDisclosure=Object.freeze({openForElement(el,persist=true){return revealSettingsAncestor(el,persist)},collapseSettings(){qa('#settings > .pd-panel').forEach(p=>settingsSetOpen(p,false))},expandSettings(){qa('#settings > .pd-panel').forEach(p=>settingsSetOpen(p,true))},owner:'workspace-owner-v17133'});
root.ANESVET_LIFECYCLE_COORDINATOR?.ready(bind);
})(window);
