'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict'),{chromium}=require('playwright');
const R=path.resolve(__dirname,'../..');let count=0;const check=(label,ok)=>{assert.ok(ok,label);console.log('PASS '+label);count++};
async function run(){const server=http.createServer((req,res)=>{const p=new URL(req.url,'http://local').pathname,f=path.join(R,p==='/'?'index.html':decodeURIComponent(p));if(!f.startsWith(R+path.sep)||!fs.existsSync(f)||!fs.statSync(f).isFile()){res.writeHead(404);res.end();return}res.setHeader('Content-Type',{'.html':'text/html','.js':'text/javascript','.css':'text/css'}[path.extname(f)]||'application/octet-stream');res.end(fs.readFileSync(f))});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true});try{for(const [width,height]of [[320,844],[360,844],[390,844],[1024,844],[844,390]]){
 const context=await browser.newContext({viewport:{width,height},hasTouch:true,isMobile:width<768}),page=await context.newPage(),errors=[];page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());const ck=(s,v)=>check(width+'x'+height+' '+s,v);
 await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>window.AnesvetApp?.version==='17.14.14'&&!document.body.classList.contains('av-booting'));
 await page.evaluate(()=>{for(const [id,v]of [['patientName','QA workflow layout'],['species','cat'],['weight','3'],['patientProcedure','QA'],['procedure','QA'],['asa','II'],['anesthetist','QA']])document.getElementById(id).value=v;const s=AnesvetApp.getState();s.patientSaved=true;s.caseStartedAt=Date.now();s.casePhase='setup';s.timer={elapsedMs:1000,running:true,startedEpoch:Date.now()};s.protocolSnapshot={version:'qa-synthetic',caseDrugPlan:[]};document.getElementById('reminderOn').checked=false;AnesvetApp.save();AnesvetApp.setTab('orlive',{force:true});ANESVET_OR_LIVE_INSTANCE.renderOrLive()});
 ck('a recently started case counts to its actual first record deadline',await page.locator('#orVitalsFocusDue').innerText().then(t=>/^first in 4:5\d$/.test(t)));
 async function geometry(label){const result=await page.evaluate(()=>{const card=document.querySelector('.or-primary-flow'),title=document.getElementById('orPrimaryActionTitle'),buttons=[...document.querySelectorAll('.or-primary-buttons>button')].filter(e=>e.checkVisibility({checkVisibilityCSS:true})),c=card.getBoundingClientRect(),t=title.getBoundingClientRect(),rs=buttons.map(e=>e.getBoundingClientRect());return {title:t.width>=240&&t.height<=48,below:rs.every(r=>r.top>=t.bottom&&r.left>=c.left&&r.right<=c.right),touch:rs.every(r=>r.height>=48),separate:rs.every((a,i)=>rs.every((b,j)=>i===j||!(a.left<b.right&&a.right>b.left&&a.top<b.bottom&&a.bottom>b.top))),complete:buttons.every(e=>e.scrollHeight<=e.clientHeight+1&&getComputedStyle(e).whiteSpace==='normal')}});ck(label+' heading has its own readable row',result.title);ck(label+' actions stay inside the card below the heading',result.below);ck(label+' native actions have complete text and at least 48 px touch targets',result.touch&&result.complete);ck(label+' action buttons do not overlap',result.separate)}
 for(const [action,milestone]of [['start-induction','Induction'],['airway','Intubation'],['surgery-start','Surgery start'],['surgery-end','Surgery end']]){
  await page.waitForFunction(a=>document.getElementById(document.getElementById('avContextWorkflow').dataset.nativeTarget)?.dataset.action===a,action);await page.locator('#avContextWorkflow').tap();if(await page.locator('#orStepConfirmDialog').isVisible())await page.locator('#orStepConfirmGoBtn').tap();await page.waitForFunction(name=>AnesvetApp.getState().events.some(e=>e.name===name),milestone);await page.waitForTimeout(100);ck(action+' stays reachable by real touch through the footer',await page.evaluate(name=>AnesvetApp.getState().events.filter(e=>e.name===name).length===1,milestone));await geometry(action);
 }
 ck('Surgery end retains the native Emergence and Extubation action',await page.locator('#orPrimaryActionTitle').innerText()==='Emergence'&&await page.locator('#orPrimaryActionBtn').getAttribute('data-action')==='extubation');
 const overdue=(21*60+18)*60000+44000;await page.evaluate(ms=>{const s=AnesvetApp.getState();s.caseStartedAt=Date.now()-ms;s.timer={elapsedMs:ms,running:false,startedEpoch:null};AnesvetApp.save();ANESVET_OR_LIVE_INSTANCE.renderOrLive()},overdue);
 ck('an old paused case displays overdue hours, minutes and seconds',await page.locator('#orVitalsFocusDue').innerText()==='FIRST DUE +21:13:44');
 ck('duration presentation retains the original timer value',await page.evaluate(ms=>AnesvetApp.getState().timer.elapsedMs===ms&&!AnesvetApp.getState().timer.running,overdue));
 // Reproduce the overlap with the fixed footer and check actual hit targets.
 await page.evaluate(()=>{const b=document.getElementById('orUndoStepBtn'),f=document.getElementById('avContextWorkflow');scrollBy({top:b.getBoundingClientRect().top-f.getBoundingClientRect().top,behavior:'instant'})});
 ck('inline Undo cannot intercept the footer workflow action',await page.locator('#avContextWorkflow').evaluate(e=>{const r=e.getBoundingClientRect();return e.contains(document.elementFromPoint(r.left+r.width/2,r.top+r.height/2))}));
 ck('inline Undo cannot intercept footer Save or navigation',await page.evaluate(()=>['avContextPrimary',...Array.from(document.querySelectorAll('#avBottom [data-av-nav]')).map(e=>e.id).filter(Boolean)].every(id=>{const e=document.getElementById(id),r=e.getBoundingClientRect();return e.contains(document.elementFromPoint(r.left+r.width/2,r.top+r.height/2))})));
 // Larger text is a reflow test; it does not emulate a physical keyboard.
 await page.evaluate(()=>{for(const e of document.querySelectorAll('#orPrimaryActionTitle,.or-primary-buttons>button'))e.style.setProperty('font-size',e.id==='orPrimaryActionTitle'?'24px':'20px','important')});await geometry('larger text');
 await page.locator('#orUndoStepBtn').evaluate(e=>e.scrollIntoView({block:'center',behavior:'instant'}));await page.locator('#orUndoStepBtn').tap();await page.waitForFunction(()=>AnesvetApp.getState().casePhase==='intraop');ck('responsive Undo still reverses Surgery end only',await page.evaluate(()=>AnesvetApp.getState().events.some(e=>e.name==='Surgery start')&&!AnesvetApp.getState().events.some(e=>e.name==='Surgery end')));
 await page.evaluate(()=>{for(const e of document.querySelectorAll('#orPrimaryActionTitle,.or-primary-buttons>button'))e.style.removeProperty('font-size')});await page.waitForFunction(()=>document.getElementById(document.getElementById('avContextWorkflow').dataset.nativeTarget)?.dataset.action==='surgery-end');await page.locator('#avContextWorkflow').tap();await page.locator('#orStepConfirmGoBtn').tap();await page.waitForFunction(()=>AnesvetApp.getState().casePhase==='emergence');
 await page.evaluate(ms=>{const s=AnesvetApp.getState();s.caseStartedAt=Date.now()-ms;s.timer={elapsedMs:ms,running:false,startedEpoch:null};AnesvetApp.save();ANESVET_OR_LIVE_INSTANCE.renderOrLive()},overdue);for(const [id,v]of [['orHr','120'],['orMap','80'],['orSpo2','98'],['orEtco2','38'],['orRr','18'],['orTemp','38']])await page.locator('#'+id).fill(v);await page.locator('#avContextPrimary').tap();await page.waitForFunction(()=>AnesvetApp.getState().records.length===1);
 ck('first Vitals save still records exactly one measured set',await page.evaluate(()=>AnesvetApp.getState().records[0].hr===120&&AnesvetApp.getState().records[0].map===80));ck('next due uses the newly saved record rather than total case age',await page.locator('#orVitalsFocusDue').innerText().then(t=>/^in 4:5\d$/.test(t)));
 await page.reload();await page.waitForFunction(()=>window.AnesvetApp?.version==='17.14.14'&&!document.body.classList.contains('av-booting'));ck('reload retains long elapsed time and the actual Vitals record',await page.evaluate(ms=>AnesvetApp.getState().timer.elapsedMs===ms&&AnesvetApp.getState().records.length===1,overdue));
 await page.waitForFunction(()=>document.getElementById('orPrimaryActionBtn').dataset.action==='extubation');await page.locator('#orPrimaryActionBtn').evaluate(e=>e.scrollIntoView({block:'center',behavior:'instant'}));await page.locator('#orPrimaryActionBtn').tap();ck('Extubation still requires the native confirmation',await page.locator('#orStepConfirmDialog').isVisible()&&await page.evaluate(()=>AnesvetApp.getState().casePhase==='emergence'));
 await page.locator('#orStepConfirmGoBtn').tap();await page.waitForFunction(()=>AnesvetApp.getState().casePhase==='recovery');ck('confirmed Extubation still enters Recovery with Vitals retained',await page.evaluate(()=>document.querySelector('.tabpage.active').id==='recovery'&&AnesvetApp.getState().events.some(e=>e.name==='Extubation')&&AnesvetApp.getState().records.length===1));ck('no browser errors or horizontal overflow',errors.length===0&&await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await context.close();
 }}finally{await browser.close();await new Promise(r=>server.close(r))}console.log(count+'/'+count+' PASS')}
run().catch(e=>{console.error(e);process.exitCode=1});
