'use strict';
const fs=require('fs'),path=require('path'),R=path.resolve(__dirname,'../..');
const exists=p=>fs.existsSync(path.join(R,p));
const files=(p,rx)=>fs.readdirSync(path.join(R,p),{withFileTypes:true}).filter(x=>x.isFile()&&(!rx||rx.test(x.name))).map(x=>x.name);
const rootFiles=files('.'),currentQA=files('qa/current',/\.js$/),runtimeMap=JSON.parse(fs.readFileSync(path.join(R,'config/runtime-map.json'),'utf8'));
const platform=runtimeMap.startupModules.filter(x=>x.group==='platform-foundation');
const clinical=runtimeMap.startupModules.filter(x=>x.group==='clinical-foundation');
const app=runtimeMap.startupModules.filter(x=>x.group==='app-foundation');
const domains=runtimeMap.startupModules.filter(x=>x.group==='domains');
const orch=runtimeMap.startupModules.filter(x=>x.group==='orchestration');
const controllers=runtimeMap.startupModules.filter(x=>x.group==='controllers');
const remaining=runtimeMap.startupModules.filter(x=>!x.path.includes('/'));
const T=[];const add=(n,v)=>T.push([n,!!v]);
add('Package grouping folders exist',['docs/releases','docs/architecture','docs/audits','docs/retirement','qa/current','qa/archive','qa/evidence','src/styles/canonical','src/styles/legacy-active','src/legacy-js','build/history'].every(exists));
add('Root file count reduced to 41 or fewer',rootFiles.length<=41);
add('No release/owner/QA artifacts remain at root',!rootFiles.some(x=>/^(RELEASE_|OWNER_MAP_|QA_)/.test(x)));
add('Current QA suite contains twenty-six scripts including read-only basics lessons regression',currentQA.length===26);
add('Production CSS and icons remain grouped',exists('assets/css/anesvet-ui-bundle.css')&&exists('assets/css/or-workspace-restructure.css')&&exists('assets/icons/icon-192.png'));
add('Platform runtime folder retains five modules',files('runtime/platform',/\.js$/).length===5&&platform.length===5);
add('Clinical runtime folder retains three modules',files('runtime/clinical',/\.js$/).length===3&&clinical.length===3);
add('Core runtime folder contains all ten app foundation modules',exists('runtime/core')&&files('runtime/core',/\.js$/).length===10&&app.length===10);
add('App foundation positions 9–18 live under runtime/core',app.every(x=>x.path.startsWith('runtime/core/')&&exists(x.path)));
add('No app foundation root copies remain',app.every(x=>!exists(path.basename(x.path))));
add('Domains runtime folder contains five modules',exists('runtime/domains')&&files('runtime/domains',/\.js$/).length===5&&domains.length===5);
add('Domain positions 19–23 live under runtime/domains',domains.every(x=>x.path.startsWith('runtime/domains/')&&exists(x.path)));
add('No domain root copies remain',domains.every(x=>!exists(path.basename(x.path))));
add('Orchestration runtime folder contains three modules',exists('runtime/orchestration')&&files('runtime/orchestration',/\.js$/).length===3&&orch.length===3);
add('Orchestration positions 24–26 live under runtime/orchestration',orch.every(x=>x.path.startsWith('runtime/orchestration/')&&exists(x.path)));
add('No orchestration root copies remain',orch.every(x=>!exists(path.basename(x.path))));
add('Controllers runtime folder contains seven modules',exists('runtime/controllers')&&files('runtime/controllers',/\.js$/).length===7&&controllers.length===7);
add('Controller positions 27–33 live under runtime/controllers',controllers.every(x=>x.path.startsWith('runtime/controllers/')&&exists(x.path)));
add('No controller root copies remain',controllers.every(x=>!exists(path.basename(x.path))));
add('Other 36 startup modules intentionally remain at root',remaining.length===36&&remaining.every(x=>exists(x.path)));
add('Session pair no longer remains at root',!exists('session-coordination.js')&&!exists('session-controller.js'));
add('Runtime knowledge folder retains seven lazy modules',files('runtime/knowledge',/\.js$/).length===7&&runtimeMap.lazyModules.length===7);
add('Current BUILD_SHA256 and START_HERE remain at root',exists('BUILD_SHA256.txt')&&exists('START_HERE_TH.txt'));
add('Runtime map exists',exists('config/runtime-map.json'));
add('Retired JS archive remains 13 modules',files('src/legacy-js',/\.js$/).length===13);
add('Canonical/legacy CSS source counts remain 29/9',files('src/styles/canonical',/\.css$/).length===29&&files('src/styles/legacy-active',/\.css$/).length===9);
let p=0;for(const [n,v] of T){console.log((v?'PASS':'FAIL')+'  '+n);if(v)p++;} console.log(`\n${p}/${T.length} PASS`);process.exit(p===T.length?0:1);
