'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict'),{chromium}=require('playwright');
const R=path.resolve(__dirname,'../..');let count=0;const check=(label,ok)=>{assert.ok(ok,label);console.log('PASS '+label);count++};
async function run(){const server=http.createServer((req,res)=>{const p=decodeURIComponent(new URL(req.url,'http://local').pathname),f=path.join(R,p==='/'?'index.html':p);if(!f.startsWith(R+path.sep)||!fs.existsSync(f)||!fs.statSync(f).isFile()){res.writeHead(404);res.end();return}res.setHeader('Content-Type',{'.html':'text/html','.js':'text/javascript','.css':'text/css'}[path.extname(f)]||'application/octet-stream');res.end(fs.readFileSync(f))});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true});try{for(const width of [360,390,1024]){
 const context=await browser.newContext({viewport:{width,height:844},hasTouch:true,isMobile:width<768}),page=await context.newPage(),errors=[];page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());const ck=(s,v)=>check(width+' '+s,v);
 await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>window.AnesvetApp?.version==='17.14.14'&&!document.body.classList.contains('av-booting'));
 await page.evaluate(()=>{for(const [id,v]of[['patientName','QA OR feedback'],['species','cat'],['weight','3'],['patientProcedure','QA'],['procedure','QA'],['asa','II'],['anesthetist','QA']])document.getElementById(id).value=v;const s=AnesvetApp.getState();s.patientSaved=true;s.caseStartedAt=Date.now();s.casePhase='setup';s.timer={elapsedMs:1000,running:true,startedEpoch:Date.now()};s.protocolSnapshot={version:'qa-synthetic',caseDrugPlan:[]};AnesvetApp.save();AnesvetApp.setTab('orlive',{force:true});ANESVET_OR_LIVE_INSTANCE.renderOrLive()});
 await page.locator('#avContextWorkflow').tap();await page.locator('#orStepConfirmGoBtn').tap();await page.waitForFunction(()=>document.getElementById('orPrimaryActionBtn').dataset.action==='airway');
 ck('Induction keeps the native confirmed milestone',await page.evaluate(()=>AnesvetApp.getState().events.some(e=>e.name==='Induction')&&AnesvetApp.getState().casePhase==='induction'));
 const t=await page.locator('#toast').boundingBox();ck('one-line action confirmation uses natural height',t.height>=30&&t.height<=45);
 ck('Undo remains inline and at least 44 px high',await page.locator('#orUndoStepBtn').evaluate(e=>getComputedStyle(e).position==='static'&&getComputedStyle(e).transform==='none'&&e.getBoundingClientRect().height>=44&&e.closest('.or-primary-buttons')));
 ck('Undo uses a neutral surface and compact width',await page.locator('#orUndoStepBtn').evaluate(e=>getComputedStyle(e).backgroundColor==='rgb(246, 251, 249)'&&e.getBoundingClientRect().width<=260));
 const noOverlap=()=>page.evaluate(()=>{const a=document.getElementById('orUndoStepBtn').getBoundingClientRect(),b=document.getElementById('orPrimaryActionBtn').getBoundingClientRect();return !(a.left<b.right&&a.right>b.left&&a.top<b.bottom&&a.bottom>b.top)});
 ck('Undo does not cover the next clinical action',await noOverlap());
 await page.locator('#orPrimaryActionBtn').scrollIntoViewIfNeeded();await page.locator('#orPrimaryActionBtn').tap();await page.waitForFunction(()=>AnesvetApp.getState().events.some(e=>e.name==='Intubation'));
 ck('Intubation is reachable with native timestamp-only behavior',!await page.locator('#orAirwaySetupDialog').isVisible());
 ck('wrapped action confirmation is compact and retains its full text',await page.locator('#toast').evaluate(e=>{const c=getComputedStyle(e);return e.textContent.includes('Intubation timestamp saved')&&e.getBoundingClientRect().height<80&&e.getBoundingClientRect().top>=70&&e.getBoundingClientRect().top<=74&&e.scrollHeight<=e.clientHeight}));
 await page.locator('#orUndoStepBtn').tap();await page.waitForFunction(()=>!AnesvetApp.getState().events.some(e=>e.name==='Intubation'));
 ck('the compact Undo button still reverses the original transition',await page.evaluate(()=>AnesvetApp.getState().events.some(e=>e.name==='Induction')));
 await page.locator('#orPrimaryActionBtn').tap();await page.waitForFunction(()=>AnesvetApp.getState().events.some(e=>e.name==='Intubation'));
 for(const [id,v]of[['orHr','120'],['orMap','80'],['orSpo2','98'],['orEtco2','38'],['orRr','18'],['orTemp','38']])await page.locator('#'+id).fill(v);
 await page.evaluate(()=>{document.getElementById('orTemp').focus({preventScroll:true});document.body.classList.add('anesvet-soft-keyboard');AnesvetApp.toast('✓ Saved 12:34')});
 ck('typing and keyboard styles cannot stretch confirmation',await page.locator('#toast').evaluate(e=>e.getBoundingClientRect().top>=70&&e.getBoundingClientRect().top<=74&&e.getBoundingClientRect().height<45));
 ck('typing cannot turn Undo back into a floating orange bar',await page.locator('#orUndoStepBtn').evaluate(e=>getComputedStyle(e).position==='static'&&getComputedStyle(e).transform==='none'));
 await page.evaluate(()=>{document.activeElement?.blur();document.body.classList.remove('anesvet-soft-keyboard');scrollTo({top:250,behavior:'instant'})});await page.waitForTimeout(70);const y=await page.evaluate(()=>scrollY);
 await page.locator('#avContextPrimary').tap();await page.waitForFunction(()=>AnesvetApp.getState().records.length===1);
 ck('Save records the original six measured values once',await page.evaluate(()=>{const r=AnesvetApp.getState().records[0];return r.hr===120&&r.map===80&&r.spo2===98&&r.etco2===38&&r.rr===18&&Math.abs(r.temp-100.4)<.01}));
 ck('Save shows one compact visual confirmation',await page.locator('#toast').evaluate(e=>e.classList.contains('show')&&e.textContent.includes('Vitals saved')&&e.getBoundingClientRect().height<45)&&!await page.locator('#orVitalSaveFeedback').isVisible());
 ck('Save feedback does not change the reading position',Math.abs(await page.evaluate(()=>scrollY)-y)<12);
 await page.locator('#avContextPrimary').tap();ck('duplicate prevention still rejects a repeated identical record',await page.evaluate(()=>AnesvetApp.getState().records.length===1));
 ck('duplicate warning text remains complete',await page.locator('#toast').evaluate(e=>e.textContent.includes('duplicate prevented')&&e.scrollHeight<=e.clientHeight));
 const before=await page.evaluate(()=>AnesvetApp.getState().events.length);await page.locator('#orUndoStepBtn').scrollIntoViewIfNeeded();await page.locator('#orUndoStepBtn').tap();
 ck('Intubation Undo retains measurements under the original policy',await page.evaluate(n=>AnesvetApp.getState().records.length===1&&AnesvetApp.getState().events.length<n,before));await page.evaluate(()=>AnesvetApp.toast('Undo blocked: clinical data was recorded after this step. Use the documented correction / emergency workflow instead.'));
 ck('longer warning text remains complete',await page.locator('#toast').evaluate(e=>e.textContent.includes('Undo blocked')&&e.scrollHeight<=e.clientHeight));
 await page.waitForTimeout(2300);ck('confirmation dismisses on the existing timer',await page.locator('#toast').evaluate(e=>!e.classList.contains('show')));
 await page.evaluate(()=>{const s=AnesvetApp.getState();s.casePhase='recovery';s.recoveryStartedAt=Date.now();AnesvetApp.save();AnesvetApp.setTab('recovery',{force:true});AnesvetApp.toast('✓ Recovery saved')});
 ck('Recovery confirmation also stays compact',await page.locator('#toast').evaluate(e=>e.getBoundingClientRect().height<45&&e.getBoundingClientRect().top>=70&&e.getBoundingClientRect().top<=74));
 ck('no browser errors or horizontal overflow',errors.length===0&&await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await context.close();
 }}finally{await browser.close();await new Promise(r=>server.close(r))}console.log(count+'/'+count+' PASS')}
run().catch(e=>{console.error(e);process.exitCode=1});
