'use strict';
const fs=require('fs'),path=require('path');const R=path.resolve(__dirname,'../..');
const read=f=>fs.readFileSync(path.join(R,f),'utf8');
const app=read('app.js'),med=read('runtime/controllers/medication-workspace-controller.js'),rec=read('runtime/controllers/recovery-controller.js'),orws=read('or-workspace-restructure.js'),orcss=read('assets/css/or-workspace-restructure.css'),mobile=read('src/styles/canonical/mobile-design.css'),bundle=read('assets/css/anesvet-ui-bundle.css'),map=JSON.parse(read('config/runtime-map.json')),html=read('index.html'),sw=read('service-worker.js');
const T=[];const add=(n,v)=>T.push([n,!!v]);
add('Release is V17.14.5',/const APP_VERSION='17\.14\.5'/.test(app)&&map.release==='17.14.5'&&sw.includes('anesvet-v17-14-5-startup'));
add('Physical pilot UX policy is recorded',String(map.policy?.physicalPilotUxFix||'').includes('vent-direct-mode'));
add('Vent buttons are direct-bound',orws.includes("buttons.forEach(b=>{b.setAttribute('aria-pressed','false');b.addEventListener('click'"));
add('Vent direct action writes authoritative select',orws.includes('select.value=mode')&&orws.includes("select.dispatchEvent(new Event('change',{bubbles:true}))"));
add('Vent action syncs OR mirror select',orws.includes("const mirror=$('orVentilation');if(mirror)mirror.value=mode"));
add('Vent buttons retain active/aria state',orws.includes("b.setAttribute('aria-pressed',active?'true':'false')"));
add('Vent buttons force touch/pointer interactivity',orcss.includes('pointer-events:auto')&&orcss.includes('touch-action:manipulation'));
add('Built-in Tramadol plan defaults to SC',app.includes("name:'Tramadol',origin:'Built-in',phase:'pre',mode:'mgkg'")&&app.includes("tramadolDose'),route:'SC'"));
add('Frozen quick Tramadol defaults to SC',med.includes("['tramadol','Tramadol','tramadolDose','SC','pre','']"));
add('Legacy blank-route Tramadol gets SC fallback',med.includes("normalizeMedicationIdentity(d?.name)==='tramadol'?'SC':''"));
add('Quick editor uses effective route for one-tap readiness',med.includes('const effectiveRoute=defaultRouteForDrug(d),oneTapReady=valid&&!!effectiveRoute'));
add('Quick editor applies effective route preset',med.includes('setQuickRoutePreset(effectiveRoute)'));
add('Standby detector recognizes emergency phase',med.includes("return !!d?.standby||phase==='emergency'"));
add('Auto quick strip excludes standby/emergency',med.includes('if(!d||isStandbyDrug(d))return'));
add('Favorites do not reintroduce standby meds',med.includes('d.favorite===true&&!isStandbyDrug(d)'));
add('Auto-next excludes standby unless emergency context',med.includes('allowStandby||!isStandbyDrug(x.d)'));
add('Emergency medications remain accessible in full workspace',med.includes('Adrenaline CPR')&&med.includes('Atropine — CPR')&&html.includes('All medications'));
add('Bottom bar remains displayed while editing',mobile.includes('body.av-mobile-design.av-editing #avBottom{display:grid!important'));
add('Editing bottom bar is compacted instead of removed',mobile.includes('#avBottom .av-nav button{min-height:42px!important}')&&mobile.includes('#avBottom .av-bottom-context .av-button{min-height:44px!important}'));
add('Mobile overflow containment is present',mobile.includes('overflow-wrap:anywhere')&&mobile.includes('#recovery .table-wrap{max-width:100%;overflow-x:auto'));
add('Workflow undo strip is visible above mobile bottom bar',mobile.includes('#orUndoStepBtn:not([hidden]){position:fixed!important'));
add('Recovery layout organizer exists',rec.includes('function organizeRecoveryLayout()'));
add('Recovery vital records are promoted into primary grid',rec.includes("record.classList.add('recovery-primary-vitals-history')")&&rec.includes('grid.insertBefore(record,obs.nextElementSibling)'));
add('Recovery score is promoted before checklist',rec.includes("score.classList.add('recovery-primary-score')")&&rec.includes('grid.insertBefore(score,record.nextElementSibling)'));
add('Recovery score has tap-first controls',rec.includes('function installRecoveryScoreQuickControls()')&&rec.includes('data-score-value'));
add('Recovery score supports N/A only where allowed',rec.includes("...(allowNA?[['NA','N/A']]:[])"));
add('Score buttons sync active aria state',rec.includes("b.setAttribute('aria-pressed',active?'true':'false')"));
add('Save score is disabled until complete',rec.includes('saveBtn.disabled=!!live.incomplete'));
add('Score save button reports total',rec.includes('Save score • ${live.total}/${live.possible}'));
add('Mobile score controls are styled as large tap targets',mobile.includes('.recovery-score-quick button{min-height:46px'));
add('Runtime bundle contains physical pilot mobile CSS',bundle.includes('V17.14.5 — physical pilot mobile containment + Recovery scoring'));
add('Clinical dose calculation function remains present',med.includes('safeMedicationCalculation'));
add('Drug administration still requires explicit route/by/concentration',med.includes("if(!(actual>0)||!route||!by||!concentration)"));
add('Emergency Return contract remains',rec.includes('emergencyReturnToOr'));
add('Final Lock remains present',html.includes('id="endSaveArchiveBtn"'));
let p=0;for(const [n,v] of T){console.log(`${v?'PASS':'FAIL'}  ${n}`);if(v)p++;}console.log(`\n${p}/${T.length} PASS`);process.exit(p===T.length?0:1);
