'use strict';
// Real touch interactions against the delivered application. Synthetic cases only.
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict'),{chromium}=require('playwright');
const R=path.resolve(__dirname,'../..');let count=0;
const check=(label,ok)=>{assert.ok(ok,label);console.log('PASS '+label);count++};
async function run(){
 const server=http.createServer((req,res)=>{const f=path.join(R,decodeURIComponent(new URL(req.url,'http://local').pathname)==='/'?'index.html':decodeURIComponent(new URL(req.url,'http://local').pathname));if(!f.startsWith(R+path.sep)||!fs.existsSync(f)||!fs.statSync(f).isFile()){res.writeHead(404);res.end();return}res.writeHead(200,{'Content-Type':{'.html':'text/html','.js':'text/javascript','.css':'text/css','.webmanifest':'application/manifest+json'}[path.extname(f)]||'application/octet-stream'});res.end(fs.readFileSync(f))});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const browser=await chromium.launch({channel:'msedge',headless:true});
 try{for(const width of [390,1024]){
  const context=await browser.newContext({viewport:{width,height:844},hasTouch:true}),page=await context.newPage(),errors=[];page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.dismiss());
  await page.goto('http://127.0.0.1:'+server.address().port+'/');await page.waitForFunction(()=>window.AnesvetApp?.version==='17.14.9'&&!document.body.classList.contains('av-booting'));
  const tab=async id=>{await page.evaluate(id=>AnesvetApp.setTab(id,{force:true}),id);await page.waitForTimeout(80)};
  const reveal=async id=>page.evaluate(id=>ANESVET_WORKSPACE_OWNER.openForElement(document.getElementById(id),{persist:false}),id);
  const ck=(s,v)=>check(width+' '+s,v);
  await tab('patient');
  ck('lookup and secondary fields initially collapsed',await page.locator('#patientLookupDetails').evaluate(e=>!e.open)&&await page.locator('#patientSecondaryDetails').evaluate(e=>!e.open));
  await page.locator('#patientLookupDetails summary').tap();ck('patient lookup opens by touch',await page.locator('#patientMasterSearch').isVisible());await page.locator('#patientLookupDetails summary').tap();
  ck('current BW, procedure and cautions remain visible',await page.locator('#weight').isVisible()&&await page.locator('#patientProcedure').isVisible()&&await page.locator('#patientAllergies').isVisible()&&await page.locator('#patientPrecautions').isVisible());
  ck('ASA descriptions stay available for all five choices',await page.locator('#asaGrid .asa-card span:visible').count()===5);
  const unsaved=await page.evaluate(()=>({draft:document.getElementById('saveState').textContent,patient:document.getElementById('patientSaveStatus').textContent}));
  ck('draft storage differs from patient confirmation',unsaved.draft.includes('บันทึกร่าง')&&unsaved.patient.includes('ยังไม่ยืนยัน'));
  await page.locator('#savePatientBtn').scrollIntoViewIfNeeded();await page.locator('#savePatientBtn').tap();
  ck('missing identity does not confirm patient or leave setup',await page.evaluate(()=>!AnesvetApp.getState().patientSaved&&document.querySelector('.tabpage.active').id==='patient'));
  await page.locator('#patientMoreDetailsBtn').scrollIntoViewIfNeeded();await page.locator('#patientMoreDetailsBtn').tap();
  ck('additional details open without duplicate fields',await page.locator('#birthDate').isVisible()&&await page.locator('#surgeon').isVisible());
  await page.locator('#anesthetist').fill('QA veterinarian');await page.locator('#surgeon').fill('QA surgeon');
  await page.locator('#patientMoreDetailsBtn').scrollIntoViewIfNeeded();await page.locator('#patientMoreDetailsBtn').tap();await reveal('microchip');
  ck('focus coordinator opens a hidden secondary target',await page.locator('#microchip').isVisible());
  await page.evaluate(()=>ANESVET_PATIENT_PREOP_SIMPLIFICATION.setDetails(false,false));
  await page.locator('#patientName').fill('QA synthetic patient');await page.locator('#species').selectOption('cat');await page.locator('#weight').fill('3');await page.locator('#patientProcedure').fill('QA procedure');await page.locator('.asa-card[data-asa="II"]').tap();
  await page.locator('#savePatientBtn').scrollIntoViewIfNeeded();await page.locator('#savePatientBtn').tap();await page.waitForFunction(()=>AnesvetApp.getState().patientSaved&&document.querySelector('.tabpage.active').id==='preop');
  ck('original save confirms current BW and enters pre-check',await page.evaluate(()=>Number(AnesvetApp.getState().weight)===3&&document.getElementById('patientSaveStatus').classList.contains('good')));
  ck('pre-check groups do not mark clinical checks automatically',await page.locator('#preop .preop-check:checked').count()===0&&await page.locator('#preopQuickActionBtn').isVisible()&&!await page.locator('#preopNextIncompleteBtn').isVisible());
  await page.locator('#preopQuickActionBtn').tap();await page.waitForTimeout(200);
  ck('next task opens the missing physical exam',await page.locator('#preopExamDetails').evaluate(e=>e.open)&&await page.locator('#preopMentation').isVisible());
  await tab('drugs');
  ck('case plan precedes both optional drug workspaces',await page.evaluate(()=>{const p=document.querySelector('.case-drug-plan-panel'),presets=document.getElementById('drugPresetsDetails'),tools=document.getElementById('drugToolsDetails');return !!(p.compareDocumentPosition(presets)&Node.DOCUMENT_POSITION_FOLLOWING)&&!!(p.compareDocumentPosition(tools)&Node.DOCUMENT_POSITION_FOLLOWING)&&!presets.open&&!tools.open}));
  ck('drug workflow uses readable foreground and background',await page.locator('#drugWorkflowFocusTitle').evaluate(e=>getComputedStyle(e).color==='rgb(18, 62, 54)'&&getComputedStyle(document.getElementById('drugWorkflowFocus')).backgroundColor==='rgb(237, 247, 243)'));
  const action=await page.locator('#drugWorkflowPrimaryBtn').innerText();ck('one primary action routes through original plan owner',/ยืนยันแผนยา|สร้างแผน/.test(action));
  await page.locator('#drugWorkflowPrimaryBtn').tap();await page.waitForTimeout(120);
  if(await page.evaluate(()=>ANESVET_DRUG_START_SIMPLIFICATION.actionForPlan()==='review'))await page.locator('#drugWorkflowPrimaryBtn').tap();
  ck('review records native plan confirmation without starting case',await page.evaluate(()=>!!AnesvetApp.getState().caseDrugPlanReviewedAt&&!AnesvetApp.getState().caseStartedAt));
  await page.locator('#drugPresetsDetails summary').tap();
  ck('Quick Presets can still be opened',await page.locator('#drugPresetsDetails').evaluate(e=>e.open));
  await page.locator('#drugPresetsDetails summary').focus();await page.keyboard.press('Enter');const closed=await page.locator('#drugPresetsDetails').evaluate(e=>!e.open);await page.keyboard.press('Enter');ck('disclosures toggle by keyboard without focus reopening them',closed&&await page.locator('#drugPresetsDetails').evaluate(e=>e.open));
  await page.evaluate(()=>{const s=AnesvetApp.getState();s.caseStartedAt=Date.now();s.casePhase='intraop';s.protocolSnapshot={version:'qa-synthetic',caseDrugPlan:[{id:'meloxicamDose',name:'Meloxicam',phase:'post',mode:'manual',route:'SC',conc:5,concUnit:'mg/mL'}]};AnesvetApp.save({reason:'qa-ux'});});await tab('orlive');await page.evaluate(()=>ANESVET_OR_LIVE_INSTANCE.renderOrLive());
  const save=await page.locator('#orVitalsFocusSaveBtn').boundingBox();
  ck('Vitals save is a readable full-size touch target',save.width>=250&&save.height>=48&&await page.locator('#orVitalsFocusSaveBtn').innerText()==='＋ บันทึก Vitals');
  await page.locator('[data-or-workspace="meds"]').tap();await page.locator('.or-medication-record-btn').tap();
  ck('actual fields precede optional medication reference',await page.evaluate(()=>!!(document.querySelector('#orQuickDrugSingleEditor .quick-drug-fields').compareDocumentPosition(document.getElementById('orQuickDrugReferenceDetails'))&Node.DOCUMENT_POSITION_FOLLOWING)));
  ck('medication editor retains selected route and explicit save',await page.locator('#orQuickDrugRoute').inputValue()==='SC'&&await page.locator('#orQuickDrugSaveBtn').isVisible()&&await page.evaluate(()=>AnesvetApp.getState().drugAdministrations.length===0));
  await page.locator('#orQuickDrugDoneBtn').tap();ck('back closes editor without medication administration',await page.locator('#orQuickDrugDialog').evaluate(e=>!e.open)&&await page.evaluate(()=>AnesvetApp.getState().drugAdministrations.length===0));
  await page.evaluate(()=>{const s=AnesvetApp.getState();s.casePhase='recovery';s.recoveryStartedAt=Date.now();s.extubationAt=Date.now();AnesvetApp.save({reason:'qa-recovery'});});await tab('recovery');
  ck('Temp units stay inline and extubation placeholder fits',await page.locator('#recTempUnitLabel').evaluate(e=>getComputedStyle(e).display==='inline')&&await page.locator('#recExtubation').getAttribute('placeholder')==='HH:MM');
  ck('assessment save follows all five domains and blocks incomplete input',await page.evaluate(()=>!!(document.querySelector('.recovery-score-grid').compareDocumentPosition(document.getElementById('saveRecoveryScoreBtn'))&Node.DOCUMENT_POSITION_FOLLOWING))&&await page.locator('#saveRecoveryScoreBtn').isDisabled());
  for(const id of ['recScoreAirway','recScoreOxygen','recScoreTemp','recScoreMentation','recScoreComfort'])await page.locator('#'+id).selectOption('2');
  await page.waitForFunction(()=>document.getElementById('recoveryAssessmentProgress').textContent.includes('ประเมินครบ'));
  ck('assessment progress becomes complete',await page.locator('#recoveryAssessmentProgress').innerText().then(t=>t.includes('ประเมินครบ'))&&!await page.locator('#saveRecoveryScoreBtn').isDisabled());
  await page.locator('#saveRecoveryScoreBtn').scrollIntoViewIfNeeded();await page.locator('#saveRecoveryScoreBtn').tap();
  ck('original score semantics persist 10/10',await page.evaluate(()=>AnesvetApp.getState().recoveryScores.at(-1)?.total===10&&AnesvetApp.getState().recoveryScores.at(-1)?.possible===10));
  await page.locator('#recScoreOxygen').selectOption('NA');await page.locator('#saveRecoveryScoreBtn').scrollIntoViewIfNeeded();await page.locator('#saveRecoveryScoreBtn').tap();
  ck('N/A without reason still cannot save a score',await page.evaluate(()=>AnesvetApp.getState().recoveryScores.length===1));
  await tab('endcase');ck('pending medications, sign-off and blockers stay visible',await page.locator('#medicationReconciliationPanel').isVisible()&&await page.locator('.final-signoff-panel').isVisible()&&await page.locator('#endCaseBlockers').isVisible());
  await page.locator('#endSaveArchiveBtn').scrollIntoViewIfNeeded();await page.locator('#endSaveArchiveBtn').tap();ck('incomplete case cannot final-lock',await page.evaluate(()=>!AnesvetApp.getState().caseLocked));
  await tab('endcase');await reveal('endDocumentationGuardian');ck('full documentation review remains reachable',await page.locator('#endDocumentationGuardian').isVisible());
  await page.evaluate(()=>{document.getElementById('finalArchiveAssuranceBadge').textContent='VERIFY FAILED';ANESVET_REPEAT_PRESENTATION_OWNER.repaint()});ck('archive result reveals verification details',await page.locator('#endArchiveDetails').evaluate(e=>e.open));
  ck('runtime DOM has unique IDs and no horizontal overflow',await page.evaluate(()=>{const ids=[...document.querySelectorAll('[id]')].map(e=>e.id);return new Set(ids).size===ids.length&&document.documentElement.scrollWidth<=innerWidth}));
  await page.evaluate(()=>document.fonts.ready);ck('bundled Thai and Latin fonts load',await page.evaluate(()=>{const fonts=[...document.fonts];return ['ANESVET Thai','Inter'].every(name=>fonts.some(f=>f.family.replace(/"/g,'')===name&&f.status==='loaded'))}));
  ck('full application has no browser errors',errors.length===0);await context.close();
 }}finally{await browser.close();await new Promise(resolve=>server.close(resolve))}console.log(count+'/'+count+' PASS');
}
run().catch(e=>{console.error(e);process.exitCode=1});
