'use strict';
const path=require('path'),cryptoNode=require('crypto');
const R=path.resolve(__dirname,'../..');
global.window=global;global.CustomEvent=global.CustomEvent||class{constructor(type,init={}){this.type=type;this.detail=init.detail}};global.Event=global.Event||class{constructor(type){this.type=type}};
const T=[];const add=(n,v,d='')=>T.push([n,!!v,d]);
const fs=require('fs');const read=f=>fs.readFileSync(path.join(R,f),'utf8');
const pilotSrc=read('production-pilot.js');
add('Stress: Production Pilot cache check is current-build dynamic',pilotSrc.includes('function expectedCacheName()')&&!pilotSrc.includes('anesvet-v16-21-0')&&pilotSrc.includes('expectedCacheName,scenarios'));
global.AnesvetApp={version:'17.14.6'};const pilotApi=require(path.join(R,'production-pilot.js'));add('Stress: Production Pilot expected cache resolves to current release',pilotApi.expectedCacheName()==='anesvet-v17-14-6-startup');
class CL{constructor(){this.s=new Set()}add(...x){x.forEach(v=>this.s.add(v))}remove(...x){x.forEach(v=>this.s.delete(v))}toggle(x,on){if(on===undefined){if(this.s.has(x)){this.s.delete(x);return false}this.s.add(x);return true}if(on)this.s.add(x);else this.s.delete(x);return !!on}contains(x){return this.s.has(x)}}
class El{constructor(id=''){this.id=id;this.value='';this.textContent='';this.innerHTML='';this.hidden=false;this.disabled=false;this.checked=false;this.open=false;this.dataset={};this.classList=new CL();this.tagName='INPUT';this.type='text';this.style={setProperty(){}};this.listeners={};this.attrs={};}addEventListener(t,f){(this.listeners[t]??=[]).push(f)}dispatchEvent(e){for(const f of this.listeners[e.type]||[])f.call(this,e);return true}setAttribute(k,v){this.attrs[k]=String(v);if(k==='open')this.open=true}removeAttribute(k){delete this.attrs[k];if(k==='open')this.open=false}focus(){global.document.activeElement=this}blur(){if(global.document.activeElement===this)global.document.activeElement=null}closest(sel){if(sel==='.signoff-card')return this._card||(this._card=new El('card'));return null}querySelector(){return null}querySelectorAll(){return[]}scrollIntoView(){}click(){this.dispatchEvent({type:'click',target:this,preventDefault(){},stopImmediatePropagation(){}})}}
const els={};const $=id=>els[id]||(els[id]=new El(id));const $$=()=>[];
const docListeners={};global.document={activeElement:null,body:new El('body'),documentElement:new El('html'),visibilityState:'visible',readyState:'loading',addEventListener(t,f){(docListeners[t]??=[]).push(f)},dispatchEvent(e){for(const f of docListeners[e.type]||[])f.call(this,e);return true},getElementById:id=>$(id),querySelector(){return null},querySelectorAll(){return[]},createElement(){return new El()},createElementNS(){return new El()}};
Object.defineProperty(global,'navigator',{value:{onLine:true,userAgent:'node',platform:'test',language:'en',maxTouchPoints:0},configurable:true});global.matchMedia=()=>({matches:false});global.innerWidth=390;global.innerHeight=844;global.screen={width:390,height:844};global.devicePixelRatio=1;
const mem=new Map();global.localStorage={getItem:k=>mem.has(k)?mem.get(k):null,setItem:(k,v)=>mem.set(k,String(v)),removeItem:k=>mem.delete(k)};global.sessionStorage={getItem(){return null},setItem(){}};

// 1) High-volume vital + duplicate/correction using production domain/orchestration.
require(path.join(R,'runtime/domains/or-domain.js'));require(path.join(R,'runtime/orchestration/or-record-orchestration.js'));
const od=global.ANESVET_OR_DOMAIN,oo=global.ANESVET_OR_RECORD_ORCHESTRATION;let recs=[],corr=[];const base=1_000_000;
for(let i=0;i<720;i++){const snap={id:`R${i}`,epoch:base+i*15000,elapsedMs:i*15000,hr:90+(i%30),rr:12+(i%8),sap:null,map:i%9===0?45:72,dap:null,spo2:98,etco2:38,temp:100.1,vaporizer:1.8,o2flow:1,fluidRate:20,fluidTotal:i,depth:'',ventilation:'',note:''};const c=oo.commitVital(recs,snap,{guardMs:12000,findDuplicate:od.recentExactVitalDuplicate});if(!c.ok)throw new Error('unexpected vital reject '+i);recs=c.records;}
add('Stress: 720 serial OR vital records persist in chronological order',recs.length===720&&recs.every((r,i)=>i===0||r.epoch>=recs[i-1].epoch));
let dupe={...recs.at(-1),id:'DUP',epoch:recs.at(-1).epoch+5000,elapsedMs:recs.at(-1).elapsedMs+5000};let dc=oo.commitVital(recs,dupe,{guardMs:12000,findDuplicate:od.recentExactVitalDuplicate});add('Stress: exact vital duplicate inside guard window is rejected',!dc.ok&&dc.reason==='duplicate'&&recs.length===720);
let changed={...dupe,id:'CHANGED',map:71};let cc=oo.commitVital(recs,changed,{guardMs:12000,findDuplicate:od.recentExactVitalDuplicate});recs=cc.records;add('Stress: clinically changed vital set inside guard window is accepted',cc.ok&&recs.length===721&&recs.at(-1).map===71);
let cr=oo.applyCorrection(recs,corr,{recordId:'R350',field:'map',newValue:68,reason:'transcription correction',epoch:base+999999,clock:'12:00',id:'C1'});recs=cr.records;corr=cr.corrections;add('Stress: correction keeps record count and appends immutable audit correction',cr.ok&&recs.length===721&&corr.length===1&&recs.find(r=>r.id==='R350').map===68&&cr.oldValue!==68);

// 2) Medication duplicate/retrospective/void using production controller.
const medMod=require(path.join(R,'runtime/controllers/medication-workspace-controller.js'));const medState={caseId:'S1',casePhase:'intraop',caseStartedAt:base,protocolSnapshot:{capturedAt:base,version:'P1'},drugAdministrations:[],auditTrail:[],events:[]};let confirmAnswer=true,saveCount=0;const promptAnswers=[];
['drugAdministrationAudit','drugAuditCount','anesthetist'].forEach(id=>$(id));$('anesthetist').value='Dr Test';
const medCtl=medMod.create({$,$$,workflow:{clone:v=>JSON.parse(JSON.stringify(v)),numeric:v=>Number(v)},getState:()=>medState,clinicalWriteAllowed:()=>true,permissionAllowed:()=>true,ensureTimerStarted:()=>true,currentElapsed:()=>500000,currentWeightKg:()=>10,currentWeightReady:()=>true,requireCurrentWeight:()=>true,confirm:()=>confirmAnswer,prompt:(m,d)=>promptAnswers.length?promptAnswers.shift():d,formatClock:e=>`T${e}`,formatShortElapsed:m=>String(m),fmtDose:v=>String(v),save:()=>{saveCount++},addEvent:e=>{const x={id:'E'+(medState.events.length+1),...e,...(e.meta||{})};delete x.meta;medState.events.push(x);return x},addAudit:(action,detail,actor)=>medState.auditTrail.push({action,detail,actor}),renderEvents(){},renderProcedureTimeline(){},renderOrLive(){},renderOrMedicationQueue(){},renderOrPrimaryFlow(){}});
let m1=medCtl.recordDrugAdministration({drug:'Propofol',actual:1,route:'IV',administeredBy:'Dr Test',adminEpoch:2_000_000,adminElapsedMs:1000,source:'Manual'});confirmAnswer=false;let blocked=medCtl.recordDrugAdministration({drug:'Propofol',actual:0.5,route:'IV',administeredBy:'Dr Test',adminEpoch:2_060_000,adminElapsedMs:61000,source:'Manual'});add('Stress: near-duplicate medication requires explicit confirmation',!!m1&&!blocked&&medState.drugAdministrations.length===1);
confirmAnswer=true;let m2=medCtl.recordDrugAdministration({drug:'Propofol',actual:0.5,route:'IV',administeredBy:'Dr Test',adminEpoch:2_060_000,adminElapsedMs:61000,source:'Manual'});let m0=medCtl.recordDrugAdministration({drug:'Cefazolin',actual:0.3,route:'IV',administeredBy:'Dr Test',adminEpoch:1_900_000,adminElapsedMs:0,source:'Manual',retrospective:true});add('Stress: confirmed repeat medication and retrospective entry remain chronological',!!m2&&!!m0&&medState.drugAdministrations.length===3&&medState.drugAdministrations[0].drug==='Cefazolin'&&medState.drugAdministrations.at(-1).id===m2.id);
promptAnswers.push('duplicate charting correction','Dr Test');medCtl.voidDrugAdministration(m2.id);add('Stress: void retains original administration and adds audit event',medState.drugAdministrations.length===3&&!!medState.drugAdministrations.find(x=>x.id===m2.id).voidedAt&&medState.auditTrail.some(x=>x.action==='DRUG_ADMIN_VOIDED')&&medState.events.some(x=>x.drugAdministrationVoid));

// 3) Recovery repeated emergency return cycles using production controller.
require(path.join(R,'runtime/domains/recovery-domain.js'));require(path.join(R,'runtime/orchestration/recovery-orchestration.js'));const recMod=require(path.join(R,'runtime/controllers/recovery-controller.js'));const recState={caseId:'S1',caseStartedAt:base,casePhase:'recovery',recoveryStartedAt:3_000_000,recoveryCompletedAt:null,emergencyReturnActive:false,recoveryRecords:[],recoveryScores:[],recoveryObservationNA:{},timer:{running:true}};let recEvents=[],recSaves=0,tabs=[];const recCtl=recMod.create({$,$$,recoveryDomain:global.ANESVET_RECOVERY_DOMAIN,recoveryOrchestration:global.ANESVET_RECOVERY_ORCHESTRATION,getState:()=>recState,clinicalWriteAllowed:()=>true,confirm:()=>true,toast(){},addEvent:e=>recEvents.push(e),save:()=>{recSaves++},renderCasePhase(){},setTab:t=>tabs.push(t),captureRecoveryHandoff(){},formatClock:e=>String(e),formatElapsed:m=>String(m),formatShortElapsed:m=>String(m),tempInputStoredF:()=>100,tempStoredFToDisplay:v=>v,tempSymbol:()=>'°F',renderWorkflowLocks(){},renderProcedureTimeline(){},renderEndCase(){},renderOrLive(){},currentElapsed:()=>1000,autoWakeEnabled:()=>false,plausibilityWarnings:()=>[],confirmPlausibility:()=>true,bumpAlertObservationRevision(){},activeAlertProtocol:()=>({}),syncAlertEpisodes(){},pauseTimer(){recState.timer.running=false},releaseScreenWakeLock(){}});
for(let i=0;i<10;i++){recCtl.emergencyReturnToOr();if(!(recState.casePhase==='emergency'&&recState.emergencyReturnActive))throw new Error('emergency cycle failed '+i);recCtl.returnAfterEmergency();if(!(recState.casePhase==='recovery'&&!recState.emergencyReturnActive))throw new Error('return cycle failed '+i);}
add('Stress: 10 Emergency Return cycles preserve original Recovery start and recover mode',recState.recoveryStartedAt===3_000_000&&recState.casePhase==='recovery'&&!recState.emergencyReturnActive&&recEvents.filter(x=>/emergency return/i.test(x.name)).length===10&&recEvents.filter(x=>/Returned to recovery/i.test(x.name)).length===10);
recCtl.emergencyReturnToOr();recCtl.complete();add('Stress: Recovery completion remains blocked during active Emergency Return',recState.casePhase==='emergency'&&recState.recoveryCompletedAt==null);recCtl.returnAfterEmergency();

// 4) Active-case freshness blocks stale writer.
const freshMod=require(path.join(R,'active-case-freshness.js'));let shared='A',blockedReason='';const fg=freshMod.create({read:()=>shared,onBlocked:r=>{blockedReason=r}});add('Stress: freshness guard establishes on hydrated payload',fg.establish()&&fg.verify());shared='B';add('Stress: external case change permanently blocks stale writer',fg.verify()===false&&fg.isBlocked()&&blockedReason==='external-case-change'&&fg.committed('C')===false);

// 5) Session collision / takeover / stale owner.
const realNow=Date.now,realSetInterval=global.setInterval,realClearInterval=global.clearInterval;let clock=5_000_000;Date.now=()=>clock;global.setInterval=()=>1;global.clearInterval=()=>{};const sharedLs=new Map();global.localStorage={getItem:k=>sharedLs.has(k)?sharedLs.get(k):null,setItem:(k,v)=>sharedLs.set(k,String(v)),removeItem:k=>sharedLs.delete(k)};global.window.addEventListener=()=>{};delete global.BroadcastChannel;require(path.join(R,'runtime/core/session-coordination.js'));const makeSS=id=>({getItem:k=>k==='tab'?id:null,setItem(){}});global.sessionStorage=makeSS('A');const a=global.ANESVET_SESSION_COORDINATION.create({lockKey:'lock',tabKey:'tab',ttlMs:30000,heartbeatMs:5000,appVersion:'17.14.6',getCaseInfo:()=>({caseId:'C',patientName:'P'})});add('Stress: first session becomes active owner',a.init()==='active'&&a.readLock().tabId==='A');global.sessionStorage=makeSS('B');const b=global.ANESVET_SESSION_COORDINATION.create({lockKey:'lock',tabKey:'tab',ttlMs:30000,heartbeatMs:5000,appVersion:'17.14.6'});add('Stress: second fresh tab starts view-only',b.init()==='view'&&b.getMode()==='view');b.takeControl();add('Stress: explicit takeover transfers shared owner',b.getMode()==='active'&&b.readLock().tabId==='B'&&a.verifyOwnership()===false&&a.getMode()==='view');clock+=31000;const ar=a.refresh();add('Stress: stale owner can be recovered after TTL',ar.mode==='active'&&a.readLock().tabId==='A');Date.now=realNow;global.setInterval=realSetInterval;global.clearInterval=realClearInterval;

// Restore localStorage for remaining tests.
global.localStorage={getItem:k=>mem.has(k)?mem.get(k):null,setItem:(k,v)=>mem.set(k,String(v)),removeItem:k=>mem.delete(k)};

// 6) PWA freeze + BFCache restore callbacks.
global.ANESVET_APP_SHELL={$};let lifecyclePageshow=null,rootListeners={};global.addEventListener=(t,f)=>(rootListeners[t]??=[]).push(f);global.ANESVET_LIFECYCLE_COORDINATOR={subscribe:(name,f)=>{if(name==='pageshow')lifecyclePageshow=f}};const realTimeout=global.setTimeout;global.setTimeout=f=>{f();return 1};const pwaMod=require(path.join(R,'runtime/domains/pwa-controller.js'));let flushed=0,restored=0;const pwa=pwaMod.create({flushOnFreeze:()=>flushed++,restoreAfterBFCache:()=>restored++,serviceWorkerUrl:'./service-worker.js'});pwa.bind();for(const f of docListeners.freeze||[])f({type:'freeze'});lifecyclePageshow?.({detail:{persisted:true}});add('Stress: freeze flush and BFCache persisted restore callbacks both fire',flushed===1&&restored===1);global.setTimeout=realTimeout;

// 7) Large backup integrity / tamper detection.
const backupMod=require(path.join(R,'runtime/controllers/backup-restore-controller.js'));const backupState={caseId:'BIG',patientName:'Stress',records:Array.from({length:1200},(_,i)=>({id:`r${i}`,epoch:base+i*10000,map:60+i%20,hr:90+i%30})),events:Array.from({length:200},(_,i)=>({id:`e${i}`,epoch:base+i*60000,name:'event'})),drugAdministrations:Array.from({length:80},(_,i)=>({id:`d${i}`,epoch:base+i*90000,drug:'Drug',actual:1,route:'IV'}))};const backupCtl=backupMod.create({$,getState:()=>backupState,keys:{},getArchive:()=>[],getPatients:()=>[],getArchiveBackend:()=>'test',getPatientBackend:()=>'test'});const payload={format:'ANESVET_BACKUP',backupSchema:3,version:'17.14.6',current:JSON.parse(JSON.stringify(backupState)),archive:[],patients:[]};
(async()=>{payload.integrityManifest=await backupCtl.createIntegrityManifest(payload);let ok=await backupCtl.verifyBackupPayloadIntegrity(payload);add('Stress: large backup payload passes SHA-256 payload + clinical integrity',ok.payload.valid===true&&ok.clinical.valid===true);payload.current.records[777].map=999;let bad=await backupCtl.verifyBackupPayloadIntegrity(payload);add('Stress: single-field tamper in large active case is detected',bad.payload.valid===false&&bad.clinical.valid===false);

// 8) Final Lock gating + idempotent blocked second finalize through clinicalWriteAllowed.
const finMod=require(path.join(R,'runtime/controllers/finalization-archive-controller.js'));const finState={caseId:'SIM-FINAL',simulationMode:true,casePhase:'recovery',caseLocked:false,recoveryCompletedAt:9_000_000,alertEpisodes:[],complications:[],protocolSnapshot:{caseDrugPlan:[]},caseDrugPlan:[],drugAdministrations:[],finalSignoff:{anesthetist:{name:'Dr A',epoch:1},surgeon:{name:'Dr S',epoch:1}},records:[],events:[],recoveryScores:[],timer:{running:false}};['endcase','endPatient','endProcedure','endDuration','endRecordCount','endEventCount','endDrugAdminCount','endActiveComplications','endRecoveryStatus','endRecoveryScore','endFluidTotal','endBloodLoss','endUrine','finalSignoffStatus','endCaseReadiness','endConfirmRecovery','endConfirmRecord','endConfirmDrugs','endConfirmPdf','signoffAnesthetistName','signoffAnesthetistTime','signAnesthetistBtn','signoffSurgeonName','signoffSurgeonTime','signSurgeonBtn','patientName','species','weight','procedure','anesthetist','surgeon'].forEach(id=>$(id));$('patientName').value='Stress';$('species').value='dog';$('weight').value='10';$('procedure').value='Test';$('anesthetist').value='Dr A';$('surgeon').value='Dr S';['endConfirmRecovery','endConfirmRecord','endConfirmDrugs','endConfirmPdf'].forEach(id=>$(id).checked=true);let finSaves=0,toasts=[];const fin=finMod.create({$,$$,getState:()=>finState,clinicalWriteAllowed:()=>!finState.caseLocked,toast:m=>toasts.push(m),confirm:()=>true,currentElapsed:()=>0,getFluidMetrics:()=>({totalIn:0,loss:0,urine:0}),currentSettingsObject:()=>({defaultReport:'summary'}),computeCaseChecksum:async()=>cryptoNode.createHash('sha256').update(JSON.stringify(finState)).digest('hex'),addAudit(){},save:()=>{finSaves++},renderCasePhase(){},releaseScreenWakeLock:async()=>{},formatClock:e=>String(e),formatDate:e=>String(e),formatElapsed:e=>String(e),setTab(){}});await fin.finalizeCase();const lockedAt=finState.lockedAt;add('Stress: eligible simulation Final Lock seals record and creates checksum',finState.caseLocked&&finState.casePhase==='complete'&&!!finState.finalChecksum&&finSaves===1);await fin.finalizeCase();add('Stress: second Final Lock call is blocked after sealed state',finState.lockedAt===lockedAt&&finSaves===1);
const finState2={...finState,caseId:'BLOCK',caseLocked:false,casePhase:'recovery',finalChecksum:null,lockedAt:null,alertEpisodes:[{id:'A1',resolvedAt:null}],finalSignoff:{anesthetist:{name:'Dr A',epoch:1},surgeon:{name:'Dr S',epoch:1}}};const fin2=finMod.create({$,$$,getState:()=>finState2,clinicalWriteAllowed:()=>!finState2.caseLocked,toast:m=>toasts.push(m),confirm:()=>true,currentElapsed:()=>0,getFluidMetrics:()=>({totalIn:0,loss:0,urine:0}),currentSettingsObject:()=>({defaultReport:'summary'}),computeCaseChecksum:async()=>'',save(){},formatClock:e=>String(e),formatDate:e=>String(e),formatElapsed:e=>String(e)});await fin2.finalizeCase();add('Stress: unresolved alert blocks Final Lock',!finState2.caseLocked&&toasts.some(x=>/Resolve active alerts/i.test(x)));

let pass=0;for(const [n,v,d] of T){console.log(`${v?'PASS':'FAIL'}  ${n}${d?` — ${d}`:''}`);if(v)pass++;}console.log(`\n${pass}/${T.length} PASS`);process.exit(pass===T.length?0:1);
})().catch(e=>{console.error(e);process.exit(1)});
